"""Project-level configuration for paths, runtime settings, and environment management"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/config.ipynb.

# %% auto 0
__all__ = ['RuntimeMode', 'CondaType', 'RuntimeConfig', 'CJMConfig', 'load_config', 'get_config', 'set_config', 'reset_config']

# %% ../../nbs/core/config.ipynb 3
import os
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Dict, Optional

import yaml

# %% ../../nbs/core/config.ipynb 5
class RuntimeMode(str, Enum):
    """Runtime mode for the plugin system."""
    LOCAL = "local"    # Project-local runtime and data
    SYSTEM = "system"  # System-wide conda and ~/.cjm data


class CondaType(str, Enum):
    """Type of conda implementation to use."""
    MICROMAMBA = "micromamba"
    MINIFORGE = "miniforge"
    CONDA = "conda"

# %% ../../nbs/core/config.ipynb 7
@dataclass
class RuntimeConfig:
    """Runtime environment configuration."""
    mode:RuntimeMode=RuntimeMode.SYSTEM # LOCAL for project-local, SYSTEM for global
    conda_type:CondaType=CondaType.CONDA # Conda implementation to use
    prefix:Optional[Path]=None # Path to runtime directory (LOCAL mode only)
    binaries:Dict[str, Path]=field(default_factory=dict) # Platform-specific binary paths

# %% ../../nbs/core/config.ipynb 8
@dataclass
class CJMConfig:
    """Main configuration for cjm-plugin-system."""
    runtime:RuntimeConfig=field(default_factory=RuntimeConfig) # Runtime environment settings
    data_dir:Path=field(default_factory=lambda: Path.home() / ".cjm") # Base directory for manifests, logs
    plugins_config:Path=field(default_factory=lambda: Path("plugins.yaml")) # Path to plugins.yaml file
    models_dir:Optional[Path]=None # Directory for model downloads

    @property
    def plugins_dir(self) -> Path: # Directory containing plugin manifests
        """Directory containing plugin manifests."""
        return self.data_dir / "plugins"

    @property
    def logs_dir(self) -> Path: # Directory containing plugin logs
        """Directory containing plugin logs."""
        return self.data_dir / "logs"

# %% ../../nbs/core/config.ipynb 10
# Module-level configuration singleton
_current_config: Optional[CJMConfig] = None

# %% ../../nbs/core/config.ipynb 11
def _load_from_yaml(
    yaml_path:Path # Path to cjm.yaml file
) -> CJMConfig: # Parsed configuration
    """Load config from YAML file, resolving relative paths."""
    with open(yaml_path) as f:
        data = yaml.safe_load(f) or {}

    # Resolve relative paths against yaml file location
    base_dir = yaml_path.parent.resolve()

    # Parse runtime config
    runtime_data = data.get("runtime", {})
    runtime = RuntimeConfig(
        mode=RuntimeMode(runtime_data.get("mode", "system")),
        conda_type=CondaType(runtime_data.get("conda_type", "conda")),
        prefix=base_dir / runtime_data["prefix"] if runtime_data.get("prefix") else None,
        binaries={k: base_dir / v for k, v in runtime_data.get("binaries", {}).items()}
    )

    # Parse top-level config
    config = CJMConfig(runtime=runtime)

    if "data_dir" in data:
        config.data_dir = base_dir / data["data_dir"]
    if "plugins_config" in data:
        config.plugins_config = base_dir / data["plugins_config"]
    if "models_dir" in data:
        config.models_dir = base_dir / data["models_dir"]

    return config

# %% ../../nbs/core/config.ipynb 12
def load_config(
    config_path:Optional[Path]=None, # CLI --cjm-config
    data_dir:Optional[Path]=None, # CLI --data-dir
    conda_prefix:Optional[Path]=None, # CLI --conda-prefix
    conda_type:Optional[str]=None # CLI --conda-type
) -> CJMConfig: # Resolved configuration
    """Load config with layered resolution (CLI > env vars > yaml > defaults)."""
    # 1. Start with defaults
    config = CJMConfig()

    # 2. Load cjm.yaml if exists (specified or in cwd)
    yaml_path = config_path or Path("cjm.yaml")
    if yaml_path.exists():
        config = _load_from_yaml(yaml_path)

    # 3. Override with environment variables
    if env_data_dir := os.environ.get("CJM_DATA_DIR"):
        config.data_dir = Path(env_data_dir)
    if env_conda_prefix := os.environ.get("CJM_CONDA_PREFIX"):
        config.runtime.prefix = Path(env_conda_prefix)
    if env_conda_type := os.environ.get("CJM_CONDA_TYPE"):
        config.runtime.conda_type = CondaType(env_conda_type)

    # 4. Override with CLI args (highest priority)
    if data_dir:
        config.data_dir = data_dir
    if conda_prefix:
        config.runtime.prefix = conda_prefix
    if conda_type:
        config.runtime.conda_type = CondaType(conda_type)

    return config

# %% ../../nbs/core/config.ipynb 14
def get_config() -> CJMConfig: # Current configuration
    """Get current config (loads defaults if not set)."""
    global _current_config
    if _current_config is None:
        _current_config = load_config()
    return _current_config


def set_config(
    config:CJMConfig # Configuration to set as current
) -> None:
    """Set current config (called by CLI callback)."""
    global _current_config
    _current_config = config


def reset_config() -> None:
    """Reset to unloaded state (for testing)."""
    global _current_config
    _current_config = None
