"""Persistent storage for per-plugin configuration (with enabled flag)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/config_store.ipynb.

# %% auto #0
__all__ = ['PluginConfigRecord', 'PluginConfigStore', 'LocalPluginConfigStore']

# %% ../../nbs/core/config_store.ipynb #exports
import json
import sqlite3
import time
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterator, Optional, Protocol, runtime_checkable

import logging
_logger = logging.getLogger(__name__)

# %% ../../nbs/core/config_store.ipynb #record
@dataclass
class PluginConfigRecord:
    """Persisted state for a plugin: config dict + enabled flag."""
    config: Dict[str, Any] = field(default_factory=dict)  # Plugin's current config values
    enabled: bool = True  # Whether the substrate should accept jobs for this plugin
    updated_at: float = 0.0  # Unix timestamp of the last write (server clock)

# %% ../../nbs/core/config_store.ipynb #protocol
@runtime_checkable
class PluginConfigStore(Protocol):
    """Protocol for persisting per-plugin `PluginConfigRecord` across sessions."""
    
    def get(self, plugin_name: str) -> Optional[PluginConfigRecord]:
        """Fetch the record for a plugin, or None if no record exists yet."""
        ...
    
    def set(self, plugin_name: str, record: PluginConfigRecord) -> None:
        """Persist a record. Overwrites any prior record for the same plugin.
        
        Implementations stamp `record.updated_at` to the current time during
        the write so callers don't have to manage timestamps.
        """
        ...
    
    def delete(self, plugin_name: str) -> bool:
        """Remove the record for a plugin. Returns True if a record was deleted."""
        ...
    
    def list_all(self) -> Dict[str, PluginConfigRecord]:
        """Return every stored record, keyed by plugin name."""
        ...

# %% ../../nbs/core/config_store.ipynb #local-impl
_SCHEMA = """
CREATE TABLE IF NOT EXISTS plugin_configs (
    plugin_name TEXT PRIMARY KEY,
    config_json TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    updated_at REAL NOT NULL
)
"""


def _default_db_path() -> Path:
    """Default SQLite location: `~/.cjm/plugin_configs.db`."""
    return Path.home() / ".cjm" / "plugin_configs.db"


class LocalPluginConfigStore:
    """SQLite-backed default implementation of `PluginConfigStore`.
    
    The DB is created lazily on first write. Reads against a non-existent DB
    return empty results rather than raising, so hosts can call `.get()` on
    a fresh install without preparing the file first.
    """
    
    def __init__(self, db_path: Optional[Path] = None):
        """Initialize the store. `db_path=None` uses `~/.cjm/plugin_configs.db`."""
        self.db_path = Path(db_path) if db_path is not None else _default_db_path()
    
    @contextmanager
    def _conn(self) -> Iterator[sqlite3.Connection]:
        """Open a connection, creating parent dirs + schema on demand."""
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(self.db_path)
        try:
            conn.execute(_SCHEMA)
            conn.commit()
            yield conn
        finally:
            conn.close()
    
    def get(
        self,
        plugin_name: str  # Plugin to look up
    ) -> Optional[PluginConfigRecord]:  # Persisted record or None if absent
        """Fetch the record for a plugin."""
        if not self.db_path.exists():
            return None
        with self._conn() as conn:
            row = conn.execute(
                "SELECT config_json, enabled, updated_at FROM plugin_configs WHERE plugin_name = ?",
                (plugin_name,),
            ).fetchone()
        if row is None:
            return None
        config_json, enabled, updated_at = row
        try:
            config = json.loads(config_json) if config_json else {}
        except json.JSONDecodeError as e:
            _logger.warning(
                "Corrupted config row for plugin %s: %s. Returning empty config.",
                plugin_name, e,
            )
            config = {}
        return PluginConfigRecord(
            config=config,
            enabled=bool(enabled),
            updated_at=float(updated_at),
        )
    
    def set(
        self,
        plugin_name: str,  # Plugin to write
        record: PluginConfigRecord  # New record (updated_at overwritten with current time)
    ) -> None:
        """Persist a record. Stamps `updated_at` to the current time."""
        record.updated_at = time.time()
        with self._conn() as conn:
            conn.execute(
                "INSERT OR REPLACE INTO plugin_configs "
                "(plugin_name, config_json, enabled, updated_at) VALUES (?, ?, ?, ?)",
                (
                    plugin_name,
                    json.dumps(record.config),
                    1 if record.enabled else 0,
                    record.updated_at,
                ),
            )
            conn.commit()
    
    def delete(
        self,
        plugin_name: str  # Plugin to remove
    ) -> bool:  # True if a row was deleted
        """Remove the record for a plugin."""
        if not self.db_path.exists():
            return False
        with self._conn() as conn:
            cur = conn.execute(
                "DELETE FROM plugin_configs WHERE plugin_name = ?", (plugin_name,),
            )
            conn.commit()
            return cur.rowcount > 0
    
    def list_all(self) -> Dict[str, PluginConfigRecord]:  # plugin_name -> record
        """Return all stored records keyed by plugin name."""
        if not self.db_path.exists():
            return {}
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT plugin_name, config_json, enabled, updated_at FROM plugin_configs",
            ).fetchall()
        out: Dict[str, PluginConfigRecord] = {}
        for name, config_json, enabled, updated_at in rows:
            try:
                config = json.loads(config_json) if config_json else {}
            except json.JSONDecodeError:
                config = {}
            out[name] = PluginConfigRecord(
                config=config,
                enabled=bool(enabled),
                updated_at=float(updated_at),
            )
        return out
