"""Abstract base class defining the generic plugin interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/interface.ipynb.

# %% auto #0
__all__ = ['FileBackedDTO', 'PluginInterface', 'plugin_action', 'collect_plugin_actions']

# %% ../../nbs/core/interface.ipynb #f96db51b
from abc import ABC, abstractmethod
from typing import Any, Callable, Dict, Generator, Optional, Protocol, Set, runtime_checkable

# %% ../../nbs/core/interface.ipynb #so9ttuo6zo
@runtime_checkable
class FileBackedDTO(Protocol):
    """Protocol for Data Transfer Objects that serialize to disk for zero-copy transfer."""
    
    def to_temp_file(self) -> str: # Absolute path to the temporary file
        """Save the data to a temporary file and return the absolute path."""
        ...

# %% ../../nbs/core/interface.ipynb #287e8911
class PluginInterface(ABC):
    """Abstract base class for all plugins (both local workers and remote proxies)."""

    @property
    @abstractmethod
    def name(self) -> str: # Unique identifier for this plugin
        """Unique plugin identifier."""
        ...

    @property
    @abstractmethod
    def version(self) -> str: # Semantic version string (e.g., "1.0.0")
        """Plugin version."""
        ...

    @abstractmethod
    def initialize(
        self,
        config: Optional[Dict[str, Any]] = None # Configuration dictionary
    ) -> None:
        """Initialize or re-configure the plugin."""
        ...

    @abstractmethod
    def execute(
        self,
        *args,
        **kwargs
    ) -> Any: # Plugin-specific output
        """Execute the plugin's main functionality."""
        ...

    def execute_stream(
        self,
        *args,
        **kwargs
    ) -> Generator[Any, None, None]: # Yields partial results
        """Stream execution results chunk by chunk."""
        # Default: yield single result from execute()
        yield self.execute(*args, **kwargs)

    @abstractmethod
    def get_config_schema(self) -> Dict[str, Any]: # JSON Schema for configuration
        """Return JSON Schema describing the plugin's configuration options."""
        ...

    @abstractmethod
    def get_current_config(self) -> Dict[str, Any]: # Current configuration values
        """Return the current configuration state as a dictionary."""
        ...

    @abstractmethod
    def cleanup(self) -> None:
        """Clean up resources when plugin is unloaded."""
        ...

    def cancel(self) -> None:
        """Cancel the current execution. Override for cooperative cancellation support."""
        pass  # Default: no-op (plugins opt-in to cancellation)

    def report_progress(
        self,
        progress: float, # 0.0 to 1.0, or -1.0 for indeterminate
        message: str = "" # Descriptive status message
    ) -> None:
        """Report execution progress. Call during execute() to update status."""
        # Default: store in instance variables for worker to poll
        self._progress = progress
        self._status_message = message

# %% ../../nbs/core/interface.ipynb #540be780
def plugin_action(
    action_name: str  # Public action name the decorated method handles
) -> Callable[[Callable], Callable]:  # Decorator
    """Marker decorator tagging a plugin method as the handler for `action_name`.
    
    Sets `func._plugin_action = action_name`. Plugin authors with dispatcher-style
    `execute(action, **kwargs)` use `collect_plugin_actions(cls)` to derive their
    `supported_actions` set from these markers rather than maintaining a separate
    list. The decorator does not change call semantics — the wrapped function is
    returned unchanged.
    """
    def decorator(func: Callable) -> Callable:
        func._plugin_action = action_name
        return func
    return decorator


def collect_plugin_actions(
    cls: type  # Class (or subclass) to scan for @plugin_action-tagged methods
) -> Set[str]:  # Set of action names handled by `cls` (including inherited)
    """Collect action names from `@plugin_action`-decorated methods on `cls`.
    
    Walks the class's MRO so subclasses inherit action handlers from base
    classes automatically. The returned set is suitable for
    `supported_actions: ClassVar[Set[str]] = collect_plugin_actions(MyPlugin)`
    once the plugin class body has been defined.
    """
    actions: Set[str] = set()
    for ancestor in cls.__mro__:
        for attr in vars(ancestor).values():
            tag = getattr(attr, "_plugin_action", None)
            if isinstance(tag, str):
                actions.add(tag)
    return actions
