"""Abstract base class defining the generic plugin interface

Docs: https://cj-mills.github.io/cjm-plugin-systemcore/interface.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/interface.ipynb.

# %% auto #0
__all__ = ['RELOAD_TRIGGER', 'FileBackedDTO', 'PluginInterface', 'plugin_action', 'collect_plugin_actions']

# %% ../../nbs/core/interface.ipynb #f96db51b
import dataclasses
import logging
from abc import ABC, abstractmethod
from contextlib import contextmanager
from typing import Any, Callable, Dict, Generator, List, Optional, Protocol, Set, runtime_checkable

from .errors import PluginCancelledError

# CR-4: metadata key for declarative reload triggers on config dataclass fields.
# Plugin authors annotate fields whose changes require resource release:
#
#     @dataclass
#     class WhisperConfig:
#         model: str = field(default="base", metadata={RELOAD_TRIGGER: "model"})
#         temperature: float = field(default=0.0)  # no reload needed on change
#
# Plugins then implement `_release_<trigger>()` methods (e.g. `_release_model`)
# and the substrate-provided `reconfigure_with_triggers` walks the diff between
# old and new configs, firing each affected trigger's release method.
RELOAD_TRIGGER = "reload_trigger"

_logger = logging.getLogger(__name__)

# %% ../../nbs/core/interface.ipynb #so9ttuo6zo
@runtime_checkable
class FileBackedDTO(Protocol):
    """Protocol for Data Transfer Objects that serialize to disk for zero-copy transfer."""
    
    def to_temp_file(self) -> str: # Absolute path to the temporary file
        """Save the data to a temporary file and return the absolute path."""
        ...

# %% ../../nbs/core/interface.ipynb #287e8911
class PluginInterface(ABC):
    """Abstract base class for all plugins (both local workers and remote proxies).
    
    CR-4 extended this surface with: prefetch hook (SG-19), made cleanup optional
    (SG-43), reconfigure split + RELOAD_TRIGGER declarative-helper (lifecycle
    hook split), and cooperative-cancellation primitives (SG-16 — flag + callback
    + context manager).
    
    Abstract methods: `name`, `version`, `initialize`, `execute`, `get_config_schema`,
    `get_current_config`. Concrete defaults (overridable): `execute_stream`,
    `cleanup`, `prefetch`, `reconfigure`, `cancel`, `check_cancel`,
    `register_cancel_callback`, `cancel_signal_to`, `report_progress`,
    `fields_that_changed`, `reconfigure_with_triggers`, `on_disable`, `on_enable`.
    """

    # CR-4: cooperative-cancellation flag. Class-level default so subclasses
    # don't have to remember to initialize it in __init__; setting on an
    # instance creates an instance attribute that shadows the class default.
    # Reset by the substrate's worker /execute wrapper before each call so
    # stale state from a previous cancellation doesn't leak forward.
    _cancel_requested: bool = False

    @property
    @abstractmethod
    def name(self) -> str: # Unique identifier for this plugin
        """Unique plugin identifier."""
        ...

    @property
    @abstractmethod
    def version(self) -> str: # Semantic version string (e.g., "1.0.0")
        """Plugin version."""
        ...

    @abstractmethod
    def initialize(
        self,
        config: Optional[Dict[str, Any]] = None # Configuration dictionary
    ) -> None:
        """Initialize or re-configure the plugin.
        
        CR-4: this is "first-time setup" — called once after construction with
        the initial config. Substrate uses `reconfigure(old, new)` for delta
        updates afterwards. Plugins predating CR-4 see no behavior change since
        the default `reconfigure()` body delegates to `reconfigure_with_triggers`
        which is a no-op unless the plugin opts in via RELOAD_TRIGGER metadata.
        """
        ...

    @abstractmethod
    def execute(
        self,
        *args,
        **kwargs
    ) -> Any: # Plugin-specific output
        """Execute the plugin's main functionality."""
        ...

    def execute_stream(
        self,
        *args,
        **kwargs
    ) -> Generator[Any, None, None]: # Yields partial results
        """Stream execution results chunk by chunk."""
        # Default: yield single result from execute()
        yield self.execute(*args, **kwargs)

    @abstractmethod
    def get_config_schema(self) -> Dict[str, Any]: # JSON Schema for configuration
        """Return JSON Schema describing the plugin's configuration options."""
        ...

    @abstractmethod
    def get_current_config(self) -> Dict[str, Any]: # Current configuration values
        """Return the current configuration state as a dictionary."""
        ...

    def cleanup(self) -> None:
        """Clean up resources when plugin is unloaded.
        
        CR-4: made optional (SG-43 closure). Was `@abstractmethod` before; every
        audited plugin overrode it with a near-no-op, so the default is now a
        no-op and plugin authors override only when they have non-trivial
        teardown (file handles, GPU memory, database connections). The
        substrate's worker /cleanup endpoint calls this regardless.
        """
        pass

    def prefetch(self) -> None:
        """Acquire heavy resources eagerly without invoking execute().
        
        CR-4 (SG-19): default no-op. Plugin authors override when downstream
        callers benefit from eager acquisition — typically transcription /
        inference plugins that lazy-download models on first execute. The
        substrate's prefetch_plugin(name) API + worker /prefetch endpoint
        invoke this. Should be idempotent (safe to call multiple times) since
        the substrate may pre-warm at load time AND on operator request.
        """
        pass

    def reconfigure(
        self,
        old_config: Optional[Dict[str, Any]],  # Previous configuration values
        new_config: Optional[Dict[str, Any]],  # New configuration values to apply
    ) -> None:
        """Apply a configuration change without re-running full initialize().
        
        CR-4: default delegates to `reconfigure_with_triggers`, which walks the
        plugin's `config_class` dataclass for RELOAD_TRIGGER metadata and fires
        the corresponding `_release_<trigger>` methods for fields whose values
        changed. Plugins that don't use the declarative pattern can either
        override `reconfigure` directly OR rely on the substrate falling back
        to `initialize(new_config)` (which existing plugins already handle).
        
        Distinction from initialize(): initialize sets up persistent state once
        after construction; reconfigure applies delta updates and is the
        canonical entry point for hot-reload via the substrate's
        update_plugin_config path.
        """
        self.reconfigure_with_triggers(old_config or {}, new_config or {})

    def fields_that_changed(
        self,
        old: Dict[str, Any],  # Previous config snapshot
        new: Dict[str, Any],  # Proposed new config snapshot
    ) -> Set[str]:  # Field names whose values differ between old and new
        """Return the set of field names whose values differ between old and new.
        
        Includes fields present in only one dict (treated as a change to/from
        the implicit None). Equality is structural via `!=`; nested dicts /
        lists compare by value, not identity. Hashable-vs-unhashable values
        compare correctly because we never put them in a set themselves.
        """
        all_keys = set(old) | set(new)
        return {k for k in all_keys if old.get(k) != new.get(k)}

    def reconfigure_with_triggers(
        self,
        old_config: Dict[str, Any],  # Previous configuration values
        new_config: Dict[str, Any],  # New configuration values being applied
    ) -> None:
        """CR-4 helper: walk RELOAD_TRIGGER metadata + fire `_release_<trigger>` methods.
        
        Resolution sequence:
        
          1. Find the plugin's `config_class` attribute (a dataclass). Absent
             means the plugin hasn't opted into the declarative pattern; the
             helper returns silently.
          2. Compute the diff between `old_config` and `new_config` via
             `fields_that_changed`.
          3. For each changed field, read its `RELOAD_TRIGGER` metadata key
             (if any) and accumulate the trigger names into a set (de-duping
             when multiple fields share a trigger).
          4. For each trigger, call `self._release_<trigger>()` if it exists
             on the instance.
        
        Plugin authors opt in by:
        
          - Setting `config_class = MyConfigDataclass` as a class attribute.
          - Annotating field metadata with `{RELOAD_TRIGGER: "model"}` etc.
          - Implementing matching `_release_model(self)` instance methods.
        
        Plugins WITHOUT config_class or RELOAD_TRIGGER metadata land here as a
        no-op — safe default for the SG-T3tr migration window where the
        cascade hasn't yet adopted the declarative pattern everywhere.
        """
        config_class = getattr(type(self), "config_class", None)
        if config_class is None or not dataclasses.is_dataclass(config_class):
            return
        changed = self.fields_that_changed(old_config, new_config)
        if not changed:
            return
        triggers_to_fire: Set[str] = set()
        for f in dataclasses.fields(config_class):
            if f.name not in changed:
                continue
            trigger = f.metadata.get(RELOAD_TRIGGER) if hasattr(f, "metadata") else None
            if trigger:
                triggers_to_fire.add(trigger)
        for trigger in triggers_to_fire:
            release_method = getattr(self, f"_release_{trigger}", None)
            if callable(release_method):
                try:
                    release_method()
                except Exception as e:
                    # A misbehaving _release method must NOT prevent the rest
                    # from firing — heavy-resource teardown is best-effort.
                    _logger.warning(
                        "_release_%s() raised on %r; continuing with remaining triggers: %s",
                        trigger, getattr(self, "name", type(self).__name__), e,
                    )

    def cancel(self) -> None:
        """Request cooperative cancellation of the current execute() call.
        
        CR-4: default sets the substrate-tracked `_cancel_requested` flag and
        fires any callbacks registered via `register_cancel_callback`.
        
        Plugin authors who need extra teardown logic (signaling a subprocess,
        closing a network connection) override `cancel()` and SHOULD call
        `super().cancel()` to preserve the flag-setting + callback-fire
        behavior. The plugin's `execute()` polls via `check_cancel()` at safe
        interruption points and unwinds when it raises `PluginCancelledError`.
        """
        self._cancel_requested = True
        for cb in list(getattr(self, "_cancel_callbacks", ())):
            try:
                cb()
            except Exception as e:
                # Cancellation callbacks are best-effort; a misbehaving one
                # must not stop subsequent callbacks from firing.
                _logger.warning(
                    "cancel callback raised on %r: %s",
                    getattr(self, "name", type(self).__name__), e,
                )

    def check_cancel(self) -> None:
        """Raise `PluginCancelledError` if cancellation has been requested.
        
        CR-4 (SG-16 polling primitive): plugin authors call this at safe
        interruption points inside `execute()`. The substrate sets the flag via
        `cancel()` (typically driven by an operator's "Cancel" button); the
        next `check_cancel` call surfaces the cancellation as a typed exception
        that unwinds execute() cleanly.
        
        The substrate's worker /execute wrapper resets the flag before each
        call so cancellation doesn't leak from one job into the next.
        """
        if self._cancel_requested:
            raise PluginCancelledError(self.name)

    def register_cancel_callback(
        self,
        callback: Callable[[], None],  # Called when cancel() fires
    ) -> None:
        """Register a callback that fires when cancel() is called.
        
        CR-4 (SG-16 callback primitive): for plugins that can't easily insert
        polling at strategic points (e.g., a plugin wrapping a blocking C
        extension). Callbacks should be non-blocking and idempotent. Multiple
        callbacks can be registered; all fire in registration order when
        cancel() is invoked. A misbehaving callback that raises is logged
        and skipped — the remaining callbacks still fire.
        """
        if not hasattr(self, "_cancel_callbacks"):
            self._cancel_callbacks: List[Callable[[], None]] = []
        self._cancel_callbacks.append(callback)

    @contextmanager
    def cancel_signal_to(
        self,
        callback: Callable[[], None],  # Cancellation callback scoped to the with-block
    ) -> Generator[None, None, None]:
        """Context manager registering `callback` for the duration of the with-block.
        
        Useful for binding cancellation to a finite-scope resource (a subprocess,
        a network request, a temporary file handle) without needing to
        deregister manually. Pairs with `register_cancel_callback` for cases
        where lifetime is tied to a `try:`/`finally:` block.
        
        Example:
        
            def execute(self, *args, **kwargs):
                proc = subprocess.Popen(...)
                with self.cancel_signal_to(lambda: proc.terminate()):
                    return proc.wait()
        """
        self.register_cancel_callback(callback)
        try:
            yield
        finally:
            if hasattr(self, "_cancel_callbacks"):
                try:
                    self._cancel_callbacks.remove(callback)
                except ValueError:
                    pass  # Already removed (e.g. by an aliased call); silent OK.

    def on_disable(self) -> None:
        """CR-2: signal that the substrate has marked this plugin as disabled.
        
        Worker stays alive; plugin can release heavy resources here (e.g., free
        GPU memory, close model files). The substrate fires this hook AFTER any
        in-flight job for this plugin finishes — see PluginManager.disable_plugin
        deferred-hook semantics. Default: no-op; plugins opt in by overriding.
        """
        pass

    def on_enable(self) -> None:
        """CR-2: signal that the substrate has marked this plugin as re-enabled.
        
        Plugin can eagerly re-acquire heavy resources here, or rely on lazy
        re-acquisition via the next execute() call (substrate doesn't prefer
        one strategy over the other). Default: no-op; plugins opt in by overriding.
        """
        pass

    def report_progress(
        self,
        progress: float, # 0.0 to 1.0, or -1.0 for indeterminate
        message: str = "" # Descriptive status message
    ) -> None:
        """Report execution progress. Call during execute() to update status."""
        # Default: store in instance variables for worker to poll
        self._progress = progress
        self._status_message = message

# %% ../../nbs/core/interface.ipynb #540be780
def plugin_action(
    action_name: str  # Public action name the decorated method handles
) -> Callable[[Callable], Callable]:  # Decorator
    """Marker decorator tagging a plugin method as the handler for `action_name`.
    
    Sets `func._plugin_action = action_name`. Plugin authors with dispatcher-style
    `execute(action, **kwargs)` use `collect_plugin_actions(cls)` to derive their
    `supported_actions` set from these markers rather than maintaining a separate
    list. The decorator does not change call semantics — the wrapped function is
    returned unchanged.
    """
    def decorator(func: Callable) -> Callable:
        func._plugin_action = action_name
        return func
    return decorator


def collect_plugin_actions(
    cls: type  # Class (or subclass) to scan for @plugin_action-tagged methods
) -> Set[str]:  # Set of action names handled by `cls` (including inherited)
    """Collect action names from `@plugin_action`-decorated methods on `cls`.
    
    Walks the class's MRO so subclasses inherit action handlers from base
    classes automatically. The returned set is suitable for
    `supported_actions: ClassVar[Set[str]] = collect_plugin_actions(MyPlugin)`
    once the plugin class body has been defined.
    """
    actions: Set[str] = set()
    for ancestor in cls.__mro__:
        for attr in vars(ancestor).values():
            tag = getattr(attr, "_plugin_action", None)
            if isinstance(tag, str):
                actions.add(tag)
    return actions

# %% ../../nbs/core/interface.ipynb #9342f856-f07e-4e18-b016-4f089a50c4c4
class _CR4MinimalPlugin(PluginInterface):
    """Concrete plugin satisfying abstracts; relies on CR-4 default cleanup()."""
    @property
    def name(self) -> str: return "cr4-minimal"
    @property
    def version(self) -> str: return "0.0.0"
    def initialize(self, config=None): self._cfg = dict(config or {})
    def execute(self, *args, **kwargs): return None
    def get_config_schema(self) -> Dict[str, Any]: return {}
    def get_current_config(self) -> Dict[str, Any]: return dict(getattr(self, "_cfg", {}))
