"""Plugin discovery, loading, and lifecycle management system"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/manager.ipynb.

# %% auto #0
__all__ = ['PluginManager', 'get_plugin_config', 'get_plugin_config_schema', 'get_all_plugin_configs', 'update_plugin_config',
           'reload_plugin', 'get_plugin_stats', 'execute_plugin_stream', 'PluginBinding', 'bind']

# %% ../../nbs/core/manager.ipynb #31a5a9f1
import json
from pathlib import Path
import time
from typing import Any, Dict, List, Optional, Type

from .config import get_config
from .interface import PluginInterface
from .metadata import PluginMeta
from .proxy import RemotePluginProxy
from .scheduling import ResourceScheduler, PermissiveScheduler
from ..utils.validation import PluginConfigError

# SG-39: library modules use `logging.getLogger(__name__)` and let the host
# (CLI entry point, FastHTML app, worker subprocess) own `basicConfig`.
# Previously each module called `logging.basicConfig(force=True, format=...)`
# at import time; the last-imported module's format silently overrode the
# others.
import logging

# %% ../../nbs/core/manager.ipynb #ad3d4194
class PluginManager:
    """Manages plugin discovery, loading, and lifecycle via process isolation."""

    def __init__(
        self,
        plugin_interface:Type[PluginInterface]=PluginInterface, # Base interface for type checking
        search_paths:Optional[List[Path]]=None, # Custom manifest search paths
        scheduler:Optional[ResourceScheduler]=None # Resource allocation policy
    ):
        """Initialize the plugin manager."""
        self.plugin_interface = plugin_interface
        
        # Use config-based search paths if not explicitly provided
        if search_paths is None:
            cfg = get_config()
            self.search_paths = [
                Path.cwd() / ".cjm" / "manifests",  # Local (high priority)
                cfg.manifests_dir                    # Config-based (replaces ~/.cjm/manifests)
            ]
        else:
            self.search_paths = search_paths
        
        self.scheduler = scheduler or PermissiveScheduler()
        self.system_monitor: Optional[PluginInterface] = None
        self.discovered: List[PluginMeta] = []
        self.plugins: Dict[str, PluginMeta] = {}
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")

    def register_system_monitor(
        self,
        plugin_name:str # Name of the system monitor plugin
    ) -> None:
        """Bind a loaded plugin to act as the hardware system monitor."""
        self.system_monitor = self.get_plugin(plugin_name)
        if self.system_monitor:
            self.logger.info(f"Registered system monitor: {plugin_name}")
        else:
            self.logger.warning(f"System monitor plugin not found: {plugin_name}")

    def _get_global_stats(self) -> Dict[str, Any]: # Current system telemetry
        """Fetch real-time stats from the system monitor plugin (sync)."""
        if self.system_monitor:
            try:
                return self.system_monitor.execute("get_system_status")
            except Exception as e:
                self.logger.warning(f"Failed to fetch system stats: {e}")
        return {}

    async def _get_global_stats_async(self) -> Dict[str, Any]: # Current system telemetry
        """Fetch real-time stats from the system monitor plugin (async)."""
        if self.system_monitor:
            try:
                return await self.system_monitor.execute_async("get_system_status")
            except Exception as e:
                self.logger.warning(f"Failed to fetch system stats: {e}")
        return {}

    def _check_interface_fqn(
        self,
        iface_fqn:str, # Interface FQN string from the manifest
        plugin_name:str # For error messages
    ) -> bool: # True if FQN passes the format check
        """SG-7: sanity-check the interface FQN format at discovery time.
        
        Substrate cannot actually import every interface library (the host
        env doesn't carry them all), so this is a format-only check. The
        authoritative import check happens at install time in
        _generate_manifest's introspection script. This guard catches
        manifests generated by older substrate versions before the
        introspection check shipped, plus obviously malformed values.
        """
        if not iface_fqn:
            self.logger.warning(
                f"Plugin {plugin_name!r}: manifest has empty `interface` field. "
                f"Run `cjm-ctl regenerate-manifest {plugin_name}` to refresh."
            )
            return False
        if "." not in iface_fqn:
            self.logger.warning(
                f"Plugin {plugin_name!r}: malformed interface FQN {iface_fqn!r} "
                f"(expected dotted path like 'module.subpackage.ClassName'). "
                f"Run `cjm-ctl regenerate-manifest {plugin_name}` to refresh."
            )
            return False
        return True

    def discover_manifests(self) -> List[PluginMeta]: # List of discovered plugin metadata
        """Discover plugins via JSON manifests in search paths."""
        self.discovered = []
        seen_plugins = set()

        for base_path in self.search_paths:
            if not base_path.exists():
                continue
            
            for manifest_file in base_path.glob("*.json"):
                try:
                    with open(manifest_file) as f:
                        manifest = json.load(f)
                    
                    name = manifest.get('name')
                    if not name or name in seen_plugins:
                        continue  # Skip duplicates (local shadows global)
                    
                    # Create metadata with manifest attached.
                    # SG-35: `author` + `package_name` removed; `description`
                    # kept and validated by SG-6.
                    meta = PluginMeta(
                        name=name,
                        version=manifest.get('version', '0.0.0'),
                        description=manifest.get('description', ''),
                        category=manifest.get('category', ''),
                        interface=manifest.get('interface', ''),
                        config_schema=manifest.get('config_schema')
                    )
                    meta.manifest = manifest
                    
                    # SG-7: format-check the interface FQN; warn but still
                    # discover the manifest so older plugins remain usable.
                    self._check_interface_fqn(meta.interface, name)
                    
                    self.discovered.append(meta)
                    seen_plugins.add(name)
                    self.logger.info(f"Discovered manifest: {name} from {manifest_file}")

                except Exception as e:
                    self.logger.error(f"Error loading manifest {manifest_file}: {e}")

        return self.discovered

    def get_discovered_by_category(
        self,
        category:str # Category to filter by (e.g., "transcription")
    ) -> List[PluginMeta]: # List of matching discovered plugins
        """Get discovered plugins filtered by category."""
        return [meta for meta in self.discovered if meta.category == category]

    def get_plugins_by_category(
        self,
        category:str # Category to filter by (e.g., "transcription")
    ) -> List[PluginMeta]: # List of matching loaded plugins
        """Get loaded plugins filtered by category."""
        return [meta for meta in self.plugins.values() if meta.category == category]

    def get_discovered_categories(self) -> List[str]: # List of unique categories
        """Get all unique categories among discovered plugins."""
        return list(set(meta.category for meta in self.discovered if meta.category))

    def get_loaded_categories(self) -> List[str]: # List of unique categories
        """Get all unique categories among loaded plugins."""
        return list(set(meta.category for meta in self.plugins.values() if meta.category))

    def get_plugin_meta(
        self,
        plugin_name:str # Name of the plugin
    ) -> Optional[PluginMeta]: # Plugin metadata or None
        """Get metadata for a loaded plugin by name."""
        return self.plugins.get(plugin_name)

    def get_discovered_meta(
        self,
        plugin_name:str # Name of the plugin
    ) -> Optional[PluginMeta]: # Plugin metadata or None
        """Get metadata for a discovered (not necessarily loaded) plugin by name."""
        for meta in self.discovered:
            if meta.name == plugin_name:
                return meta
        return None

    def _extract_defaults_from_schema(
        self,
        config_schema:Optional[Dict[str, Any]] # JSON Schema with properties
    ) -> Dict[str, Any]: # Default values extracted from schema
        """Extract default values from a JSON Schema's properties."""
        if not config_schema:
            return {}

        properties = config_schema.get("properties", {})
        defaults = {}

        for field_name, field_schema in properties.items():
            if "default" in field_schema:
                defaults[field_name] = field_schema["default"]

        return defaults

    def _validate_config_against_schema(
        self,
        config:Optional[Dict[str, Any]], # Caller-provided config dict (or None)
        config_schema:Optional[Dict[str, Any]], # Plugin's JSON Schema from manifest
        plugin_name:str, # For error messages and warnings
        strict:bool=True # Reject unknown keys (default); set False to log+filter
    ) -> Dict[str, Any]: # Validated (possibly filtered) config dict
        """SG-5: validate a config dict against the manifest's `config_schema`
        before forwarding to the plugin's `initialize()`.
        
        Substrate-side gate that catches unknown keys at the host boundary
        rather than relying on the worker process to silently drop them. The
        manifest's `config_schema.properties` is the authority for what keys
        are accepted.
        """
        if config is None:
            return {}
        if not config_schema or "properties" not in config_schema:
            # No schema declared; substrate cannot validate. Pass through.
            return dict(config)
        
        valid_keys = set(config_schema["properties"].keys())
        unknown_keys = sorted(set(config) - valid_keys)
        
        if unknown_keys:
            if strict:
                # CR-5: pass via `fields_invalid=` (canonical PluginInputError kwarg);
                # `unknown_keys=` is the SG-8-era deprecated alias.
                raise PluginConfigError(
                    f"Unknown config keys for plugin {plugin_name!r}: {unknown_keys}. "
                    f"Accepted keys per manifest config_schema: {sorted(valid_keys)}. "
                    f"Pass strict=False to ignore unknown keys (forward-compat).",
                    fields_invalid=unknown_keys,
                    config_class_name=plugin_name,
                )
            else:
                self.logger.warning(
                    "%s: ignoring unknown config keys %s (lenient mode)",
                    plugin_name, unknown_keys,
                )
                return {k: v for k, v in config.items() if k in valid_keys}
        
        return dict(config)

    def _check_config_schema_drift(
        self,
        proxy:Any, # RemotePluginProxy with a live worker
        plugin_meta:PluginMeta, # Metadata to flag if drift is detected
        manifest_schema:Optional[Dict[str, Any]] # Schema stored in the manifest
    ) -> None:
        """SG-9: compare live worker `/config_schema` to the manifest's stored
        schema. On mismatch: log a warning + set `plugin_meta.config_schema_drift`
        + populate `plugin_meta.live_config_schema`. Substrate keeps using the
        manifest schema for defaults + validation; the drift signal surfaces
        stale manifests that need regeneration (CR-8 `cjm-ctl regenerate-manifest`).
        
        Standalone scope: direct dict comparison rather than CR-8's nested-format
        hash-based check; same intent, smaller landing.
        """
        try:
            live_schema = proxy.get_config_schema()
        except Exception as e:
            self.logger.debug(
                f"Skipping drift detection for {plugin_meta.name}: live schema fetch failed ({e})"
            )
            return
        
        # Compare. dict equality is deep and order-insensitive in Python.
        if (manifest_schema or {}) != (live_schema or {}):
            plugin_meta.config_schema_drift = True
            plugin_meta.live_config_schema = live_schema
            self.logger.warning(
                f"Config schema drift for {plugin_meta.name}: manifest disagrees with live worker. "
                f"Run `cjm-ctl regenerate-manifest {plugin_meta.name}` to refresh the manifest."
            )

    def load_plugin(
        self,
        plugin_meta:PluginMeta, # Plugin metadata (with manifest attached)
        config:Optional[Dict[str, Any]]=None, # Initial configuration
        strict:bool=True # SG-5: reject unknown keys against manifest config_schema (default)
    ) -> bool: # True if successfully loaded
        """Load a plugin by spawning a Worker subprocess."""
        if not hasattr(plugin_meta, 'manifest'):
            self.logger.error(f"Plugin {plugin_meta.name} has no manifest data")
            return False

        try:
            self.logger.info(f"Launching worker for {plugin_meta.name}...")
            proxy = RemotePluginProxy(plugin_meta.manifest)

            config_schema = plugin_meta.manifest.get("config_schema")
            
            # SG-9: detect drift between manifest-declared schema and live worker.
            self._check_config_schema_drift(proxy, plugin_meta, config_schema)
            
            # If config is None or empty, extract defaults from the plugin's config schema
            if not config:
                config = self._extract_defaults_from_schema(config_schema)
                if config:
                    self.logger.info(f"Using default config for {plugin_meta.name}: {list(config.keys())}")
            else:
                # SG-5: validate caller-provided config against manifest schema
                # before forwarding to the worker.
                config = self._validate_config_against_schema(
                    config, config_schema, plugin_meta.name, strict=strict,
                )

            # Initialize with config (defaults or provided)
            if config:
                proxy.initialize(config)

            plugin_meta.instance = proxy
            self.plugins[plugin_meta.name] = plugin_meta
            self.logger.info(f"Loaded plugin: {plugin_meta.name}")
            return True

        except Exception as e:
            self.logger.error(f"Failed to load plugin {plugin_meta.name}: {e}")
            return False

    def load_all(
        self,
        configs:Optional[Dict[str, Dict[str, Any]]]=None # Plugin name -> config mapping
    ) -> Dict[str, bool]: # Plugin name -> success mapping
        """Discover and load all available plugins."""
        configs = configs or {}
        results = {}
        
        self.discover_manifests()
        for meta in self.discovered:
            config = configs.get(meta.name)
            results[meta.name] = self.load_plugin(meta, config)
        
        return results

    def unload_plugin(
        self,
        plugin_name:str # Name of the plugin to unload
    ) -> bool: # True if successfully unloaded
        """Unload a plugin and terminate its Worker process."""
        if plugin_name not in self.plugins:
            self.logger.error(f"Plugin {plugin_name} not found")
            return False

        try:
            plugin_meta = self.plugins[plugin_name]
            if plugin_meta.instance:
                plugin_meta.instance.cleanup()

            del self.plugins[plugin_name]
            self.logger.info(f"Unloaded plugin: {plugin_name}")
            return True

        except Exception as e:
            self.logger.error(f"Error unloading plugin {plugin_name}: {e}")
            return False

    def unload_all(self) -> None:
        """Unload all plugins and terminate all Worker processes."""
        for name in list(self.plugins.keys()):
            self.unload_plugin(name)

    def get_plugin(
        self,
        plugin_name:str # Name of the plugin
    ) -> Optional[PluginInterface]: # Plugin proxy instance or None
        """Get a loaded plugin instance by name."""
        if plugin_name in self.plugins:
            return self.plugins[plugin_name].instance
        return None

    def list_plugins(self) -> List[PluginMeta]: # List of loaded plugin metadata
        """List all loaded plugins."""
        return list(self.plugins.values())

    def _evict_for_resources(self, needed_meta:PluginMeta) -> bool:
        """Attempt to free resources by unloading/releasing idle plugins (LRU)."""
        self.logger.info(f"Attempting eviction to make room for {needed_meta.name}...")
        
        # 1. Identify Candidates: Running plugins that ARE NOT the one we need
        candidates = [
            meta for name, meta in self.plugins.items()
            if meta.instance 
            and name != needed_meta.name
            and meta.manifest.get('resources', {}).get('requires_gpu', False) # Only evict GPU users
        ]
        
        # 2. Sort by LRU (Oldest timestamp first)
        candidates.sort(key=lambda x: x.last_executed)
        
        # 3. Evict one by one until we have space
        for candidate in candidates:
            self.logger.info(f"Evicting idle plugin: {candidate.name} (Last used: {candidate.last_executed})")
            
            # Prefer Soft Release if available, else Hard Unload
            if hasattr(candidate.instance, 'release'):
                candidate.instance.release()
            else:
                self.reload_plugin(candidate.name)
            
            # Wait a moment for VRAM to clear
            time.sleep(0.5) 
            
            # Re-check scheduler immediately
            # If allocate returns True now, we stop evicting
            if self.scheduler.allocate(needed_meta, self._get_global_stats):
                return True
                
        return False

    def execute_plugin(
        self,
        plugin_name:str, # Name of the plugin
        *args,
        **kwargs
    ) -> Any: # Plugin result
        """Execute a plugin's main functionality (sync)."""
        plugin = self.get_plugin(plugin_name)
        if not plugin:
            raise ValueError(f"Plugin {plugin_name} not found or not loaded")

        if not self.plugins[plugin_name].enabled:
            raise ValueError(f"Plugin {plugin_name} is disabled")

        # Update Timestamp (Mark as active)
        plugin_meta = self.plugins[plugin_name]
        plugin_meta.last_executed = time.time()

        # Allocation Loop
        stats_provider = self._get_global_stats

        # Scheduling check (pass method reference for polling support)
        if not self.scheduler.allocate(plugin_meta, stats_provider):
            # Trigger Eviction if blocked
            self.logger.warning(f"Resources busy for {plugin_name}. Triggering eviction protocol.")
            
            if self._evict_for_resources(plugin_meta):
                self.logger.info("Eviction successful. Resources acquired.")
            else:
                # If eviction failed (or QueueScheduler timed out), raise error
                raise RuntimeError(f"ResourceScheduler blocked execution of {plugin_name} (Eviction failed)")

        self.scheduler.on_execution_start(plugin_name)
        try:
            return plugin.execute(*args, **kwargs)
        finally:
            self.scheduler.on_execution_finish(plugin_name)

    async def execute_plugin_async(
        self,
        plugin_name:str, # Name of the plugin
        *args,
        **kwargs
    ) -> Any: # Plugin result
        """Execute a plugin's main functionality (async)."""
        plugin = self.get_plugin(plugin_name)
        if not plugin:
            raise ValueError(f"Plugin {plugin_name} not found or not loaded")

        if not self.plugins[plugin_name].enabled:
            raise ValueError(f"Plugin {plugin_name} is disabled")

        # Update Timestamp (Mark as active)
        plugin_meta = self.plugins[plugin_name]
        plugin_meta.last_executed = time.time()

        # Allocation Loop
        stats_provider = self._get_global_stats

        # Async scheduling check (pass async method for non-blocking polling)
        if not await self.scheduler.allocate_async(self.plugins[plugin_name], self._get_global_stats_async):
            # Trigger Eviction if blocked
            self.logger.warning(f"Resources busy for {plugin_name}. Triggering eviction protocol.")
            
            if self._evict_for_resources(plugin_meta):
                self.logger.info("Eviction successful. Resources acquired.")
            else:
                # If eviction failed (or QueueScheduler timed out), raise error
                raise RuntimeError(f"ResourceScheduler blocked execution of {plugin_name} (Eviction failed)")

        self.scheduler.on_execution_start(plugin_name)
        try:
            return await plugin.execute_async(*args, **kwargs)
        finally:
            self.scheduler.on_execution_finish(plugin_name)

    def enable_plugin(
        self,
        plugin_name:str # Name of the plugin
    ) -> bool: # True if plugin was enabled
        """Enable a plugin."""
        if plugin_name in self.plugins:
            self.plugins[plugin_name].enabled = True
            return True
        return False

    def disable_plugin(
        self,
        plugin_name:str # Name of the plugin
    ) -> bool: # True if plugin was disabled
        """Disable a plugin without unloading it."""
        if plugin_name in self.plugins:
            self.plugins[plugin_name].enabled = False
            return True
        return False

    def get_plugin_logs(
        self,
        plugin_name:str, # Name of the plugin
        lines:int=50 # Number of lines to return
    ) -> str: # Log content
        """Read the last N lines of the plugin's log file."""
        cfg = get_config()
        log_path = cfg.logs_dir / f"{plugin_name}.log"
        
        if not log_path.exists():
            return "No logs found."
            
        try:
            # Efficient tail implementation
            from collections import deque
            with open(log_path, 'r') as f:
                tail = deque(f, maxlen=lines)
                return "".join(tail)
        except Exception as e:
            return f"Error reading logs: {e}"

# %% ../../nbs/core/manager.ipynb #a79dda0b
def get_plugin_config(
    self,
    plugin_name: str # Name of the plugin
) -> Optional[Dict[str, Any]]: # Current configuration or None
    """Get the current configuration of a plugin."""
    plugin = self.get_plugin(plugin_name)
    if plugin:
        return plugin.get_current_config()
    return None

def get_plugin_config_schema(
    self,
    plugin_name: str # Name of the plugin
) -> Optional[Dict[str, Any]]: # JSON Schema or None
    """Get the configuration JSON Schema for a plugin."""
    plugin = self.get_plugin(plugin_name)
    if plugin:
        return plugin.get_config_schema()
    return None

def get_all_plugin_configs(self) -> Dict[str, Dict[str, Any]]: # Plugin name -> config mapping
    """Get current configuration for all loaded plugins."""
    return {
        name: plugin.get_current_config()
        for name, meta in self.plugins.items()
        if meta.instance
        for plugin in [meta.instance]
    }

def update_plugin_config(
    self,
    plugin_name: str, # Name of the plugin
    config: Dict[str, Any], # New configuration values
    strict: bool = True # SG-5: reject unknown keys against manifest config_schema (default)
) -> bool: # True if successful
    """Update a plugin's configuration (hot-reload without restart)."""
    plugin = self.get_plugin(plugin_name)
    if not plugin:
        self.logger.error(f"Plugin {plugin_name} not found")
        return False

    try:
        # SG-5: validate caller-provided config against manifest schema
        # before forwarding to the worker. PluginConfigError propagates so
        # callers can distinguish substrate-side validation failures from
        # worker-side runtime errors.
        meta = self.plugins[plugin_name]
        config_schema = meta.manifest.get("config_schema") if hasattr(meta, "manifest") else None
        validated_config = self._validate_config_against_schema(
            config, config_schema, plugin_name, strict=strict,
        )
        plugin.initialize(validated_config)
        self.logger.info(f"Updated configuration for plugin: {plugin_name}")
        return True
    except PluginConfigError:
        # Let typed validation errors propagate to callers; substrate-side
        # rejection is a programmer/operator signal, not a "soft" failure.
        raise
    except Exception as e:
        self.logger.error(f"Error updating plugin {plugin_name} config: {e}")
        return False

def reload_plugin(
    self,
    plugin_name: str, # Name of the plugin
    config: Optional[Dict[str, Any]] = None # Optional new configuration
) -> bool: # True if successful
    """Reload a plugin by terminating and restarting its Worker."""
    if plugin_name not in self.plugins:
        self.logger.error(f"Plugin {plugin_name} not found")
        return False

    try:
        plugin_meta = self.plugins[plugin_name]
        
        # Get current config if not provided
        if config is None and plugin_meta.instance:
            config = plugin_meta.instance.get_current_config()
        
        # Unload and reload
        self.unload_plugin(plugin_name)
        return self.load_plugin(plugin_meta, config)

    except Exception as e:
        self.logger.error(f"Error reloading plugin {plugin_name}: {e}")
        return False

def get_plugin_stats(
    self,
    plugin_name: str # Name of the plugin
) -> Optional[Dict[str, Any]]: # Resource telemetry or None
    """Get resource usage stats for a plugin's Worker process."""
    plugin = self.get_plugin(plugin_name)
    if plugin and hasattr(plugin, 'get_stats'):
        return plugin.get_stats()
    return None

# Add methods to PluginManager
PluginManager.get_plugin_config = get_plugin_config
PluginManager.get_plugin_config_schema = get_plugin_config_schema
PluginManager.get_all_plugin_configs = get_all_plugin_configs
PluginManager.update_plugin_config = update_plugin_config
PluginManager.reload_plugin = reload_plugin
PluginManager.get_plugin_stats = get_plugin_stats

# %% ../../nbs/core/manager.ipynb #5ef5a64c
from typing import AsyncGenerator

async def execute_plugin_stream(
    self,
    plugin_name: str,  # Name of the plugin
    *args,
    **kwargs
) -> AsyncGenerator[Any, None]:  # Async generator yielding results
    """Execute a plugin with streaming response."""
    plugin = self.get_plugin(plugin_name)
    if not plugin:
        raise ValueError(f"Plugin {plugin_name} not found or not loaded")

    if not self.plugins[plugin_name].enabled:
        raise ValueError(f"Plugin {plugin_name} is disabled")

    # Async scheduling check (pass async method for non-blocking polling)
    if not await self.scheduler.allocate_async(self.plugins[plugin_name], self._get_global_stats_async):
        raise RuntimeError(f"ResourceScheduler blocked execution of {plugin_name}")

    self.scheduler.on_execution_start(plugin_name)
    try:
        async for chunk in plugin.execute_stream(*args, **kwargs):
            yield chunk
    finally:
        self.scheduler.on_execution_finish(plugin_name)

# Add to PluginManager
PluginManager.execute_plugin_stream = execute_plugin_stream

# %% ../../nbs/core/manager.ipynb #c8ebac45
from dataclasses import dataclass, field as _field


@dataclass
class PluginBinding:
    """Pre-bound view of a single plugin through a shared PluginManager.
    
    Eliminates the wrapper-class duplication audited across 8 consumer services
    (SG-17). Methods forward to the manager with `plugin_name` pre-supplied;
    `default_config` is the fallback used when `load()` is called without an
    explicit config (matches the manifest-default behavior in `load_plugin`).
    """
    manager: "PluginManager"  # The shared PluginManager
    plugin_name: str  # Name of the plugin this binding targets
    default_config: Dict[str, Any] = _field(default_factory=dict)  # Used when load() called without config
    
    # --- Observation ---
    
    @property
    def meta(self) -> Optional[PluginMeta]:
        """The PluginMeta if the plugin is loaded, else None."""
        return self.manager.get_plugin_meta(self.plugin_name)
    
    @property
    def is_loaded(self) -> bool:
        """True if the plugin is loaded in the bound manager."""
        return self.manager.get_plugin(self.plugin_name) is not None
    
    @property
    def is_enabled(self) -> bool:
        """True if the plugin is loaded AND not currently disabled."""
        m = self.meta
        return m is not None and m.enabled
    
    # --- Lifecycle ---
    
    def load(
        self,
        config: Optional[Dict[str, Any]] = None,  # Override default_config when provided
        strict: bool = True  # SG-5 strict validation
    ) -> bool:  # True if loaded successfully
        """Load via the bound manager. Uses `default_config` if no `config` provided."""
        meta = self.manager.get_discovered_meta(self.plugin_name)
        if meta is None:
            self.manager.logger.error(f"Plugin {self.plugin_name!r} not discovered")
            return False
        effective = config if config is not None else dict(self.default_config)
        return self.manager.load_plugin(meta, effective, strict=strict)
    
    def unload(self) -> bool:  # True if unloaded
        """Unload the bound plugin."""
        return self.manager.unload_plugin(self.plugin_name)
    
    def reload(
        self,
        config: Optional[Dict[str, Any]] = None  # Optional new config; current config used if None
    ) -> bool:
        """Reload the bound plugin (terminate + restart worker)."""
        return self.manager.reload_plugin(self.plugin_name, config)
    
    def enable(self) -> bool:
        """Enable the bound plugin."""
        return self.manager.enable_plugin(self.plugin_name)
    
    def disable(self) -> bool:
        """Disable the bound plugin (worker stays alive; jobs rejected)."""
        return self.manager.disable_plugin(self.plugin_name)
    
    # --- Execution ---
    
    def execute(self, *args, **kwargs) -> Any:
        """Execute via the bound manager (sync)."""
        return self.manager.execute_plugin(self.plugin_name, *args, **kwargs)
    
    async def execute_async(self, *args, **kwargs) -> Any:
        """Execute via the bound manager (async)."""
        return await self.manager.execute_plugin_async(self.plugin_name, *args, **kwargs)
    
    # --- Configuration ---
    
    def update_config(
        self,
        config: Dict[str, Any],  # New config values
        strict: bool = True  # SG-5 strict validation
    ) -> bool:
        """Hot-reload the bound plugin's configuration."""
        return self.manager.update_plugin_config(self.plugin_name, config, strict=strict)
    
    def get_config(self) -> Optional[Dict[str, Any]]:
        """Current configuration values (None if not loaded)."""
        return self.manager.get_plugin_config(self.plugin_name)
    
    def get_config_schema(self) -> Optional[Dict[str, Any]]:
        """JSON Schema describing this plugin's configuration."""
        return self.manager.get_plugin_config_schema(self.plugin_name)
    
    def get_stats(self) -> Optional[Dict[str, Any]]:
        """Resource telemetry for the bound plugin's worker process."""
        return self.manager.get_plugin_stats(self.plugin_name)


def bind(
    self,
    plugin_name: str,  # Name of the plugin to pre-bind
    default_config: Optional[Dict[str, Any]] = None  # Default config used by binding.load()
) -> PluginBinding:  # Bound view ready for instance-style use
    """Create a PluginBinding pre-bound to this manager + plugin_name."""
    return PluginBinding(
        manager=self,
        plugin_name=plugin_name,
        default_config=dict(default_config) if default_config else {},
    )


PluginManager.bind = bind

# %% ../../nbs/core/manager.ipynb #5c1b890e
# SG-15: curate __all__ to expose only the class symbols.
# The patched PluginManager methods (get_plugin_config, reload_plugin, etc.)
# remain accessible as PluginManager.method() — they're removed from the
# module's `from ... import *` surface because invoking them standalone
# fails (they expect `self`). nbdev's auto-`__all__` lists them as free
# names; this override runs after that assignment and wins by being last.
__all__ = ['PluginManager', 'PluginBinding']
