"""Data structures for plugin metadata"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/metadata.ipynb.

# %% auto #0
__all__ = ['PluginMeta']

# %% ../../nbs/core/metadata.ipynb #82130a8f
from dataclasses import dataclass, field
from typing import Any, Dict, Optional

# %% ../../nbs/core/metadata.ipynb #cf0ae1a9
@dataclass
class PluginMeta:
    """Metadata about a plugin."""
    name:str # Plugin's unique identifier
    version:str # Plugin's version string
    description:str="" # Brief description of the plugin's functionality
    # SG-35: `author` and `package_name` removed — author lives in pyproject.toml
    # + importlib.metadata; package_name is derivable from the import system.
    # `description` is retained and validated by SG-6's manifest checker.
    category:str="" # Plugin category (e.g., "transcription", "system_monitor")
    interface:str="" # Fully qualified interface class name
    config_schema:Optional[Dict[str, Any]]=None # JSON Schema for plugin configuration
    instance:Optional[Any]=None # Plugin instance (PluginInterface subclass)
    enabled:bool=True # Whether the plugin is enabled
    last_executed:float=0.0 # Unix timestamp
    # SG-9: drift detection — set by PluginManager.load_plugin when the live
    # worker's /config_schema disagrees with the manifest's stored config_schema.
    # `live_config_schema` holds the worker-reported shape so callers can pick
    # which to honor (substrate keeps using `config_schema` for defaults +
    # validation; tooling and the future plugin-config UI library can inspect
    # `live_config_schema` for the post-regenerate-manifest preview).
    config_schema_drift:bool=False
    live_config_schema:Optional[Dict[str, Any]]=None
