"""Data structures for plugin metadata"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/metadata.ipynb.

# %% auto 0
__all__ = ['PluginMeta']

# %% ../../nbs/core/metadata.ipynb 3
from dataclasses import dataclass, field
from typing import Optional, Any

# %% ../../nbs/core/metadata.ipynb 5
@dataclass
class PluginMeta:
    """Metadata about a plugin."""
    name:str # Plugin's unique identifier
    version:str # Plugin's version string
    description:str="" # Brief description of the plugin's functionality
    author:str="" # Plugin author's name or organization
    package_name:str="" # Python package name containing the plugin
    category:str="" # Plugin category (e.g., "transcription", "system_monitor")
    interface:str="" # Fully qualified interface class name
    instance:Optional[Any]=None # Plugin instance (PluginInterface subclass)
    enabled:bool=True # Whether the plugin is enabled
    last_executed:float=0.0 # Unix timestamp
