"""Data structures for plugin metadata"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/metadata.ipynb.

# %% auto #0
__all__ = ['PluginTaxonomy', 'ResourceRequirements', 'PluginMeta']

# %% ../../nbs/core/metadata.ipynb #82130a8f
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

# %% ../../nbs/core/metadata.ipynb #a67634c3
@dataclass
class PluginTaxonomy:
    """Derived classification of a plugin via its interface FQN.
    
    Populated at install time by `_generate_manifest`'s introspection script
    (running in the plugin's own conda env, where the interface library is
    installed). Substrate stores strings only — no host-side imports of
    interface libraries needed for taxonomy queries.
    
    - `domain`: the substrate area, derived from the interface library's
      naming convention `cjm-<domain>-plugin-system` (e.g., "transcription",
      "graph", "media", "text").
    - `role`: the interface class name segment of the FQN (e.g.,
      "TranscriptionPlugin", "GraphPlugin", "ForcedAlignmentPlugin"). Multiple
      plugins can share a role within a domain.
    - `interface_fqcn`: the full dotted path, kept verbatim for queries and
      reverse-lookup.
    """
    domain: str  # e.g., "transcription", "graph", "media"
    role: str  # e.g., "TranscriptionPlugin", "GraphPlugin"
    interface_fqcn: str  # Full dotted interface class path


@dataclass
class ResourceRequirements:
    """Binary hard-facts about what a plugin needs to run (Phase 5a).
    
    Quantitative resource amounts (min_vram_mb, etc.) deliberately omitted
    per CR-7's reactive resource management reframing — plugin authors can't
    reliably estimate model × dtype × quantization combinatorics, and Blender-
    style variable-render plugins can't estimate at all. The substrate uses
    these binary hard-facts purely for discovery filtering; actual resource
    contention is handled reactively by CR-7's eviction + retry flow.
    
    - `requires_gpu`: True if the plugin needs any GPU; the substrate gates
      execution on a system monitor reporting one is present.
    - `platforms`: e.g., ["linux-x64", "darwin-arm64"]. Empty list means no
      platform constraint declared (assume universal compatibility).
    - `accelerators`: e.g., ["cuda", "mps", "cpu"]. Informational; substrate
      doesn't auto-select but consumers can filter on the values.
    """
    requires_gpu: bool = False
    platforms: List[str] = field(default_factory=list)
    accelerators: List[str] = field(default_factory=list)

# %% ../../nbs/core/metadata.ipynb #cf0ae1a9
@dataclass
class PluginMeta:
    """Metadata about a plugin."""
    name:str # Plugin's unique identifier
    version:str # Plugin's version string
    description:str="" # Brief description of the plugin's functionality
    # SG-35: `author` and `package_name` removed — author lives in pyproject.toml
    # + importlib.metadata; package_name is derivable from the import system.
    # `description` is retained and validated by SG-6's manifest checker.
    category:str="" # Display label — derived from taxonomy.domain (CR-1) or read from legacy manifests
    interface:str="" # Fully qualified interface class name (kept verbatim for SG-7 format check)
    # CR-1: taxonomy block supersedes the legacy flat `category` string with a
    # derived domain/role/interface_fqcn triple. Populated at discovery from
    # the manifest's taxonomy block (which `_generate_manifest` emits at install
    # time). Optional during the SG-47 cascade window: legacy manifests without
    # the block read taxonomy=None and rely on the legacy `category` string.
    taxonomy:Optional["PluginTaxonomy"]=None
    # Phase 5a: binary hard-facts for discovery filtering (no quantitative amounts
    # per CR-7 reactive reframing). Optional during the cascade window for the
    # same reason as taxonomy.
    resources:Optional["ResourceRequirements"]=None
    config_schema:Optional[Dict[str, Any]]=None # JSON Schema for plugin configuration
    instance:Optional[Any]=None # Plugin instance (PluginInterface subclass)
    enabled:bool=True # Whether the plugin is enabled
    last_executed:float=0.0 # Unix timestamp
    # SG-9: drift detection — set by PluginManager.load_plugin when the live
    # worker's /config_schema disagrees with the manifest's stored config_schema.
    # `live_config_schema` holds the worker-reported shape so callers can pick
    # which to honor (substrate keeps using `config_schema` for defaults +
    # validation; tooling and the future plugin-config UI library can inspect
    # `live_config_schema` for the post-regenerate-manifest preview).
    config_schema_drift:bool=False
    live_config_schema:Optional[Dict[str, Any]]=None
