"""Bridge between Host application and isolated Worker processes"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/proxy.ipynb.

# %% auto #0
__all__ = ['RemotePluginProxy', 'execute_async', 'execute_stream_sync', 'execute_stream', 'get_stats', 'is_alive', 'cancel',
           'cancel_async', 'get_progress', 'get_progress_async', 'on_disable', 'on_enable', 'get_system_status',
           'get_system_status_async', 'list_processes', 'list_processes_async']

# %% ../../nbs/core/proxy.ipynb #exports
import json
import os
import socket
import subprocess
import time
from pathlib import Path
from typing import Any, AsyncGenerator, Dict, Generator, List, Optional, Tuple

import httpx

from .config import get_config
from .interface import FileBackedDTO, PluginInterface
from .platform import get_popen_isolation_kwargs, is_windows, terminate_process

# %% ../../nbs/core/proxy.ipynb #proxy-class
class RemotePluginProxy(PluginInterface):
    """Proxy that forwards plugin calls to an isolated Worker subprocess."""
    
    def __init__(
        self,
        manifest:Dict[str, Any] # Plugin manifest with python_path, module, class, etc.
    ):
        """Initialize proxy and start the worker process."""
        self.manifest = manifest
        self.process: Optional[subprocess.Popen] = None
        # SG-4: bind the listening socket in the parent and (on Unix) pass the
        # FD to the worker via subprocess inheritance, closing the
        # bind-then-close-then-reopen TOCTOU race that would otherwise let
        # another process steal the port between parent close and worker bind.
        self._listen_sock, self.port = self._bind_listen_socket()
        self.base_url = f"http://127.0.0.1:{self.port}"
        self._start_process()

    @property
    def name(self) -> str: # Plugin name from manifest
        """Plugin name."""
        return self.manifest.get('name', 'unknown')
    
    @property
    def version(self) -> str: # Plugin version from manifest
        """Plugin version."""
        return self.manifest.get('version', '0.0.0')

    def _bind_listen_socket(self) -> Tuple[socket.socket, int]:
        """Bind a listening socket on a kernel-chosen ephemeral port.
        The socket is kept open so its FD can be inherited by the worker
        subprocess (Unix). Returns (socket, port)."""
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.bind(('127.0.0.1', 0))
        sock.listen(128)
        return sock, sock.getsockname()[1]

    def _start_process(self) -> None:
        """Launch the worker subprocess."""
        python_path = self.manifest['python_path']

        # 1. Setup Log Directory using config
        cfg = get_config()
        log_dir = cfg.logs_dir
        log_dir.mkdir(parents=True, exist_ok=True)
        
        # 2. Open Log File (Append mode)
        # We keep the file handle open as long as the process runs
        self.log_path = log_dir / f"{self.name}.log"
        self.log_file = open(self.log_path, "a") # Close this in cleanup()
        
        # Write a header so we know a new session started
        self.log_file.write(f"\n--- Starting {self.name} at {time.ctime()} ---\n")
        self.log_file.flush()
        
        # SG-4: prefer FD inheritance over bind-then-close. `pass_fds` is
        # Unix-only; Windows falls back to the legacy port-handoff (TOCTOU
        # latent there until cross-platform CI matrix per SG-32).
        popen_kwargs: Dict[str, Any] = {}
        if is_windows():
            self._listen_sock.close()
            self._listen_sock = None
            port_args = ["--port", str(self.port)]
        else:
            fd = self._listen_sock.fileno()
            os.set_inheritable(fd, True)
            popen_kwargs["pass_fds"] = (fd,)
            port_args = ["--fd", str(fd)]

        cmd = [
            python_path,
            "-m", "cjm_plugin_system.core.worker",
            "--module", self.manifest['module'],
            "--class", self.manifest['class'],
            *port_args,
            "--ppid", str(os.getpid())  # Enable suicide pact
        ]
        
        # Merge environment variables from manifest
        env = dict(os.environ)
        env.update(self.manifest.get('env_vars', {}))
        
        # Inject CJM paths for plugin runtime
        env["CJM_DATA_DIR"] = str(cfg.plugin_data_dir)
        if cfg.models_dir:
            env["CJM_MODELS_DIR"] = str(cfg.models_dir)

        print(f"[{self.name}] Starting worker on port {self.port}...")
        # 3. Redirect Output to File
        # We merge stderr into stdout for a single timeline
        print(f"[{self.name}] Logs: {self.log_path}")
        
        # Get cross-platform process isolation kwargs
        isolation_kwargs = get_popen_isolation_kwargs()
        
        self.process = subprocess.Popen(
            cmd,
            stdout=self.log_file,
            stderr=subprocess.STDOUT, # Merge stderr into stdout
            env=env,
            **isolation_kwargs,
            **popen_kwargs,
        )
        # Parent releases its copy of the listening socket once the worker has
        # inherited the FD; the worker now owns it via uvicorn's --fd path.
        if self._listen_sock is not None:
            self._listen_sock.close()
            self._listen_sock = None
        self._wait_for_ready()

    def _wait_for_ready(
        self,
        timeout:float=30.0 # Max seconds to wait for worker startup
    ) -> None:
        """Wait for worker to become responsive."""
        start = time.time()
        while time.time() - start < timeout:
            try:
                with httpx.Client() as client:
                    client.get(f"{self.base_url}/health")
                print(f"[{self.name}] Worker ready.")
                return
            except httpx.ConnectError:
                time.sleep(0.5)
        
        # Timeout - get stderr for debugging
        _, stderr = self.process.communicate(timeout=1)
        raise TimeoutError(
            f"Plugin '{self.name}' failed to start within {timeout}s: "
            f"{stderr.decode() if stderr else 'Unknown error'}"
        )


    def initialize(
        self,
        config:Optional[Dict[str, Any]]=None # Configuration dictionary
    ) -> None:
        """Initialize or reconfigure the plugin."""
        with httpx.Client() as client:
            resp = client.post(f"{self.base_url}/initialize", json=config or {})
        if resp.status_code != 200:
            raise RuntimeError(f"Initialize failed: {resp.text}")
    
    def execute(
        self,
        *args,
        **kwargs
    ) -> Any: # Plugin result
        """Execute the plugin synchronously."""
        payload = self._prepare_payload(args, kwargs)
        # timeout=None for long-running AI tasks
        with httpx.Client(timeout=None) as client:
            resp = client.post(f"{self.base_url}/execute", json=payload)
        
        if resp.status_code != 200:
            raise RuntimeError(f"Execute failed: {resp.text}")
        return resp.json()
    
    def get_config_schema(self) -> Dict[str, Any]: # JSON Schema
        """Get the plugin's configuration schema."""
        with httpx.Client() as client:
            return client.get(f"{self.base_url}/config_schema").json()
    
    def get_current_config(self) -> Dict[str, Any]: # Current config values
        """Get the plugin's current configuration."""
        with httpx.Client() as client:
            return client.get(f"{self.base_url}/config").json()


    def cleanup(self) -> None:
        """Clean up plugin resources and terminate worker process."""
        # Send cleanup request to worker
        try:
            with httpx.Client(timeout=2) as client:
                client.post(f"{self.base_url}/cleanup")
        except Exception:
            pass  # Worker may already be gone
        
        # Terminate the subprocess using cross-platform utility
        terminate_process(self.process, timeout=2.0)
        self.process = None

        # Close file handle
        if hasattr(self, 'log_file') and self.log_file:
            self.log_file.close()

# %% ../../nbs/core/proxy.ipynb #serialization
def _maybe_serialize_input(
    self,
    obj: Any # Object to potentially serialize
) -> Any: # Serialized form (path string or original object)
    """Convert FileBackedDTO objects to file paths for zero-copy transfer."""
    # Zero-Copy: Ask object to save itself
    if isinstance(obj, FileBackedDTO):
        return obj.to_temp_file()
    # Paths: Convert to string
    if isinstance(obj, Path):
        return str(obj)
    # Default: Pass through for JSON serialization
    return obj

def _prepare_payload(
    self,
    args: tuple, # Positional arguments
    kwargs: dict # Keyword arguments
) -> Dict[str, Any]: # JSON-serializable payload
    """Prepare arguments for HTTP transmission."""
    safe_args = [self._maybe_serialize_input(a) for a in args]
    safe_kwargs = {k: self._maybe_serialize_input(v) for k, v in kwargs.items()}
    return {"args": safe_args, "kwargs": safe_kwargs}

RemotePluginProxy._maybe_serialize_input = _maybe_serialize_input
RemotePluginProxy._prepare_payload = _prepare_payload

# %% ../../nbs/core/proxy.ipynb #async-methods
async def execute_async(
    self,
    *args,
    **kwargs
) -> Any: # Plugin result
    """Execute the plugin asynchronously."""
    payload = self._prepare_payload(args, kwargs)
    async with httpx.AsyncClient(timeout=None) as client:
        resp = await client.post(f"{self.base_url}/execute", json=payload)
    
    if resp.status_code != 200:
        raise RuntimeError(f"Execute failed: {resp.text}")
    return resp.json()

def execute_stream_sync(self, *args, **kwargs) -> Generator[Any, None, None]:
    """Synchronous wrapper for streaming (blocking)."""
    # This is tricky without "httpx.stream" in sync mode.
    # For now, it's okay to leave it async-only if documented.
    pass

async def execute_stream(
    self,
    *args,
    **kwargs
) -> AsyncGenerator[Any, None]: # Yields parsed JSON chunks
    """Execute with streaming response (async generator)."""
    payload = self._prepare_payload(args, kwargs)
    async with httpx.AsyncClient(timeout=None) as client:
        async with client.stream("POST", f"{self.base_url}/execute_stream", json=payload) as resp:
            async for line in resp.aiter_lines():
                if line:
                    yield json.loads(line)

RemotePluginProxy.execute_async = execute_async
RemotePluginProxy.execute_stream_sync = execute_stream_sync
RemotePluginProxy.execute_stream = execute_stream

# %% ../../nbs/core/proxy.ipynb #lifecycle
def get_stats(self) -> Dict[str, Any]: # Process telemetry
    """Get worker process resource usage."""
    with httpx.Client() as client:
        return client.get(f"{self.base_url}/stats").json()

def is_alive(self) -> bool: # True if worker is responsive
    """Check if the worker process is still running and responsive."""
    if not self.process or self.process.poll() is not None:
        return False
    try:
        with httpx.Client(timeout=2) as client:
            resp = client.get(f"{self.base_url}/health")
            return resp.status_code == 200
    except Exception:
        return False

RemotePluginProxy.get_stats = get_stats
RemotePluginProxy.is_alive = is_alive

# %% ../../nbs/core/proxy.ipynb #drz681mgef7
def cancel(self) -> bool: # True if cancel request was sent
    """Request cancellation of running execution."""
    try:
        with httpx.Client(timeout=2) as client:
            resp = client.post(f"{self.base_url}/cancel")
        return resp.status_code == 200
    except httpx.ConnectError:
        return False  # Worker may have died

async def cancel_async(self) -> bool: # True if cancel request was sent
    """Request cancellation asynchronously."""
    try:
        async with httpx.AsyncClient(timeout=2) as client:
            resp = await client.post(f"{self.base_url}/cancel")
        return resp.status_code == 200
    except httpx.ConnectError:
        return False

def get_progress(self) -> Dict[str, Any]: # {progress: float, message: str}
    """Get current execution progress from worker."""
    try:
        with httpx.Client(timeout=2) as client:
            resp = client.get(f"{self.base_url}/progress")
        if resp.status_code == 200:
            return resp.json()
        return {"progress": 0.0, "message": ""}
    except httpx.ConnectError:
        return {"progress": 0.0, "message": ""}

async def get_progress_async(self) -> Dict[str, Any]: # {progress: float, message: str}
    """Get current execution progress asynchronously."""
    try:
        async with httpx.AsyncClient(timeout=2) as client:
            resp = await client.get(f"{self.base_url}/progress")
        if resp.status_code == 200:
            return resp.json()
        return {"progress": 0.0, "message": ""}
    except httpx.ConnectError:
        return {"progress": 0.0, "message": ""}

RemotePluginProxy.cancel = cancel
RemotePluginProxy.cancel_async = cancel_async
RemotePluginProxy.get_progress = get_progress
RemotePluginProxy.get_progress_async = get_progress_async

# %% ../../nbs/core/proxy.ipynb #a14ab958
def on_disable(self) -> bool:  # True if hook signal accepted by worker
    """CR-2: forward the substrate's on_disable signal to the worker process.
    
    Plugin can opt in via PluginInterface.on_disable(); default implementation
    is a no-op so silent-pass-through is the norm. Failures to reach the
    worker (already terminated, network blip) are logged-and-swallowed —
    the substrate-side enable/disable bookkeeping doesn't depend on the
    hook actually firing.
    """
    try:
        with httpx.Client(timeout=5) as client:
            resp = client.post(f"{self.base_url}/on_disable")
        return resp.status_code == 200
    except httpx.ConnectError:
        return False  # Worker may have died; substrate carries on


def on_enable(self) -> bool:  # True if hook signal accepted by worker
    """CR-2: forward the substrate's on_enable signal to the worker process.
    
    Same delivery semantics as on_disable: best-effort, errors logged-and-
    swallowed. The plugin's hook (default no-op) decides whether to eagerly
    re-acquire resources or rely on lazy re-load at next execute().
    """
    try:
        with httpx.Client(timeout=5) as client:
            resp = client.post(f"{self.base_url}/on_enable")
        return resp.status_code == 200
    except httpx.ConnectError:
        return False


RemotePluginProxy.on_disable = on_disable
RemotePluginProxy.on_enable = on_enable

# %% ../../nbs/core/proxy.ipynb #7adc9ae9
def get_system_status(self) -> Optional[Dict[str, Any]]:  # SystemStats dict, or None on transport failure
    """CR-3: typed MonitorPlugin accessor. POSTs to worker's `/get_system_status`.
    
    Status code semantics (worker side raises HTTPException with these codes):
    - 200: SystemStats dict returned
    - 404: plugin is not a MonitorPlugin — propagates as HTTPStatusError so the
          substrate caller sees a configuration error rather than silently empty stats
    - 501: legacy monitor predating CR-3; REMOVE-AFTER-OVERHAUL fallback to
          `/execute("get_system_status")` returns a dict in the pre-CR-3 wire format
    - 500: real plugin failure; propagates as HTTPStatusError
    
    Returns None on `httpx.ConnectError` (worker may have died) so the substrate's
    `_get_global_stats` exception handler can degrade gracefully.
    """
    try:
        with httpx.Client(timeout=5) as client:
            resp = client.post(f"{self.base_url}/get_system_status")
        if resp.status_code == 200:
            return resp.json()
        if resp.status_code == 501:
            # REMOVE-AFTER-OVERHAUL: dispatcher fallback for pre-CR-3 monitors.
            # SG-47 cascade migrates monitor plugins to typed methods; SG-48 sweep
            # then drops this branch (worker never returns 501 once cascade lands).
            return self.execute("get_system_status")
        resp.raise_for_status()
        return None
    except httpx.ConnectError:
        return None


async def get_system_status_async(self) -> Optional[Dict[str, Any]]:  # SystemStats dict, or None on transport failure
    """Async variant of `get_system_status`. Same 200/404/501/500/ConnectError semantics."""
    try:
        async with httpx.AsyncClient(timeout=5) as client:
            resp = await client.post(f"{self.base_url}/get_system_status")
        if resp.status_code == 200:
            return resp.json()
        if resp.status_code == 501:
            # REMOVE-AFTER-OVERHAUL: see sync variant
            return await self.execute_async("get_system_status")
        resp.raise_for_status()
        return None
    except httpx.ConnectError:
        return None


def list_processes(self) -> Optional[List[Dict[str, Any]]]:  # ProcessStats dict list, or None on transport failure
    """CR-3: typed MonitorPlugin accessor. POSTs to worker's `/list_processes`.
    
    Same 200/404/501/500/ConnectError semantics as `get_system_status`. Note that
    `MonitorPlugin.list_processes()` defaults to returning `[]`, so monitors without
    per-process visibility yield a 200 with an empty list rather than 501.
    """
    try:
        with httpx.Client(timeout=5) as client:
            resp = client.post(f"{self.base_url}/list_processes")
        if resp.status_code == 200:
            return resp.json()
        if resp.status_code == 501:
            # REMOVE-AFTER-OVERHAUL: dispatcher fallback for pre-CR-3 monitors
            return self.execute("list_processes")
        resp.raise_for_status()
        return None
    except httpx.ConnectError:
        return None


async def list_processes_async(self) -> Optional[List[Dict[str, Any]]]:  # ProcessStats dict list, or None on transport failure
    """Async variant of `list_processes`. Same semantics."""
    try:
        async with httpx.AsyncClient(timeout=5) as client:
            resp = await client.post(f"{self.base_url}/list_processes")
        if resp.status_code == 200:
            return resp.json()
        if resp.status_code == 501:
            # REMOVE-AFTER-OVERHAUL: see sync variant
            return await self.execute_async("list_processes")
        resp.raise_for_status()
        return None
    except httpx.ConnectError:
        return None


RemotePluginProxy.get_system_status = get_system_status
RemotePluginProxy.get_system_status_async = get_system_status_async
RemotePluginProxy.list_processes = list_processes
RemotePluginProxy.list_processes_async = list_processes_async

# %% ../../nbs/core/proxy.ipynb #context-manager
def __enter__(self):
    """Enter context manager."""
    return self

def __exit__(self, exc_type, exc_val, exc_tb):
    """Exit context manager and cleanup."""
    self.cleanup()
    return False

async def __aenter__(self):
    """Enter async context manager."""
    return self

async def __aexit__(self, exc_type, exc_val, exc_tb):
    """Exit async context manager and cleanup."""
    self.cleanup()
    return False

RemotePluginProxy.__enter__ = __enter__
RemotePluginProxy.__exit__ = __exit__
RemotePluginProxy.__aenter__ = __aenter__
RemotePluginProxy.__aexit__ = __aexit__
