"""Resource-aware job queue for sequential plugin execution with cancellation support"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/queue.ipynb.

# %% auto #0
__all__ = ['JobStatus', 'JobEventType', 'CancelPhase', 'JobQueueDependencies', 'Job', 'JobEvent', 'QueueStats', 'JobQueue',
           'submit', 'cancel', 'reorder', 'get_job', 'wait_for_job', 'get_pending', 'get_running', 'get_history',
           'get_stats', 'get_job_logs', 'events', 'events_for_sequence', 'all_events', 'start', 'stop', 'get_state']

# %% ../../nbs/core/queue.ipynb #exports
import asyncio
import heapq
import uuid
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import (
    Any, AsyncIterator, Callable, Dict, List, Optional, Protocol,
    Set, Tuple, TYPE_CHECKING, runtime_checkable,
)

from cjm_plugin_system.core.errors import (
    JobError, TracebackPolicy, map_bare_exception_to_job_error,
)

# CR-6: PluginManager continues to satisfy JobQueueDependencies structurally.
# Imported under TYPE_CHECKING to thin runtime coupling per OQ-5 resolution —
# JobQueue stays inline in cjm-plugin-system for v1; the Protocol enables clean
# future extraction.
if TYPE_CHECKING:
    from cjm_plugin_system.core.manager import PluginManager

# SG-39: library modules use `logging.getLogger(__name__)` and let the host
# (CLI entry point, FastHTML app, worker subprocess) own `basicConfig`.
import logging

# %% ../../nbs/core/queue.ipynb #status-enum
class JobStatus(str, Enum):
    """Status of a job in the queue."""
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"
    cancelled = "cancelled"


class JobEventType(str, Enum):
    """Push-based job event types (CR-6).

    Emitted by JobQueue on a multi-subscriber event bus. Consumers subscribe
    via `queue.events(job_id)` / `queue.events_for_sequence(seq_id)` /
    `queue.all_events()` and receive `JobEvent` instances asynchronously.

    Stage 1 wires STATE_TRANSITION + PROGRESS_CHANGED at the existing
    execute-path lifecycle points. The remaining types are reserved for
    Stages 2-4 (sequences / resources + logs / cancel-phase + retry +
    block-reason). Reserving the enum values up front keeps later stages
    additive — new event sources publish without changing the enum.
    """
    STATE_TRANSITION = "state_transition"          # JobStatus changed (Stage 1)
    PROGRESS_CHANGED = "progress_changed"          # progress / status_message updated (Stage 1)
    SEQUENCE_ADVANCED = "sequence_advanced"        # Sequence moved to next member job (Stage 2)
    RESOURCE_SNAPSHOT = "resource_snapshot"        # Periodic worker + sysmon stats (Stage 3)
    LOG_APPENDED = "log_appended"                  # New log lines for this job (Stage 3)
    BLOCK_REASON_CHANGED = "block_reason_changed"  # Scheduler block reason changed (Stage 4)
    CANCEL_PHASE_CHANGED = "cancel_phase_changed"  # Cancel state machine progressed (Stage 4)
    RETRY_STARTED = "retry_started"                # Reactive retry beginning (CR-7 + Stage 4)


class CancelPhase(str, Enum):
    """Phase of a cancellation in progress (CR-6 + CR-4 pairing).

    Surfaces the substrate's cancel state machine. Stage 4 wires the
    transitions; Stage 1 reserves the enum so `Job.cancel_phase` can be
    typed correctly without dangling forward references.
    """
    COOPERATIVE = "cooperative"  # Cancel signal sent; awaiting plugin acknowledgement
    FORCE = "force"              # Cooperative timeout; force-terminating worker
    RELOADING = "reloading"      # Worker reload in progress post-force-kill
    COMPLETED = "completed"      # Cancellation fully complete

# %% ../../nbs/core/queue.ipynb #085c210c
@runtime_checkable
class JobQueueDependencies(Protocol):
    """Substrate dependencies the JobQueue requires (CR-6).

    PluginManager satisfies this structurally; the Protocol exists so JobQueue
    can be tested in isolation (with a lightweight test double) and so a future
    extraction into a separate library has no API constraint locked in.

    Method surface chosen empirically — these are the exact 5 methods the
    queue's execute path calls today. Adding new dependencies to the Protocol
    (e.g., a typed system-monitor reader when Stage 3 wires resource snapshots)
    is an additive change.
    """
    def get_plugin_meta(self, name_or_id: str) -> Optional[Any]: ...
    def get_plugin(self, name_or_id: str) -> Optional[Any]: ...
    async def execute_plugin_async(self, name_or_id: str, *args: Any, **kwargs: Any) -> Any: ...
    def reload_plugin(self, name_or_id: str) -> Any: ...
    def get_plugin_logs(self, plugin_name: str, lines: int = 50) -> str: ...

# %% ../../nbs/core/queue.ipynb #job-dataclass
@dataclass
class Job:
    """A queued plugin execution request (CR-6 reshape).

    Stage 1 lands the full field set so subsequent stages are purely additive
    on the population paths. Fields tagged "Stage N" are typed but unpopulated
    by Stage 1's execute path; their default values keep the dataclass safely
    constructible from existing call sites.
    """
    id: str  # Unique job identifier (UUID)
    plugin_instance_id: str  # Target plugin instance (per CR-10)
    args: Tuple[Any, ...]  # Positional arguments for execute()
    kwargs: Dict[str, Any]  # Keyword arguments for execute()
    status: JobStatus = JobStatus.pending  # Current job status
    priority: int = 0  # Higher = more urgent
    submitted_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))  # When submitted
    started_at: Optional[datetime] = None  # When execution started
    completed_at: Optional[datetime] = None  # When execution finished
    progress: float = 0.0  # 0.0 to 1.0, or -1.0 for indeterminate
    status_message: str = ""  # Descriptive status message
    result: Any = None  # Execution result (if completed)
    error: Optional[JobError] = None  # Structured failure summary (CR-5)
    # CR-6 fields populated across staged commits:
    sequence_id: Optional[str] = None  # Set when part of a sequence (Stage 2)
    sequence_index: Optional[int] = None  # 0-based position in sequence (Stage 2)
    cancel_requested_at: Optional[datetime] = None  # When cancel was requested (Stage 4)
    cancel_phase: Optional[CancelPhase] = None  # Active cancel phase (Stage 4)
    block_reason: Optional[str] = None  # Why the scheduler is blocking (Stage 4)
    retry_count: int = 0  # Reactive retries attempted (CR-7 + Stage 4)
    last_resource_snapshot: Optional[Any] = None  # Stage 3 wires this (ResourceSnapshot)

    def __lt__(self, other: 'Job') -> bool:
        """Compare jobs for priority queue (higher priority first, then FIFO).

        Negate priority so higher values come first in the min-heap; use
        submitted_at as tiebreaker (earlier first). datetime supports < natively.
        """
        return (-self.priority, self.submitted_at) < (-other.priority, other.submitted_at)

    # REMOVE-AFTER-OVERHAUL: backward-compat aliases for the CR-6 rename
    # cascade. External consumers (job-monitor library, decomp host) read
    # `job.plugin_name` and `job.created_at` today; these properties keep
    # those call sites working until SG-47/SG-48 sweeps migrate them.
    @property
    def plugin_name(self) -> str:
        return self.plugin_instance_id

    @property
    def created_at(self) -> float:
        return self.submitted_at.timestamp()


@dataclass
class JobEvent:
    """A push-based job event (CR-6).

    Carries full tag context so a subscriber to `all_events()`, `events(job_id)`,
    or `events_for_sequence(seq_id)` receives identically-shaped instances.
    `payload` is a per-event-type structured dict (e.g., STATE_TRANSITION carries
    `{"from": "pending", "to": "running"}`; PROGRESS_CHANGED carries
    `{"progress": 0.42, "status_message": "..."}`).
    """
    type: JobEventType
    job_id: str
    plugin_instance_id: str
    sequence_id: Optional[str] = None
    sequence_index: Optional[int] = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    payload: Dict[str, Any] = field(default_factory=dict)


@dataclass
class QueueStats:
    """Aggregate counts returned by `JobQueue.get_stats()` (CR-6)."""
    total_pending: int
    total_completed: int
    total_failed: int
    total_cancelled: int


@dataclass
class _Subscription:
    """Internal: per-subscriber bounded queue + drop counter (CR-6 event bus).

    Slow subscribers backpressure themselves via `asyncio.QueueFull` drop;
    the publisher never blocks. `dropped_count` surfaces visibility for
    operators / future telemetry.
    """
    queue: 'asyncio.Queue[JobEvent]'
    dropped_count: int = 0

# %% ../../nbs/core/queue.ipynb #queue-class
class JobQueue:
    """Resource-aware job queue with push-based observability (CR-6)."""

    # CR-6: per-subscriber bounded queue size. Slow subscribers backpressure
    # themselves via QueueFull drop; publisher never blocks. 100 events is
    # large enough that a UI tab pause of a few seconds doesn't drop events
    # under typical workloads, small enough that a stuck subscriber doesn't
    # accumulate unbounded memory.
    SUBSCRIBER_QUEUE_MAXSIZE: int = 100

    def __init__(
        self,
        deps: JobQueueDependencies,  # Substrate dependencies (PluginManager satisfies structurally)
        max_history: int = 100,      # Max completed jobs to retain
        cancel_timeout: float = 3.0, # Seconds to wait for cooperative cancel
        progress_poll_interval: float = 1.0  # Seconds between progress polls
    ):
        """Initialize the job queue."""
        self._deps = deps
        self.max_history = max_history
        self.cancel_timeout = cancel_timeout
        self.progress_poll_interval = progress_poll_interval
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")

        # State
        self._pending: List[Job] = []  # Priority heap
        self._running: Optional[Job] = None
        self._history: List[Job] = []  # Completed/cancelled/failed jobs
        self._jobs: Dict[str, Job] = {}  # All jobs by ID for fast lookup

        # Synchronization
        self._lock = asyncio.Lock()
        self._job_available = asyncio.Event()
        self._job_completed_events: Dict[str, asyncio.Event] = {}

        # CR-6: multi-subscriber event bus.
        # Keys: "all" (firehose), "job:<id>", "seq:<id>". Each subscriber owns
        # one bounded asyncio.Queue; the publisher fans out to every matching
        # key. Independent of `_job_completed_events` (which backs the
        # `wait_for_job` simple-block affordance).
        self._subscribers: Dict[str, List[_Subscription]] = defaultdict(list)

        # Background task
        self._processor_task: Optional[asyncio.Task] = None
        self._running_flag = False
        self._cancel_requested: Set[str] = set()  # Job IDs pending cancellation

    # REMOVE-AFTER-OVERHAUL: backward-compat alias for `self.manager`. The
    # SG-13 regression test + any host inspection still expects a `.manager`
    # attribute. SG-48 sweep retires this after consumer cascade migrates
    # to the new `deps`/`_deps` shape.
    @property
    def manager(self) -> JobQueueDependencies:
        return self._deps

# %% ../../nbs/core/queue.ipynb #submission
async def submit(
    self,
    plugin_instance_id: str,  # Target plugin instance (per CR-10)
    *args,
    priority: int = 0,  # Higher = more urgent
    **kwargs
) -> str:  # Returns job_id
    """Submit a job to the queue.

    CR-2: rejects jobs for disabled plugins at submit time (typed
    PluginDisabledError) so the failure surface matches PluginManager.
    execute_plugin's disabled gate. Submitting to a disabled plugin would
    otherwise sit in the queue until execution, then raise — moving the
    check earlier gives operators an actionable signal immediately.

    CR-6: no STATE_TRANSITION event fires at submit because the job is
    already in `pending` state at construction — there's no transition
    to publish. The first STATE_TRANSITION fires when the processor loop
    moves the job pending → running.
    """
    # CR-2: late import to avoid pulling errors module into queue's import
    # path during library load (keeps the worker.py-via-queue.py import
    # chain minimal).
    from cjm_plugin_system.core.errors import PluginDisabledError

    meta = self._deps.get_plugin_meta(plugin_instance_id)
    if meta is not None and not meta.enabled:
        raise PluginDisabledError(plugin_instance_id)

    job_id = str(uuid.uuid4())
    job = Job(
        id=job_id,
        plugin_instance_id=plugin_instance_id,
        args=args,
        kwargs=kwargs,
        priority=priority,
    )

    async with self._lock:
        self._jobs[job_id] = job
        heapq.heappush(self._pending, job)
        self._job_completed_events[job_id] = asyncio.Event()
        self._job_available.set()

    self.logger.info(f"Submitted job {job_id[:8]} for {plugin_instance_id} (priority={priority})")
    return job_id

JobQueue.submit = submit

# %% ../../nbs/core/queue.ipynb #control
async def cancel(
    self,
    job_id: str  # Job to cancel
) -> bool:  # True if cancelled
    """Cancel a pending or running job.

    CR-6: publishes STATE_TRANSITION when a pending job moves directly to
    cancelled (no transition through running). Running-job cancellation
    publishes CANCEL_PHASE_CHANGED events from `_execute_with_cancellation`
    when Stage 4 wires the phase transitions; Stage 1 just records the
    cancel-request marker.
    """
    async with self._lock:
        job = self._jobs.get(job_id)
        if not job:
            return False

        if job.status == JobStatus.pending:
            # Move directly to cancelled (job never ran)
            prev_status = job.status
            job.status = JobStatus.cancelled
            job.completed_at = datetime.now(timezone.utc)
            self._pending = [j for j in self._pending if j.id != job_id]
            heapq.heapify(self._pending)
            # SG-13: signal before moving to history so the just-cancelled job's
            # event is set before any eviction could pop it from the dict.
            self._signal_job_completed(job_id)
            self._move_to_history(job)
            self._publish_event(JobEvent(
                type=JobEventType.STATE_TRANSITION,
                job_id=job.id,
                plugin_instance_id=job.plugin_instance_id,
                sequence_id=job.sequence_id,
                sequence_index=job.sequence_index,
                payload={"from": prev_status.value, "to": job.status.value},
            ))
            self.logger.info(f"Cancelled pending job {job_id[:8]}")
            return True

        elif job.status == JobStatus.running:
            # Signal cancellation request; phase-transition events (Stage 4)
            # fire from `_execute_with_cancellation` as cooperative → force
            # → reloading → completed unfolds.
            self._cancel_requested.add(job_id)
            job.cancel_requested_at = datetime.now(timezone.utc)
            self.logger.info(f"Cancellation requested for running job {job_id[:8]}")
            return True

        return False  # Already completed/cancelled/failed

def reorder(
    self,
    job_id: str,  # Job to move
    new_priority: int  # New priority value
) -> bool:  # True if reordered
    """Change the priority of a pending job."""
    job = self._jobs.get(job_id)
    if not job or job.status != JobStatus.pending:
        return False

    job.priority = new_priority
    heapq.heapify(self._pending)
    self.logger.info(f"Reordered job {job_id[:8]} to priority {new_priority}")
    return True

JobQueue.cancel = cancel
JobQueue.reorder = reorder

# %% ../../nbs/core/queue.ipynb #observation
def get_job(
    self,
    job_id: str  # Job to retrieve
) -> Optional[Job]:  # Job or None
    """Get a job by ID."""
    return self._jobs.get(job_id)

async def wait_for_job(
    self,
    job_id: str,  # Job to wait for
    timeout: Optional[float] = None  # Max seconds to wait
) -> Job:  # Completed/failed/cancelled job
    """Wait for a job to complete.

    Independent of the CR-6 event bus — uses a per-job `asyncio.Event` for
    the simple block-until-done affordance. Streaming consumers should use
    `events(job_id)` instead.
    """
    event = self._job_completed_events.get(job_id)
    if not event:
        job = self._jobs.get(job_id)
        if job and job.status in (JobStatus.completed, JobStatus.failed, JobStatus.cancelled):
            return job
        raise ValueError(f"Unknown job: {job_id}")

    try:
        await asyncio.wait_for(event.wait(), timeout=timeout)
    except asyncio.TimeoutError:
        raise TimeoutError(f"Timeout waiting for job {job_id}")

    return self._jobs[job_id]

def get_pending(self) -> List[Job]:  # Pending jobs, priority-sorted
    """Get pending jobs, priority-sorted (higher priority first, then FIFO)."""
    return sorted(self._pending)

def get_running(self) -> Optional[Job]:  # Running job or None
    """Get the currently-executing job, or None if idle."""
    return self._running

def get_history(
    self,
    limit: Optional[int] = None,  # Max jobs to return (most recent N); None = all
) -> List[Job]:  # Completed/failed/cancelled jobs, most recent first
    """Get completed jobs, most recent first.

    If `limit` is provided, returns the most recent N. The internal history
    list grows append-only up to `max_history`, so older jobs are evicted
    in submission order (oldest first).
    """
    history = self._history if limit is None else self._history[-limit:]
    return list(reversed(history))

def get_stats(self) -> QueueStats:  # Aggregate counts
    """Get aggregate queue stats — total counts by terminal status."""
    return QueueStats(
        total_pending=len(self._pending),
        total_completed=sum(1 for j in self._history if j.status == JobStatus.completed),
        total_failed=sum(1 for j in self._history if j.status == JobStatus.failed),
        total_cancelled=sum(1 for j in self._history if j.status == JobStatus.cancelled),
    )

def get_job_logs(
    self,
    job_id: str,  # Job to get logs for
    lines: int = 100  # Max lines to return
) -> str:  # Log content
    """Get logs for a job from the plugin's log file.

    Stage 1: delegates the whole-plugin-log read to `JobQueueDependencies.
    get_plugin_logs`. Stage 3 will scope by `(started_at, completed_at)`
    so the return is bounded to this job's execution window.
    """
    job = self._jobs.get(job_id)
    if not job:
        return ""

    return self._deps.get_plugin_logs(job.plugin_instance_id, lines=lines)

JobQueue.get_job = get_job
JobQueue.wait_for_job = wait_for_job
JobQueue.get_pending = get_pending
JobQueue.get_running = get_running
JobQueue.get_history = get_history
JobQueue.get_stats = get_stats
JobQueue.get_job_logs = get_job_logs

# %% ../../nbs/core/queue.ipynb #b4fe9d38
def _subscriber_keys_for(event: JobEvent) -> List[str]:
    """Return the subscriber keys an event should fan out to (CR-6).

    Every event reaches "all" subscribers + the per-job subscribers.
    Sequence-tagged events additionally reach per-sequence subscribers.
    """
    keys = ["all", f"job:{event.job_id}"]
    if event.sequence_id is not None:
        keys.append(f"seq:{event.sequence_id}")
    return keys


def _publish_event(
    self,
    event: JobEvent,  # Event to fan out
) -> None:
    """Fan out an event to all matching subscribers (CR-6).

    Slow subscribers backpressure themselves via `asyncio.QueueFull` drop —
    publisher never blocks. Each subscriber tracks `dropped_count` so
    operators / future telemetry can surface backpressure visibility.
    """
    for key in _subscriber_keys_for(event):
        # `self._subscribers` is a defaultdict but we use `.get` to avoid
        # accidentally creating empty lists for unused keys (which would
        # otherwise accumulate).
        for sub in self._subscribers.get(key, []):
            try:
                sub.queue.put_nowait(event)
            except asyncio.QueueFull:
                sub.dropped_count += 1
                self.logger.warning(
                    f"Subscriber to '{key}' dropped event "
                    f"(dropped_count={sub.dropped_count}); subscriber is "
                    f"falling behind."
                )


async def _subscribe(
    self,
    key: str,  # Subscriber key ("all" | "job:<id>" | "seq:<id>")
) -> AsyncIterator[JobEvent]:
    """Internal: register a subscription; yield events until the consumer
    exits the async generator.

    Cleanup runs in `finally` so the subscriber is unregistered even if the
    consumer raises or is cancelled. Empty key lists are deleted to avoid
    memory accumulation across many short-lived subscriptions.
    """
    sub = _Subscription(queue=asyncio.Queue(maxsize=self.SUBSCRIBER_QUEUE_MAXSIZE))
    self._subscribers[key].append(sub)
    try:
        while True:
            event = await sub.queue.get()
            yield event
    finally:
        try:
            self._subscribers[key].remove(sub)
            if not self._subscribers[key]:
                del self._subscribers[key]
        except (ValueError, KeyError):
            # Already removed (e.g., queue stop drained); idempotent cleanup.
            pass


async def events(
    self,
    job_id: str,  # Filter to events for this job
) -> AsyncIterator[JobEvent]:
    """Subscribe to events for a single job (async generator).

    Yields events as they fire. Multiple concurrent subscribers to the same
    job_id each get their own independent stream — useful for multi-tab UIs.
    """
    async for evt in self._subscribe(f"job:{job_id}"):
        yield evt


async def events_for_sequence(
    self,
    sequence_id: str,  # Filter to events tagged with this sequence
) -> AsyncIterator[JobEvent]:
    """Subscribe to events for all jobs in a sequence (async generator).

    Yields the unified per-sequence narrative: member-job lifecycle events
    interleaved with `SEQUENCE_ADVANCED` aggregate signals (wired in Stage 2).
    """
    async for evt in self._subscribe(f"seq:{sequence_id}"):
        yield evt


async def all_events(self) -> AsyncIterator[JobEvent]:
    """Subscribe to all events (firehose; async generator).

    Useful for global dashboards, audit logs, and telemetry sinks that need
    the complete event stream rather than a filtered view.
    """
    async for evt in self._subscribe("all"):
        yield evt


JobQueue._publish_event = _publish_event
JobQueue._subscribe = _subscribe
JobQueue.events = events
JobQueue.events_for_sequence = events_for_sequence
JobQueue.all_events = all_events

# %% ../../nbs/core/queue.ipynb #lifecycle
async def start(self) -> None:
    """Start the queue processor."""
    if self._running_flag:
        return
    
    self._running_flag = True
    self._processor_task = asyncio.create_task(self._process_loop())
    self.logger.info("Job queue started")

async def stop(self) -> None:
    """Stop the queue processor gracefully."""
    self._running_flag = False
    self._job_available.set()  # Wake up the processor
    
    if self._processor_task:
        try:
            await asyncio.wait_for(self._processor_task, timeout=5.0)
        except asyncio.TimeoutError:
            self._processor_task.cancel()
        self._processor_task = None
    
    self.logger.info("Job queue stopped")

JobQueue.start = start
JobQueue.stop = stop

# %% ../../nbs/core/queue.ipynb #internal
def _move_to_history(self, job: Job) -> None:
    """Move a job to history, maintaining max_history limit."""
    self._history.append(job)
    if len(self._history) > self.max_history:
        old_job = self._history.pop(0)
        # SG-13: set the evicted event before popping so any in-flight waiter
        # still holding the reference resolves immediately. Idempotent if the
        # event was already set by `_signal_job_completed`; protective if not.
        evicted = self._job_completed_events.pop(old_job.id, None)
        if evicted is not None:
            evicted.set()

def _signal_job_completed(self, job_id: str) -> None:
    """Signal that a job has completed."""
    event = self._job_completed_events.get(job_id)
    if event:
        event.set()

def _emit_state_transition(
    self,
    job: Job,
    prev_status: JobStatus,
) -> None:
    """Emit a STATE_TRANSITION event for `job`'s most recent status change.

    Centralized so every transition site (start, completed, failed, cancelled,
    or future cancel-phase-driven transitions) carries identical tag context.
    """
    self._publish_event(JobEvent(
        type=JobEventType.STATE_TRANSITION,
        job_id=job.id,
        plugin_instance_id=job.plugin_instance_id,
        sequence_id=job.sequence_id,
        sequence_index=job.sequence_index,
        payload={"from": prev_status.value, "to": job.status.value},
    ))

async def _process_loop(self) -> None:
    """Main processing loop."""
    while self._running_flag:
        # Wait for jobs
        await self._job_available.wait()

        if not self._running_flag:
            break

        async with self._lock:
            if not self._pending:
                self._job_available.clear()
                continue

            job = heapq.heappop(self._pending)
            if not self._pending:
                self._job_available.clear()

        # Process the job
        await self._execute_job(job)

async def _execute_job(self, job: Job) -> None:
    """Execute a single job."""
    self.logger.info(f"Starting job {job.id[:8]} ({job.plugin_instance_id})")

    # Mark as running + emit transition pending → running
    prev_status = job.status
    job.status = JobStatus.running
    job.started_at = datetime.now(timezone.utc)
    self._running = job
    self._emit_state_transition(job, prev_status)

    try:
        # Get the plugin proxy
        plugin = self._deps.get_plugin(job.plugin_instance_id)
        if not plugin:
            raise ValueError(f"Plugin not loaded: {job.plugin_instance_id}")

        # Start progress polling task
        progress_task = asyncio.create_task(
            self._poll_progress(job, plugin)
        )

        # Execute with cancellation support
        try:
            result = await self._execute_with_cancellation(job, plugin)

            if job.id in self._cancel_requested:
                prev = job.status
                job.status = JobStatus.cancelled
                self._cancel_requested.discard(job.id)
                self._emit_state_transition(job, prev)
            else:
                prev = job.status
                job.status = JobStatus.completed
                job.result = result
                self._emit_state_transition(job, prev)

        except asyncio.CancelledError:
            prev = job.status
            job.status = JobStatus.cancelled
            self._emit_state_transition(job, prev)
        except Exception as e:
            prev = job.status
            job.status = JobStatus.failed
            # CR-5: typed JobError carries category + retriable + structured
            # side-channels for PluginError subclasses. Stage 1 records the
            # bare-exception mapping; the CR-7 reactive-retry loop and Stage 4
            # cancel-phase wiring will populate further fields.
            job.error = map_bare_exception_to_job_error(
                e,
                plugin_instance_id=job.plugin_instance_id,
            )
            self.logger.error(f"Job {job.id[:8]} failed: {e}")
            self._emit_state_transition(job, prev)
        finally:
            progress_task.cancel()
            try:
                await progress_task
            except asyncio.CancelledError:
                pass

    except Exception as e:
        prev = job.status
        job.status = JobStatus.failed
        job.error = map_bare_exception_to_job_error(
            e,
            plugin_instance_id=job.plugin_instance_id,
        )
        self.logger.error(f"Job {job.id[:8]} failed: {e}")
        self._emit_state_transition(job, prev)

    # Finalize
    job.completed_at = datetime.now(timezone.utc)
    job.progress = 1.0 if job.status == JobStatus.completed else job.progress
    self._running = None

    async with self._lock:
        # SG-13: signal before moving to history so this job's event is set
        # before any eviction could pop it from the dict.
        self._signal_job_completed(job.id)
        self._move_to_history(job)

    self.logger.info(f"Job {job.id[:8]} {job.status.value}")

async def _execute_with_cancellation(
    self,
    job: Job,
    plugin: Any
) -> Any:
    """Execute job with cancellation monitoring.

    Stage 1 keeps the existing cooperative-then-force semantics; Stage 4
    wires CANCEL_PHASE_CHANGED events at the cooperative / force / reloading
    transitions.
    """
    # Start execution
    exec_task = asyncio.create_task(
        self._deps.execute_plugin_async(job.plugin_instance_id, *job.args, **job.kwargs)
    )

    # Monitor for cancellation
    while not exec_task.done():
        if job.id in self._cancel_requested:
            # Try cooperative cancellation first
            self.logger.info(f"Attempting cooperative cancel for {job.id[:8]}")

            if hasattr(plugin, 'cancel_async'):
                await plugin.cancel_async()
            elif hasattr(plugin, 'cancel'):
                plugin.cancel()

            # Wait briefly for cooperative cancellation
            try:
                return await asyncio.wait_for(exec_task, timeout=self.cancel_timeout)
            except asyncio.TimeoutError:
                # Force termination
                self.logger.warning(f"Force terminating plugin for job {job.id[:8]}")
                exec_task.cancel()

                # Reload the plugin to get a fresh worker
                self._deps.reload_plugin(job.plugin_instance_id)
                raise asyncio.CancelledError()

        await asyncio.sleep(0.1)

    return exec_task.result()

async def _poll_progress(
    self,
    job: Job,
    plugin: Any
) -> None:
    """Poll progress from the plugin during execution.

    Emits PROGRESS_CHANGED events when progress or status_message changes
    from the previous poll. Avoids spamming the event bus when polls return
    the same values (common between meaningful updates).
    """
    last_progress = job.progress
    last_message = job.status_message
    while True:
        try:
            if hasattr(plugin, 'get_progress_async'):
                progress_info = await plugin.get_progress_async()
            elif hasattr(plugin, 'get_progress'):
                progress_info = plugin.get_progress()
            else:
                break  # No progress support

            new_progress = progress_info.get('progress', 0.0)
            new_message = progress_info.get('message', '')
            job.progress = new_progress
            job.status_message = new_message

            if new_progress != last_progress or new_message != last_message:
                self._publish_event(JobEvent(
                    type=JobEventType.PROGRESS_CHANGED,
                    job_id=job.id,
                    plugin_instance_id=job.plugin_instance_id,
                    sequence_id=job.sequence_id,
                    sequence_index=job.sequence_index,
                    payload={"progress": new_progress, "status_message": new_message},
                ))
                last_progress = new_progress
                last_message = new_message

        except Exception:
            pass  # Ignore progress polling errors

        await asyncio.sleep(self.progress_poll_interval)

JobQueue._move_to_history = _move_to_history
JobQueue._signal_job_completed = _signal_job_completed
JobQueue._emit_state_transition = _emit_state_transition
JobQueue._process_loop = _process_loop
JobQueue._execute_job = _execute_job
JobQueue._execute_with_cancellation = _execute_with_cancellation
JobQueue._poll_progress = _poll_progress

# %% ../../nbs/core/queue.ipynb #0c35a476
def get_state(self) -> Dict[str, Any]:  # Queue state for UI (legacy shape)
    """Get the current queue state in the pre-CR-6 dict shape.

    REMOVE-AFTER-OVERHAUL: kept so existing UI consumers (notably
    `cjm-fasthtml-job-monitor`) continue to work until they migrate to the
    typed `get_pending` / `get_running` / `get_history` / `get_stats`
    accessors. Reads from the new accessors and reshapes:

    - Legacy keys (`plugin_name`, `created_at`) read from the renamed fields
      via the Job dataclass's backward-compat `@property` aliases.
    - Legacy `error` was a bare string; new is `JobError`. Shim returns
      `error.message` to preserve the string shape.
    - Legacy timestamps were unix floats; new are `datetime`. Shim returns
      `.timestamp()` to preserve float shape.
    """
    running = self.get_running()
    running_dict = None
    if running:
        running_dict = {
            "id": running.id,
            "plugin_name": running.plugin_instance_id,
            "status": running.status.value,
            "started_at": running.started_at.timestamp() if running.started_at else None,
            "progress": running.progress,
            "status_message": running.status_message,
        }

    pending_list = [
        {
            "id": j.id,
            "plugin_name": j.plugin_instance_id,
            "priority": j.priority,
            "position": i,
        }
        for i, j in enumerate(self.get_pending())
    ]

    history_list = [
        {
            "id": j.id,
            "plugin_name": j.plugin_instance_id,
            "status": j.status.value,
            "completed_at": j.completed_at.timestamp() if j.completed_at else None,
            "error": j.error.message if j.error else None,
        }
        for j in self.get_history(limit=20)
    ]

    stats = self.get_stats()
    return {
        "running": running_dict,
        "pending": pending_list,
        "history": history_list,
        "stats": {
            "total_pending": stats.total_pending,
            "total_completed": stats.total_completed,
            "total_failed": stats.total_failed,
            "total_cancelled": stats.total_cancelled,
        },
    }

JobQueue.get_state = get_state

# %% ../../nbs/core/queue.ipynb #e31875a2
# SG-15: curate __all__ to expose only the class + value symbols.
# The patched JobQueue methods (submit, cancel, wait_for_job, events, etc.)
# remain accessible as JobQueue.method() — they're removed from the module's
# `from ... import *` surface because invoking them standalone fails
# (they expect `self`). nbdev's auto-`__all__` lists them as free names;
# this override runs after that assignment and wins by being last.
#
# CR-6 additions: JobEventType + CancelPhase + JobEvent + QueueStats +
# JobQueueDependencies are first-class types that consumers import directly.
__all__ = [
    'JobStatus', 'JobEventType', 'CancelPhase',
    'Job', 'JobEvent', 'QueueStats',
    'JobQueueDependencies', 'JobQueue',
]
