"""Resource-aware job queue for sequential plugin execution with cancellation support"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/queue.ipynb.

# %% auto #0
__all__ = ['JobStatus', 'JobEventType', 'CancelPhase', 'JobQueueDependencies', 'Job', 'JobEvent', 'QueueStats', 'SequenceStep',
           'StepResult', 'JobSequence', 'ResourceSnapshot', 'JobQueue', 'submit', 'cancel', 'reorder', 'get_job',
           'wait_for_job', 'get_pending', 'get_running', 'get_history', 'get_stats', 'get_job_logs', 'events',
           'events_for_sequence', 'all_events', 'submit_sequence', 'submit_uniform_sequence', 'cancel_sequence',
           'get_sequence', 'get_resource_snapshot', 'start', 'stop', 'get_state']

# %% ../../nbs/core/queue.ipynb #exports
import asyncio
import heapq
import uuid
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import (
    Any, AsyncIterator, Callable, Dict, List, Optional, Protocol,
    Set, Tuple, TYPE_CHECKING, runtime_checkable,
)

from cjm_plugin_system.core.errors import (
    JobError, TracebackPolicy, map_bare_exception_to_job_error,
)

# CR-6: PluginManager continues to satisfy JobQueueDependencies structurally.
# Imported under TYPE_CHECKING to thin runtime coupling per OQ-5 resolution —
# JobQueue stays inline in cjm-plugin-system for v1; the Protocol enables clean
# future extraction.
if TYPE_CHECKING:
    from cjm_plugin_system.core.manager import PluginManager

# SG-39: library modules use `logging.getLogger(__name__)` and let the host
# (CLI entry point, FastHTML app, worker subprocess) own `basicConfig`.
import logging

# %% ../../nbs/core/queue.ipynb #status-enum
class JobStatus(str, Enum):
    """Status of a job in the queue."""
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"
    cancelled = "cancelled"


class JobEventType(str, Enum):
    """Push-based job event types (CR-6).

    Emitted by JobQueue on a multi-subscriber event bus. Consumers subscribe
    via `queue.events(job_id)` / `queue.events_for_sequence(seq_id)` /
    `queue.all_events()` and receive `JobEvent` instances asynchronously.

    Stage 1 wires STATE_TRANSITION + PROGRESS_CHANGED at the existing
    execute-path lifecycle points. The remaining types are reserved for
    Stages 2-4 (sequences / resources + logs / cancel-phase + retry +
    block-reason). Reserving the enum values up front keeps later stages
    additive — new event sources publish without changing the enum.
    """
    STATE_TRANSITION = "state_transition"          # JobStatus changed (Stage 1)
    PROGRESS_CHANGED = "progress_changed"          # progress / status_message updated (Stage 1)
    SEQUENCE_ADVANCED = "sequence_advanced"        # Sequence moved to next member job (Stage 2)
    RESOURCE_SNAPSHOT = "resource_snapshot"        # Periodic worker + sysmon stats (Stage 3)
    LOG_APPENDED = "log_appended"                  # New log lines for this job (Stage 3)
    BLOCK_REASON_CHANGED = "block_reason_changed"  # Scheduler block reason changed (Stage 4)
    CANCEL_PHASE_CHANGED = "cancel_phase_changed"  # Cancel state machine progressed (Stage 4)
    RETRY_STARTED = "retry_started"                # Reactive retry beginning (CR-7 + Stage 4)


class CancelPhase(str, Enum):
    """Phase of a cancellation in progress (CR-6 + CR-4 pairing).

    Surfaces the substrate's cancel state machine. Stage 4 wires the
    transitions; Stage 1 reserves the enum so `Job.cancel_phase` can be
    typed correctly without dangling forward references.
    """
    COOPERATIVE = "cooperative"  # Cancel signal sent; awaiting plugin acknowledgement
    FORCE = "force"              # Cooperative timeout; force-terminating worker
    RELOADING = "reloading"      # Worker reload in progress post-force-kill
    COMPLETED = "completed"      # Cancellation fully complete

# %% ../../nbs/core/queue.ipynb #085c210c
@runtime_checkable
class JobQueueDependencies(Protocol):
    """Substrate dependencies the JobQueue requires (CR-6).

    PluginManager satisfies this structurally; the Protocol exists so JobQueue
    can be tested in isolation (with a lightweight test double) and so a future
    extraction into a separate library has no API constraint locked in.

    Method surface chosen empirically — these are the exact 5 methods the
    queue's execute path calls today. Adding new dependencies to the Protocol
    (e.g., a typed system-monitor reader when Stage 3 wires resource snapshots)
    is an additive change.
    """
    def get_plugin_meta(self, name_or_id: str) -> Optional[Any]: ...
    def get_plugin(self, name_or_id: str) -> Optional[Any]: ...
    async def execute_plugin_async(self, name_or_id: str, *args: Any, **kwargs: Any) -> Any: ...
    def reload_plugin(self, name_or_id: str) -> Any: ...
    def get_plugin_logs(self, plugin_name: str, lines: int = 50) -> str: ...

# %% ../../nbs/core/queue.ipynb #job-dataclass
@dataclass
class Job:
    """A queued plugin execution request (CR-6 reshape).

    Stage 1 lands the full field set so subsequent stages are purely additive
    on the population paths. Fields tagged "Stage N" are typed but unpopulated
    by Stage 1's execute path; their default values keep the dataclass safely
    constructible from existing call sites.
    """
    id: str  # Unique job identifier (UUID)
    plugin_instance_id: str  # Target plugin instance (per CR-10)
    args: Tuple[Any, ...]  # Positional arguments for execute()
    kwargs: Dict[str, Any]  # Keyword arguments for execute()
    status: JobStatus = JobStatus.pending  # Current job status
    priority: int = 0  # Higher = more urgent
    submitted_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))  # When submitted
    started_at: Optional[datetime] = None  # When execution started
    completed_at: Optional[datetime] = None  # When execution finished
    progress: float = 0.0  # 0.0 to 1.0, or -1.0 for indeterminate
    status_message: str = ""  # Descriptive status message
    result: Any = None  # Execution result (if completed)
    error: Optional[JobError] = None  # Structured failure summary (CR-5)
    # CR-6 fields populated across staged commits:
    sequence_id: Optional[str] = None  # Set when part of a sequence (Stage 2)
    sequence_index: Optional[int] = None  # 0-based position in sequence (Stage 2)
    cancel_requested_at: Optional[datetime] = None  # When cancel was requested (Stage 4)
    cancel_phase: Optional[CancelPhase] = None  # Active cancel phase (Stage 4)
    block_reason: Optional[str] = None  # Why the scheduler is blocking (Stage 4)
    retry_count: int = 0  # Reactive retries attempted (CR-7 + Stage 4)
    last_resource_snapshot: Optional[Any] = None  # Stage 3 wires this (ResourceSnapshot)

    def __lt__(self, other: 'Job') -> bool:
        """Compare jobs for priority queue (higher priority first, then FIFO).

        Negate priority so higher values come first in the min-heap; use
        submitted_at as tiebreaker (earlier first). datetime supports < natively.
        """
        return (-self.priority, self.submitted_at) < (-other.priority, other.submitted_at)

    # REMOVE-AFTER-OVERHAUL: backward-compat aliases for the CR-6 rename
    # cascade. External consumers (job-monitor library, decomp host) read
    # `job.plugin_name` and `job.created_at` today; these properties keep
    # those call sites working until SG-47/SG-48 sweeps migrate them.
    @property
    def plugin_name(self) -> str:
        return self.plugin_instance_id

    @property
    def created_at(self) -> float:
        return self.submitted_at.timestamp()


@dataclass
class JobEvent:
    """A push-based job event (CR-6).

    Carries full tag context so a subscriber to `all_events()`, `events(job_id)`,
    or `events_for_sequence(seq_id)` receives identically-shaped instances.
    `payload` is a per-event-type structured dict (e.g., STATE_TRANSITION carries
    `{"from": "pending", "to": "running"}`; PROGRESS_CHANGED carries
    `{"progress": 0.42, "status_message": "..."}`).
    """
    type: JobEventType
    job_id: str
    plugin_instance_id: str
    sequence_id: Optional[str] = None
    sequence_index: Optional[int] = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    payload: Dict[str, Any] = field(default_factory=dict)


@dataclass
class QueueStats:
    """Aggregate counts returned by `JobQueue.get_stats()` (CR-6)."""
    total_pending: int
    total_completed: int
    total_failed: int
    total_cancelled: int


@dataclass
class _Subscription:
    """Internal: per-subscriber bounded queue + drop counter (CR-6 event bus).

    Slow subscribers backpressure themselves via `asyncio.QueueFull` drop;
    the publisher never blocks. `dropped_count` surfaces visibility for
    operators / future telemetry.
    """
    queue: 'asyncio.Queue[JobEvent]'
    dropped_count: int = 0

# %% ../../nbs/core/queue.ipynb #cab365ef
@dataclass
class SequenceStep:
    """A single step in a job sequence (CR-6 Stage 2).

    User-facing — supplied to `JobQueue.submit_sequence`. The substrate
    constructs the actual `Job` from this at advance time, tagging the
    job with `sequence_id` + `sequence_index` so it appears in
    `events_for_sequence` subscriptions.
    """
    plugin_instance_id: str  # Target plugin instance for this step
    args: Tuple[Any, ...] = ()  # Positional arguments
    kwargs: Dict[str, Any] = field(default_factory=dict)  # Keyword arguments
    priority: int = 0  # Per-step priority override (0 = inherit sequence priority)


@dataclass
class StepResult:
    """Result of one step in a job sequence (CR-6 Stage 2).

    `success=True` means the member-job completed with `JobStatus.completed`.
    Failure modes (failed / cancelled) capture the `JobError` in `error`.
    For best-effort sequences (`fail_fast=False`), failure rows are recorded
    in `JobSequence.results` and the sequence continues.
    """
    job_id: str  # Member job's UUID (empty string if sequence aborted before submit)
    success: bool  # True if the step's job completed successfully
    result: Any = None  # Job result (if success)
    error: Optional[JobError] = None  # Structured failure summary (if not success)


@dataclass
class JobSequence:
    """Internal: tracks a multi-step job sequence (CR-6 Stage 2).

    Lives in `JobQueue._sequences`. State machine: starts `running`,
    transitions to `completed` (all steps attempted) / `failed` (fail_fast
    halted on a failed member) / `cancelled` (cancel_sequence called or
    a member was cancelled). Once terminal, `completed_at` is set and
    `current_job_id` is cleared.
    """
    id: str  # Sequence UUID
    steps: List[SequenceStep]  # The full step list (immutable post-submit)
    fail_fast: bool = True  # Halt on first failure (audit-locked default)
    priority: int = 0  # Sequence-level priority (per-step override possible)
    current_index: int = 0  # 0-based index of the active member step
    current_job_id: Optional[str] = None  # The active member-job's ID, if any
    results: List[StepResult] = field(default_factory=list)  # Per-step outcomes
    status: JobStatus = JobStatus.running  # Sequence-level status (reuses JobStatus)
    submitted_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    completed_at: Optional[datetime] = None  # Set when sequence reaches terminal status

# %% ../../nbs/core/queue.ipynb #c28b79ab
@dataclass
class ResourceSnapshot:
    """Point-in-time resource usage for one job (CR-6 Stage 3).

    Worker stats (cpu_percent, memory_rss_mb) come from the plugin proxy's
    `get_stats()`. GPU fields come from the configured system-monitor plugin
    (when set on JobQueue) via CR-3's typed `list_processes()` (per-PID
    matching) and `get_system_status()` (global GPU stats). All GPU fields
    are Optional — None if no sysmon configured or the worker isn't running
    on a GPU.

    Distinct from CR-7's `EmpiricalResourceRecord` (aggregated profile
    across runs); this is "what's happening right now" for one job.
    """
    timestamp: datetime  # When the sample was taken
    worker_pid: int = 0  # OS PID of the plugin worker subprocess
    cpu_percent: float = 0.0  # Worker process CPU%
    memory_rss_mb: float = 0.0  # Worker process resident memory (MB)
    gpu_index: Optional[int] = None  # GPU index the worker is on (None if not GPU-bound)
    gpu_memory_mb: Optional[float] = None  # Worker's GPU memory usage (MB)
    gpu_type: Optional[str] = None  # GPU vendor (NVIDIA / AMD / Intel / None)
    gpu_total_mb: Optional[float] = None  # Total GPU memory available globally (MB)
    gpu_load_percent: Optional[float] = None  # GPU compute utilization (global)

# %% ../../nbs/core/queue.ipynb #queue-class
class JobQueue:
    """Resource-aware job queue with push-based observability (CR-6)."""

    # CR-6: per-subscriber bounded queue size. Slow subscribers backpressure
    # themselves via QueueFull drop; publisher never blocks. 100 events is
    # large enough that a UI tab pause of a few seconds doesn't drop events
    # under typical workloads, small enough that a stuck subscriber doesn't
    # accumulate unbounded memory.
    SUBSCRIBER_QUEUE_MAXSIZE: int = 100

    def __init__(
        self,
        deps: JobQueueDependencies,        # Substrate dependencies (PluginManager satisfies structurally)
        max_history: int = 100,            # Max completed jobs to retain
        cancel_timeout: float = 3.0,       # Seconds to wait for cooperative cancel
        progress_poll_interval: float = 1.0,  # Seconds between progress polls
        sysmon_plugin_name: Optional[str] = None,  # CR-3 MonitorPlugin instance for GPU stats (None = no GPU info)
        resource_snapshot_cadence_polls: int = 4,  # Sample resources every Nth progress poll
    ):
        """Initialize the job queue.

        CR-6 Stage 3 adds `sysmon_plugin_name` and `resource_snapshot_cadence_polls`.
        Sysmon integration is optional — when set, the named plugin must satisfy
        CR-3's typed `MonitorPlugin` shape (`get_system_status` + `list_processes`).
        When unset, ResourceSnapshot still carries worker stats but all GPU
        fields stay None.
        """
        self._deps = deps
        self.max_history = max_history
        self.cancel_timeout = cancel_timeout
        self.progress_poll_interval = progress_poll_interval
        self._sysmon_name = sysmon_plugin_name
        self.resource_snapshot_cadence_polls = max(1, resource_snapshot_cadence_polls)
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")

        # State
        self._pending: List[Job] = []  # Priority heap
        self._running: Optional[Job] = None
        self._history: List[Job] = []  # Completed/cancelled/failed jobs
        self._jobs: Dict[str, Job] = {}  # All jobs by ID for fast lookup

        # CR-6 Stage 2: sequence registry. JobSequence instances keyed by
        # sequence_id. Currently unbounded; sequence eviction is a follow-up
        # (parallel to `max_history` for terminal sequences).
        self._sequences: Dict[str, JobSequence] = {}

        # Synchronization
        self._lock = asyncio.Lock()
        self._job_available = asyncio.Event()
        self._job_completed_events: Dict[str, asyncio.Event] = {}

        # CR-6: multi-subscriber event bus.
        # Keys: "all" (firehose), "job:<id>", "seq:<id>". Each subscriber owns
        # one bounded asyncio.Queue; the publisher fans out to every matching
        # key. Independent of `_job_completed_events` (which backs the
        # `wait_for_job` simple-block affordance).
        self._subscribers: Dict[str, List[_Subscription]] = defaultdict(list)

        # Background task
        self._processor_task: Optional[asyncio.Task] = None
        self._running_flag = False
        self._cancel_requested: Set[str] = set()  # Job IDs pending cancellation

    # REMOVE-AFTER-OVERHAUL: backward-compat alias for `self.manager`. The
    # SG-13 regression test + any host inspection still expects a `.manager`
    # attribute. SG-48 sweep retires this after consumer cascade migrates
    # to the new `deps`/`_deps` shape.
    @property
    def manager(self) -> JobQueueDependencies:
        return self._deps

# %% ../../nbs/core/queue.ipynb #submission
async def _enqueue_job(
    self,
    job: Job,  # Pre-constructed Job (caller fills sequence fields if needed)
) -> str:  # job_id
    """Internal: enqueue a pre-constructed Job.

    Caller is responsible for validation (disabled-plugin check, etc.).
    Used by `submit` (Stage 1) and `submit_sequence` (Stage 2) — the latter
    needs to populate `sequence_id` + `sequence_index` on the Job before
    enqueueing so the running job appears in sequence-tagged event streams
    from its first STATE_TRANSITION.
    """
    async with self._lock:
        self._jobs[job.id] = job
        heapq.heappush(self._pending, job)
        self._job_completed_events[job.id] = asyncio.Event()
        self._job_available.set()

    seq_suffix = f" (seq {job.sequence_id[:8]} step {job.sequence_index})" if job.sequence_id else ""
    self.logger.info(
        f"Submitted job {job.id[:8]} for {job.plugin_instance_id} "
        f"(priority={job.priority}){seq_suffix}"
    )
    return job.id


async def submit(
    self,
    plugin_instance_id: str,  # Target plugin instance (per CR-10)
    *args,
    priority: int = 0,  # Higher = more urgent
    **kwargs
) -> str:  # Returns job_id
    """Submit a job to the queue.

    CR-2: rejects jobs for disabled plugins at submit time (typed
    PluginDisabledError) so the failure surface matches PluginManager.
    execute_plugin's disabled gate. Submitting to a disabled plugin would
    otherwise sit in the queue until execution, then raise — moving the
    check earlier gives operators an actionable signal immediately.

    CR-6: no STATE_TRANSITION event fires at submit because the job is
    already in `pending` state at construction — there's no transition
    to publish. The first STATE_TRANSITION fires when the processor loop
    moves the job pending → running.
    """
    # CR-2: late import to avoid pulling errors module into queue's import
    # path during library load (keeps the worker.py-via-queue.py import
    # chain minimal).
    from cjm_plugin_system.core.errors import PluginDisabledError

    meta = self._deps.get_plugin_meta(plugin_instance_id)
    if meta is not None and not meta.enabled:
        raise PluginDisabledError(plugin_instance_id)

    job = Job(
        id=str(uuid.uuid4()),
        plugin_instance_id=plugin_instance_id,
        args=args,
        kwargs=kwargs,
        priority=priority,
    )
    return await self._enqueue_job(job)

JobQueue._enqueue_job = _enqueue_job
JobQueue.submit = submit

# %% ../../nbs/core/queue.ipynb #control
async def cancel(
    self,
    job_id: str  # Job to cancel
) -> bool:  # True if cancelled
    """Cancel a pending or running job.

    CR-6: publishes STATE_TRANSITION when a pending job moves directly to
    cancelled (no transition through running). Running-job cancellation
    publishes CANCEL_PHASE_CHANGED events from `_execute_with_cancellation`
    when Stage 4 wires the phase transitions; Stage 1 just records the
    cancel-request marker.

    Stage 2: when the cancelled job is a sequence member, `_advance_sequence`
    runs after the lock is released so the cancelled status propagates to
    the sequence registry (marks sequence cancelled, no further submission).
    Lock release is required because `_advance_sequence` may need to enqueue
    a next member in some flows; asyncio.Lock is not re-entrant.
    """
    advance_target: Optional[Job] = None
    async with self._lock:
        job = self._jobs.get(job_id)
        if not job:
            return False

        if job.status == JobStatus.pending:
            # Move directly to cancelled (job never ran)
            prev_status = job.status
            job.status = JobStatus.cancelled
            job.completed_at = datetime.now(timezone.utc)
            self._pending = [j for j in self._pending if j.id != job_id]
            heapq.heapify(self._pending)
            # SG-13: signal before moving to history so the just-cancelled job's
            # event is set before any eviction could pop it from the dict.
            self._signal_job_completed(job_id)
            self._move_to_history(job)
            self._publish_event(JobEvent(
                type=JobEventType.STATE_TRANSITION,
                job_id=job.id,
                plugin_instance_id=job.plugin_instance_id,
                sequence_id=job.sequence_id,
                sequence_index=job.sequence_index,
                payload={"from": prev_status.value, "to": job.status.value},
            ))
            self.logger.info(f"Cancelled pending job {job_id[:8]}")
            if job.sequence_id is not None:
                advance_target = job

        elif job.status == JobStatus.running:
            # Signal cancellation request; phase-transition events (Stage 4)
            # fire from `_execute_with_cancellation` as cooperative → force
            # → reloading → completed unfolds. Sequence advance for a
            # running cancelled job happens from `_execute_job`'s finalization
            # path once the cancel resolves.
            self._cancel_requested.add(job_id)
            job.cancel_requested_at = datetime.now(timezone.utc)
            self.logger.info(f"Cancellation requested for running job {job_id[:8]}")
            return True

        else:
            return False  # Already completed/cancelled/failed

    # Outside the lock — safe to call _advance_sequence which may enqueue
    # follow-on work (no follow-on for cancelled members, but the invariant
    # is preserved for code symmetry with the running-job advance path).
    if advance_target is not None:
        await self._advance_sequence(advance_target)
    return True


def reorder(
    self,
    job_id: str,  # Job to move
    new_priority: int  # New priority value
) -> bool:  # True if reordered
    """Change the priority of a pending job."""
    job = self._jobs.get(job_id)
    if not job or job.status != JobStatus.pending:
        return False

    job.priority = new_priority
    heapq.heapify(self._pending)
    self.logger.info(f"Reordered job {job_id[:8]} to priority {new_priority}")
    return True

JobQueue.cancel = cancel
JobQueue.reorder = reorder

# %% ../../nbs/core/queue.ipynb #observation
def get_job(
    self,
    job_id: str  # Job to retrieve
) -> Optional[Job]:  # Job or None
    """Get a job by ID."""
    return self._jobs.get(job_id)

async def wait_for_job(
    self,
    job_id: str,  # Job to wait for
    timeout: Optional[float] = None  # Max seconds to wait
) -> Job:  # Completed/failed/cancelled job
    """Wait for a job to complete.

    Independent of the CR-6 event bus — uses a per-job `asyncio.Event` for
    the simple block-until-done affordance. Streaming consumers should use
    `events(job_id)` instead.
    """
    event = self._job_completed_events.get(job_id)
    if not event:
        job = self._jobs.get(job_id)
        if job and job.status in (JobStatus.completed, JobStatus.failed, JobStatus.cancelled):
            return job
        raise ValueError(f"Unknown job: {job_id}")

    try:
        await asyncio.wait_for(event.wait(), timeout=timeout)
    except asyncio.TimeoutError:
        raise TimeoutError(f"Timeout waiting for job {job_id}")

    return self._jobs[job_id]

def get_pending(self) -> List[Job]:  # Pending jobs, priority-sorted
    """Get pending jobs, priority-sorted (higher priority first, then FIFO)."""
    return sorted(self._pending)

def get_running(self) -> Optional[Job]:  # Running job or None
    """Get the currently-executing job, or None if idle."""
    return self._running

def get_history(
    self,
    limit: Optional[int] = None,  # Max jobs to return (most recent N); None = all
) -> List[Job]:  # Completed/failed/cancelled jobs, most recent first
    """Get completed jobs, most recent first.

    If `limit` is provided, returns the most recent N. The internal history
    list grows append-only up to `max_history`, so older jobs are evicted
    in submission order (oldest first).
    """
    history = self._history if limit is None else self._history[-limit:]
    return list(reversed(history))

def get_stats(self) -> QueueStats:  # Aggregate counts
    """Get aggregate queue stats — total counts by terminal status."""
    return QueueStats(
        total_pending=len(self._pending),
        total_completed=sum(1 for j in self._history if j.status == JobStatus.completed),
        total_failed=sum(1 for j in self._history if j.status == JobStatus.failed),
        total_cancelled=sum(1 for j in self._history if j.status == JobStatus.cancelled),
    )

# CR-6 Stage 3: log-slicing helpers. Worker log format from `worker.py`
# `basicConfig`: `%(asctime)s [%(levelname)s] %(message)s`. Default asctime
# emits local-time with millisecond precision: `YYYY-MM-DD HH:MM:SS,mmm`.
import re as _re_logslice
_LOG_TS_PATTERN = _re_logslice.compile(r'^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}),(\d{3})\s')


def _parse_log_timestamp(line: str) -> Optional[datetime]:
    """Parse the leading timestamp from a worker log line.

    Returns naive datetime (no tzinfo) in local time — caller is responsible
    for tz alignment with the job's UTC timestamps. Returns None for
    continuation lines (no parseable leading timestamp), blank lines, etc.
    """
    m = _LOG_TS_PATTERN.match(line)
    if not m:
        return None
    try:
        dt = datetime.strptime(m.group(1), "%Y-%m-%d %H:%M:%S")
        return dt.replace(microsecond=int(m.group(2)) * 1000)
    except ValueError:
        return None


def _slice_log_by_job_window(
    raw: str,  # Full log content
    started_at: datetime,  # Job's UTC start time
    completed_at: Optional[datetime],  # Job's UTC end time (None if still running)
    max_lines: int,  # Max lines to return
) -> str:  # Sliced log content
    """Slice log content by a job's execution window.

    Worker logs are local-time naive; job timestamps are UTC. We convert
    the job's UTC times to local-time-naive for comparison. Continuation
    lines (no parseable timestamp) are associated with the most recent
    timestamped line — included if that timestamp was in the window.

    Best-effort: if `started_at` is None (job never ran) or no lines have
    parseable timestamps, returns the raw tail unchanged.
    """
    if started_at is None:
        return '\n'.join(raw.split('\n')[-max_lines:])

    start_naive = started_at.astimezone().replace(tzinfo=None)
    end_naive = (
        completed_at.astimezone().replace(tzinfo=None)
        if completed_at is not None else None
    )

    in_window = False
    selected: List[str] = []
    saw_timestamp = False
    for line in raw.split('\n'):
        ts = _parse_log_timestamp(line)
        if ts is not None:
            saw_timestamp = True
            if ts < start_naive:
                in_window = False
            elif end_naive is not None and ts > end_naive:
                in_window = False
            else:
                in_window = True
        if in_window:
            selected.append(line)

    # If no timestamps were parseable in the raw log, fall back to the raw tail
    # rather than returning empty (heuristic preservation of useful content).
    if not saw_timestamp:
        return '\n'.join(raw.split('\n')[-max_lines:])

    return '\n'.join(selected[-max_lines:])


def get_job_logs(
    self,
    job_id: str,  # Job to get logs for
    lines: int = 100  # Max lines to return
) -> str:  # Log content scoped to this job's execution window
    """Get logs for a job, scoped to its (started_at, completed_at) window.

    CR-6 Stage 3: replaces the legacy whole-plugin-log behavior. The
    substrate over-fetches the plugin log (lines * 5) and slices by the
    job's execution window — the job-monitor library's `--- Starting` marker
    heuristic in `_filter_current_session` becomes obsolete in cascade.

    Falls back gracefully when timestamps are unparseable or the job's
    window isn't known: returns the raw tail.
    """
    job = self._jobs.get(job_id)
    if not job:
        return ""

    # Over-fetch: continuation lines + lines outside the window get filtered,
    # so we need enough raw content to populate `lines` results post-slice.
    raw = self._deps.get_plugin_logs(job.plugin_instance_id, lines=lines * 5)

    if job.started_at is None:
        # Job hasn't run yet — no useful slice. Return raw tail.
        return '\n'.join(raw.split('\n')[-lines:])

    return _slice_log_by_job_window(raw, job.started_at, job.completed_at, lines)

JobQueue.get_job = get_job
JobQueue.wait_for_job = wait_for_job
JobQueue.get_pending = get_pending
JobQueue.get_running = get_running
JobQueue.get_history = get_history
JobQueue.get_stats = get_stats
JobQueue.get_job_logs = get_job_logs

# %% ../../nbs/core/queue.ipynb #b4fe9d38
def _subscriber_keys_for(event: JobEvent) -> List[str]:
    """Return the subscriber keys an event should fan out to (CR-6).

    Every event reaches "all" subscribers + the per-job subscribers.
    Sequence-tagged events additionally reach per-sequence subscribers.
    """
    keys = ["all", f"job:{event.job_id}"]
    if event.sequence_id is not None:
        keys.append(f"seq:{event.sequence_id}")
    return keys


def _publish_event(
    self,
    event: JobEvent,  # Event to fan out
) -> None:
    """Fan out an event to all matching subscribers (CR-6).

    Slow subscribers backpressure themselves via `asyncio.QueueFull` drop —
    publisher never blocks. Each subscriber tracks `dropped_count` so
    operators / future telemetry can surface backpressure visibility.
    """
    for key in _subscriber_keys_for(event):
        # `self._subscribers` is a defaultdict but we use `.get` to avoid
        # accidentally creating empty lists for unused keys (which would
        # otherwise accumulate).
        for sub in self._subscribers.get(key, []):
            try:
                sub.queue.put_nowait(event)
            except asyncio.QueueFull:
                sub.dropped_count += 1
                self.logger.warning(
                    f"Subscriber to '{key}' dropped event "
                    f"(dropped_count={sub.dropped_count}); subscriber is "
                    f"falling behind."
                )


async def _subscribe(
    self,
    key: str,  # Subscriber key ("all" | "job:<id>" | "seq:<id>")
) -> AsyncIterator[JobEvent]:
    """Internal: register a subscription; yield events until the consumer
    exits the async generator.

    Cleanup runs in `finally` so the subscriber is unregistered even if the
    consumer raises or is cancelled. Empty key lists are deleted to avoid
    memory accumulation across many short-lived subscriptions.
    """
    sub = _Subscription(queue=asyncio.Queue(maxsize=self.SUBSCRIBER_QUEUE_MAXSIZE))
    self._subscribers[key].append(sub)
    try:
        while True:
            event = await sub.queue.get()
            yield event
    finally:
        try:
            self._subscribers[key].remove(sub)
            if not self._subscribers[key]:
                del self._subscribers[key]
        except (ValueError, KeyError):
            # Already removed (e.g., queue stop drained); idempotent cleanup.
            pass


async def events(
    self,
    job_id: str,  # Filter to events for this job
) -> AsyncIterator[JobEvent]:
    """Subscribe to events for a single job (async generator).

    Yields events as they fire. Multiple concurrent subscribers to the same
    job_id each get their own independent stream — useful for multi-tab UIs.
    """
    async for evt in self._subscribe(f"job:{job_id}"):
        yield evt


async def events_for_sequence(
    self,
    sequence_id: str,  # Filter to events tagged with this sequence
) -> AsyncIterator[JobEvent]:
    """Subscribe to events for all jobs in a sequence (async generator).

    Yields the unified per-sequence narrative: member-job lifecycle events
    interleaved with `SEQUENCE_ADVANCED` aggregate signals (wired in Stage 2).
    """
    async for evt in self._subscribe(f"seq:{sequence_id}"):
        yield evt


async def all_events(self) -> AsyncIterator[JobEvent]:
    """Subscribe to all events (firehose; async generator).

    Useful for global dashboards, audit logs, and telemetry sinks that need
    the complete event stream rather than a filtered view.
    """
    async for evt in self._subscribe("all"):
        yield evt


JobQueue._publish_event = _publish_event
JobQueue._subscribe = _subscribe
JobQueue.events = events
JobQueue.events_for_sequence = events_for_sequence
JobQueue.all_events = all_events

# %% ../../nbs/core/queue.ipynb #9eb0cb97
async def submit_sequence(
    self,
    steps: List[SequenceStep],  # Sequence steps to run in order
    priority: int = 0,          # Sequence-level priority (per-step override possible)
    fail_fast: bool = True,     # Halt on first failure (audit-locked default)
) -> str:  # sequence_id
    """Submit a multi-step job sequence (CR-6 Stage 2).

    Validates all step plugins upfront (`PluginDisabledError` if any are
    disabled) so operators get an immediate failure signal rather than
    discovering the problem mid-sequence. The first member-job is tagged
    with sequence fields BEFORE enqueue, so its first STATE_TRANSITION
    already routes through sequence-tagged subscribers.

    Returns the sequence_id; consumers subscribe via
    `queue.events_for_sequence(sequence_id)` or query state via
    `queue.get_sequence(sequence_id)`.
    """
    from cjm_plugin_system.core.errors import PluginDisabledError

    # Empty sequence — return a completed-at-submit sequence_id so the API
    # is total. Edge case; consumers can avoid by not submitting empty lists.
    if not steps:
        seq_id = str(uuid.uuid4())
        seq = JobSequence(
            id=seq_id, steps=[], fail_fast=fail_fast, priority=priority,
            status=JobStatus.completed,
            completed_at=datetime.now(timezone.utc),
        )
        self._sequences[seq_id] = seq
        self.logger.info(f"Submitted empty sequence {seq_id[:8]} (immediately completed)")
        return seq_id

    # Validate all steps upfront. Fail with the first offending step's
    # plugin name; operator can correlate via the step index in the log.
    for i, step in enumerate(steps):
        meta = self._deps.get_plugin_meta(step.plugin_instance_id)
        if meta is not None and not meta.enabled:
            self.logger.error(
                f"Sequence submission rejected: step {i} targets disabled "
                f"plugin {step.plugin_instance_id}"
            )
            raise PluginDisabledError(step.plugin_instance_id)

    seq_id = str(uuid.uuid4())
    seq = JobSequence(
        id=seq_id, steps=list(steps), fail_fast=fail_fast, priority=priority,
        status=JobStatus.running,
    )
    self._sequences[seq_id] = seq

    # Build + enqueue first member with sequence fields populated.
    first = steps[0]
    first_job = Job(
        id=str(uuid.uuid4()),
        plugin_instance_id=first.plugin_instance_id,
        args=first.args,
        kwargs=dict(first.kwargs),
        priority=first.priority if first.priority else priority,
        sequence_id=seq_id,
        sequence_index=0,
    )
    seq.current_job_id = first_job.id
    await self._enqueue_job(first_job)

    self.logger.info(
        f"Submitted sequence {seq_id[:8]} ({len(steps)} steps, "
        f"fail_fast={fail_fast}, priority={priority})"
    )
    return seq_id


async def submit_uniform_sequence(
    self,
    plugin_instance_id: str,  # Plugin every step targets
    args_list: List[Tuple[Any, ...]],  # Per-step positional args
    kwargs_list: Optional[List[Dict[str, Any]]] = None,  # Per-step keyword args (default: empty)
    priority: int = 0,        # Sequence-level priority
    fail_fast: bool = True,   # Halt on first failure (audit-locked default)
) -> str:  # sequence_id
    """Submit a sequence where every step targets the same plugin (CR-6 Stage 2).

    Sugar over `submit_sequence` for the common "same plugin, many arg sets"
    case — multi-source transcription / batch processing / parameter sweeps.
    """
    if kwargs_list is None:
        kwargs_list = [{} for _ in args_list]
    if len(args_list) != len(kwargs_list):
        raise ValueError(
            f"args_list and kwargs_list must have same length "
            f"({len(args_list)} vs {len(kwargs_list)})"
        )

    steps = [
        SequenceStep(
            plugin_instance_id=plugin_instance_id,
            args=tuple(args),
            kwargs=dict(kwargs),
        )
        for args, kwargs in zip(args_list, kwargs_list)
    ]
    return await self.submit_sequence(steps, priority=priority, fail_fast=fail_fast)


async def cancel_sequence(
    self,
    sequence_id: str  # Sequence to cancel
) -> bool:  # True if cancellation was recorded
    """Cancel an in-flight sequence (CR-6 Stage 2).

    Marks the sequence as cancelled (no further advancement) and cancels
    the current member job. Returns False if the sequence is unknown or
    already terminal; True if cancellation was recorded.

    Sets `seq.status = JobStatus.cancelled` BEFORE issuing the member-job
    cancel. This prevents a race where the member completes between the
    intent record and the cancel call — `_advance_sequence` checks
    `seq.status == cancelled` first and halts regardless of member outcome.
    """
    seq = self._sequences.get(sequence_id)
    if seq is None or seq.status != JobStatus.running:
        return False

    seq.status = JobStatus.cancelled
    self.logger.info(f"Cancellation requested for sequence {sequence_id[:8]}")

    current_id = seq.current_job_id
    if current_id and current_id in self._jobs:
        current_job = self._jobs[current_id]
        if current_job.status in (JobStatus.pending, JobStatus.running):
            await self.cancel(current_id)
            # `cancel()` runs _advance_sequence after release; that path
            # sees status==cancelled and finalizes the sequence (sets
            # completed_at).
            return True

    # No active member to cancel (between-steps state) — finalize now.
    seq.completed_at = datetime.now(timezone.utc)
    seq.current_job_id = None
    return True


def get_sequence(
    self,
    sequence_id: str  # Sequence to retrieve
) -> Optional[JobSequence]:  # JobSequence or None
    """Get a job sequence by ID (read-only inspection)."""
    return self._sequences.get(sequence_id)


async def _advance_sequence(
    self,
    completed_job: Job  # The member job that just reached terminal status
) -> None:
    """Advance the sequence after a member job completes (CR-6 Stage 2).

    Records the member's StepResult, decides whether to advance / halt /
    finalize, and submits the next member if applicable. Always called
    OUTSIDE the queue's main lock — may take it via `_enqueue_job`.
    """
    seq = self._sequences.get(completed_job.sequence_id)
    if seq is None:
        # Sequence already cleaned up; nothing to do.
        return

    # Record this member's outcome. completed/failed/cancelled are the only
    # terminal statuses this path sees.
    member_status = completed_job.status
    step_result = StepResult(
        job_id=completed_job.id,
        success=(member_status == JobStatus.completed),
        result=completed_job.result if member_status == JobStatus.completed else None,
        error=completed_job.error,
    )
    seq.results.append(step_result)

    # 1. Sequence-level cancel intent (cancel_sequence was called):
    #    halt regardless of member-job outcome.
    # 2. Member was cancelled (direct or via cancel_sequence cascade):
    #    halt the sequence (cancellation always halts).
    # 3. Member failed + fail_fast=True: halt with failed status.
    # 4. Member failed + fail_fast=False: continue to next step.
    # 5. Member succeeded: continue to next step.
    if seq.status == JobStatus.cancelled or member_status == JobStatus.cancelled:
        seq.status = JobStatus.cancelled
        seq.completed_at = datetime.now(timezone.utc)
        seq.current_job_id = None
        self.logger.info(
            f"Sequence {seq.id[:8]} cancelled (member {completed_job.id[:8]} "
            f"status={member_status.value})"
        )
        return

    if member_status == JobStatus.failed and seq.fail_fast:
        seq.status = JobStatus.failed
        seq.completed_at = datetime.now(timezone.utc)
        seq.current_job_id = None
        self.logger.info(
            f"Sequence {seq.id[:8]} failed (fail_fast, step {seq.current_index})"
        )
        return

    # Advance to the next step
    seq.current_index += 1
    if seq.current_index >= len(seq.steps):
        # All steps attempted (may include failures if fail_fast=False)
        any_failures = any(not r.success for r in seq.results)
        seq.status = JobStatus.failed if (any_failures and seq.fail_fast) else JobStatus.completed
        # NOTE: fail_fast=False sequences land as `completed` even with failed
        # members; the results list captures the per-step outcomes. This
        # matches "best-effort" semantics — "we attempted everything".
        seq.completed_at = datetime.now(timezone.utc)
        seq.current_job_id = None
        self.logger.info(
            f"Sequence {seq.id[:8]} completed ({len(seq.steps)} steps, "
            f"{sum(1 for r in seq.results if r.success)} succeeded)"
        )
        return

    # Submit next member
    next_step = seq.steps[seq.current_index]
    next_job = Job(
        id=str(uuid.uuid4()),
        plugin_instance_id=next_step.plugin_instance_id,
        args=next_step.args,
        kwargs=dict(next_step.kwargs),
        priority=next_step.priority if next_step.priority else seq.priority,
        sequence_id=seq.id,
        sequence_index=seq.current_index,
    )
    seq.current_job_id = next_job.id
    await self._enqueue_job(next_job)

    # Emit SEQUENCE_ADVANCED so sequence subscribers see the transition
    # between member jobs as a discrete signal (in addition to the next
    # member's STATE_TRANSITION pending → running fire when it starts).
    self._publish_event(JobEvent(
        type=JobEventType.SEQUENCE_ADVANCED,
        job_id=next_job.id,
        plugin_instance_id=next_job.plugin_instance_id,
        sequence_id=seq.id,
        sequence_index=seq.current_index,
        payload={
            "prior_job_id": completed_job.id,
            "prior_step_index": seq.current_index - 1,
            "prior_success": step_result.success,
        },
    ))


JobQueue.submit_sequence = submit_sequence
JobQueue.submit_uniform_sequence = submit_uniform_sequence
JobQueue.cancel_sequence = cancel_sequence
JobQueue.get_sequence = get_sequence
JobQueue._advance_sequence = _advance_sequence

# %% ../../nbs/core/queue.ipynb #ee34e330
def _sample_resource_snapshot(
    self,
    job: Job  # Job to sample resources for
) -> Optional[ResourceSnapshot]:
    """Sample worker + sysmon stats for a job (CR-6 Stage 3 internal helper).

    Returns None if the worker proxy doesn't support `get_stats` or the call
    fails — substrate can't fabricate a snapshot. Sysmon enrichment is
    best-effort: if the named plugin isn't loaded / errors / lacks the CR-3
    typed methods, GPU fields stay None and the worker-only snapshot is
    returned.
    """
    proxy = self._deps.get_plugin(job.plugin_instance_id)
    if not proxy or not hasattr(proxy, 'get_stats'):
        return None

    try:
        stats = proxy.get_stats()
    except Exception:
        return None

    snapshot = ResourceSnapshot(
        timestamp=datetime.now(timezone.utc),
        worker_pid=stats.get('pid', 0),
        cpu_percent=stats.get('cpu_percent', 0.0),
        memory_rss_mb=stats.get('memory_rss_mb', 0.0),
    )

    # Best-effort sysmon enrichment via CR-3 typed methods.
    if self._sysmon_name:
        sysmon = self._deps.get_plugin(self._sysmon_name)
        if sysmon is not None:
            # Per-PID GPU usage via list_processes()
            try:
                processes = sysmon.list_processes() if hasattr(sysmon, 'list_processes') else None
                if processes:
                    for proc in processes:
                        # proxy returns dicts; handle both dict + dataclass forms
                        proc_pid = proc.get('pid') if isinstance(proc, dict) else getattr(proc, 'pid', None)
                        if proc_pid == snapshot.worker_pid:
                            snapshot.gpu_index = (
                                proc.get('gpu_index') if isinstance(proc, dict)
                                else getattr(proc, 'gpu_index', None)
                            )
                            snapshot.gpu_memory_mb = (
                                proc.get('gpu_memory_mb') if isinstance(proc, dict)
                                else getattr(proc, 'gpu_memory_mb', None)
                            )
                            break
            except Exception:
                pass  # Sysmon failure shouldn't break the snapshot

            # Global GPU stats via get_system_status()
            try:
                sys_stats = sysmon.get_system_status() if hasattr(sysmon, 'get_system_status') else None
                if sys_stats is not None:
                    snapshot.gpu_type = (
                        sys_stats.get('gpu_type') if isinstance(sys_stats, dict)
                        else getattr(sys_stats, 'gpu_type', None)
                    )
                    snapshot.gpu_total_mb = (
                        sys_stats.get('gpu_total_memory_mb') if isinstance(sys_stats, dict)
                        else getattr(sys_stats, 'gpu_total_memory_mb', None)
                    )
                    snapshot.gpu_load_percent = (
                        sys_stats.get('gpu_load_percent') if isinstance(sys_stats, dict)
                        else getattr(sys_stats, 'gpu_load_percent', None)
                    )
            except Exception:
                pass

    return snapshot


def get_resource_snapshot(
    self,
    job_id: str  # Job to sample resources for
) -> Optional[ResourceSnapshot]:
    """Get a point-in-time resource snapshot for a job (CR-6 Stage 3).

    Returns None if the job is unknown or the worker proxy doesn't expose
    `get_stats`. Composes worker stats with sysmon GPU stats when the queue
    is configured with a `sysmon_plugin_name`.
    """
    job = self._jobs.get(job_id)
    if not job:
        return None
    return self._sample_resource_snapshot(job)


JobQueue._sample_resource_snapshot = _sample_resource_snapshot
JobQueue.get_resource_snapshot = get_resource_snapshot

# %% ../../nbs/core/queue.ipynb #lifecycle
async def start(self) -> None:
    """Start the queue processor.

    CR-6 Stage 4: installs the substrate-side retry observer on `_deps`
    (typically a PluginManager). When CR-7's reactive-retry path fires for
    a running job, the observer updates `Job.retry_count` and publishes a
    RETRY_STARTED event tagged with the in-flight job. Previous observer
    value (if any) is saved + restored in stop() for cooperative coexistence.
    """
    if self._running_flag:
        return

    # CR-6 Stage 4: install retry observer. Uses setattr defensively so
    # non-PluginManager deps implementations don't fail — they just accept
    # an unused attribute. PluginManager's execute paths look up
    # `getattr(self, '_on_retry', None)` so the hook only fires when both
    # sides are wired.
    self._prev_deps_on_retry = getattr(self._deps, '_on_retry', None)
    try:
        self._deps._on_retry = self._on_manager_retry
    except (AttributeError, TypeError):
        # Some deps implementations may not allow setattr (frozen dataclass,
        # __slots__, etc.); RETRY_STARTED won't fire for those but the rest
        # of the queue works.
        self._prev_deps_on_retry = None

    self._running_flag = True
    self._processor_task = asyncio.create_task(self._process_loop())
    self.logger.info("Job queue started")

async def stop(self) -> None:
    """Stop the queue processor gracefully.

    CR-6 Stage 4: restores the previous `_on_retry` observer on deps to
    leave the manager in the state we found it (cooperative with other
    queue instances, tests, etc.).
    """
    self._running_flag = False
    self._job_available.set()  # Wake up the processor

    if self._processor_task:
        try:
            await asyncio.wait_for(self._processor_task, timeout=5.0)
        except asyncio.TimeoutError:
            self._processor_task.cancel()
        self._processor_task = None

    # Restore previous retry observer (if any). Best-effort — same setattr
    # caveats as start().
    try:
        if self._prev_deps_on_retry is None:
            # Was unset before we touched it; clean up our attribute.
            if hasattr(self._deps, '_on_retry'):
                try:
                    del self._deps._on_retry
                except (AttributeError, TypeError):
                    self._deps._on_retry = None
        else:
            self._deps._on_retry = self._prev_deps_on_retry
    except (AttributeError, TypeError):
        pass

    self.logger.info("Job queue stopped")

def _on_manager_retry(
    self,
    instance_id: str,  # Plugin instance whose execute is retrying
    attempt: int,      # 1-based retry number (PluginManager's loop var; first retry is 1)
    exception: BaseException,  # The PluginResourceError that triggered the retry
) -> None:
    """Substrate-side retry observer (CR-6 Stage 4).

    Invoked synchronously by PluginManager's CR-7 retry loop just before
    each retry attempt. Updates `Job.retry_count` on the matching in-flight
    job + emits RETRY_STARTED. Best-effort: synchronous callback; emission
    failure shouldn't propagate back into the retry loop.

    `attempt` semantics: PluginManager's loop iterates
    `for attempt in range(max_retries + 1)`. The first iteration
    (`attempt=0`) is the original try and never invokes this callback —
    it only fires when `last_resource_error is not None`, which means
    the prior iteration raised. So the value PASSED here is already the
    1-based retry number: `attempt=1` is the first retry, `attempt=2` is
    the second retry, etc.

    Match logic: find the running job whose plugin_instance_id matches.
    Multi-instance / concurrent execution complicates this — the single
    `self._running` field tracks one job at a time, matching the queue's
    current single-worker-execution model. Future concurrent-execution
    support would extend the match strategy.
    """
    running = self._running
    if running is None or running.plugin_instance_id != instance_id:
        # No matching in-flight job (e.g. queue stopped or different instance).
        return

    running.retry_count = attempt
    self._publish_event(JobEvent(
        type=JobEventType.RETRY_STARTED,
        job_id=running.id,
        plugin_instance_id=running.plugin_instance_id,
        sequence_id=running.sequence_id,
        sequence_index=running.sequence_index,
        payload={
            "attempt": attempt,  # 1-based retry number (1=first retry, etc.)
            "exception_repr": repr(exception),
            "exception_category": getattr(exception, 'category', 'resource'),
        },
    ))

JobQueue.start = start
JobQueue.stop = stop
JobQueue._on_manager_retry = _on_manager_retry

# %% ../../nbs/core/queue.ipynb #internal
def _move_to_history(self, job: Job) -> None:
    """Move a job to history, maintaining max_history limit."""
    self._history.append(job)
    if len(self._history) > self.max_history:
        old_job = self._history.pop(0)
        # SG-13: set the evicted event before popping so any in-flight waiter
        # still holding the reference resolves immediately. Idempotent if the
        # event was already set by `_signal_job_completed`; protective if not.
        evicted = self._job_completed_events.pop(old_job.id, None)
        if evicted is not None:
            evicted.set()

def _signal_job_completed(self, job_id: str) -> None:
    """Signal that a job has completed."""
    event = self._job_completed_events.get(job_id)
    if event:
        event.set()

def _emit_state_transition(
    self,
    job: Job,
    prev_status: JobStatus,
) -> None:
    """Emit a STATE_TRANSITION event for `job`'s most recent status change.

    Centralized so every transition site (start, completed, failed, cancelled,
    or future cancel-phase-driven transitions) carries identical tag context.
    """
    self._publish_event(JobEvent(
        type=JobEventType.STATE_TRANSITION,
        job_id=job.id,
        plugin_instance_id=job.plugin_instance_id,
        sequence_id=job.sequence_id,
        sequence_index=job.sequence_index,
        payload={"from": prev_status.value, "to": job.status.value},
    ))

def _emit_cancel_phase(
    self,
    job: Job,
    new_phase: CancelPhase,
) -> None:
    """Emit a CANCEL_PHASE_CHANGED event (CR-6 Stage 4).

    Updates `job.cancel_phase` to the new value and publishes an event with
    the prior phase + new phase in the payload. Centralized so every phase
    transition site in `_execute_with_cancellation` produces identically-shaped
    events.
    """
    prev_phase = job.cancel_phase
    job.cancel_phase = new_phase
    self._publish_event(JobEvent(
        type=JobEventType.CANCEL_PHASE_CHANGED,
        job_id=job.id,
        plugin_instance_id=job.plugin_instance_id,
        sequence_id=job.sequence_id,
        sequence_index=job.sequence_index,
        payload={
            "from": prev_phase.value if prev_phase is not None else None,
            "to": new_phase.value,
        },
    ))

def _emit_block_reason(
    self,
    job: Job,
    new_reason: Optional[str],
) -> None:
    """Emit a BLOCK_REASON_CHANGED event (CR-6 Stage 4 — reserved).

    Updates `job.block_reason` and publishes an event with the prior + new
    reason. Stage 4 ships this helper for future scheduler-integration use;
    the queue's current scheduling logic doesn't surface block reasons, so
    the helper is reserved for the eventual scheduler-coordination wiring.
    """
    prev_reason = job.block_reason
    if prev_reason == new_reason:
        return  # No-op: avoid event spam on repeated no-change calls
    job.block_reason = new_reason
    self._publish_event(JobEvent(
        type=JobEventType.BLOCK_REASON_CHANGED,
        job_id=job.id,
        plugin_instance_id=job.plugin_instance_id,
        sequence_id=job.sequence_id,
        sequence_index=job.sequence_index,
        payload={"from": prev_reason, "to": new_reason},
    ))

async def _process_loop(self) -> None:
    """Main processing loop."""
    while self._running_flag:
        # Wait for jobs
        await self._job_available.wait()

        if not self._running_flag:
            break

        async with self._lock:
            if not self._pending:
                self._job_available.clear()
                continue

            job = heapq.heappop(self._pending)
            if not self._pending:
                self._job_available.clear()

        # Process the job
        await self._execute_job(job)

async def _execute_job(self, job: Job) -> None:
    """Execute a single job."""
    self.logger.info(f"Starting job {job.id[:8]} ({job.plugin_instance_id})")

    # Mark as running + emit transition pending → running
    prev_status = job.status
    job.status = JobStatus.running
    job.started_at = datetime.now(timezone.utc)
    self._running = job
    self._emit_state_transition(job, prev_status)

    try:
        # Get the plugin proxy
        plugin = self._deps.get_plugin(job.plugin_instance_id)
        if not plugin:
            raise ValueError(f"Plugin not loaded: {job.plugin_instance_id}")

        # Start progress polling task
        progress_task = asyncio.create_task(
            self._poll_progress(job, plugin)
        )

        # Execute with cancellation support
        try:
            result = await self._execute_with_cancellation(job, plugin)

            if job.id in self._cancel_requested:
                prev = job.status
                job.status = JobStatus.cancelled
                self._cancel_requested.discard(job.id)
                self._emit_state_transition(job, prev)
            else:
                prev = job.status
                job.status = JobStatus.completed
                job.result = result
                self._emit_state_transition(job, prev)

        except asyncio.CancelledError:
            prev = job.status
            job.status = JobStatus.cancelled
            self._emit_state_transition(job, prev)
        except Exception as e:
            prev = job.status
            job.status = JobStatus.failed
            # CR-5: typed JobError carries category + retriable + structured
            # side-channels for PluginError subclasses. Stage 1 records the
            # bare-exception mapping; the CR-7 reactive-retry loop and Stage 4
            # cancel-phase wiring will populate further fields.
            job.error = map_bare_exception_to_job_error(
                e,
                plugin_instance_id=job.plugin_instance_id,
            )
            self.logger.error(f"Job {job.id[:8]} failed: {e}")
            self._emit_state_transition(job, prev)
        finally:
            progress_task.cancel()
            try:
                await progress_task
            except asyncio.CancelledError:
                pass

    except Exception as e:
        prev = job.status
        job.status = JobStatus.failed
        job.error = map_bare_exception_to_job_error(
            e,
            plugin_instance_id=job.plugin_instance_id,
        )
        self.logger.error(f"Job {job.id[:8]} failed: {e}")
        self._emit_state_transition(job, prev)

    # Finalize
    job.completed_at = datetime.now(timezone.utc)
    job.progress = 1.0 if job.status == JobStatus.completed else job.progress
    self._running = None

    async with self._lock:
        # SG-13: signal before moving to history so this job's event is set
        # before any eviction could pop it from the dict.
        self._signal_job_completed(job.id)
        self._move_to_history(job)

    # CR-6 Stage 2: advance sequence after lock release. _advance_sequence
    # may take the lock again via _enqueue_job (next member); asyncio.Lock
    # is not re-entrant, so this must happen outside the lock block above.
    if job.sequence_id is not None:
        await self._advance_sequence(job)

    self.logger.info(f"Job {job.id[:8]} {job.status.value}")

async def _execute_with_cancellation(
    self,
    job: Job,
    plugin: Any
) -> Any:
    """Execute job with cancellation monitoring.

    CR-6 Stage 4 wires CANCEL_PHASE_CHANGED events for the substrate's
    cooperative → force → reloading → completed state machine.

    Cooperative-success path (plugin acknowledges cancel within timeout):
        COOPERATIVE → COMPLETED
    Force-kill path (cooperative timeout):
        COOPERATIVE → FORCE → RELOADING → COMPLETED
    """
    # Start execution
    exec_task = asyncio.create_task(
        self._deps.execute_plugin_async(job.plugin_instance_id, *job.args, **job.kwargs)
    )

    # Monitor for cancellation
    while not exec_task.done():
        if job.id in self._cancel_requested:
            # PHASE: COOPERATIVE — cancel signal being sent, awaiting acknowledgement
            self._emit_cancel_phase(job, CancelPhase.COOPERATIVE)
            self.logger.info(f"Attempting cooperative cancel for {job.id[:8]}")

            if hasattr(plugin, 'cancel_async'):
                await plugin.cancel_async()
            elif hasattr(plugin, 'cancel'):
                plugin.cancel()

            # Wait briefly for cooperative cancellation
            try:
                result = await asyncio.wait_for(exec_task, timeout=self.cancel_timeout)
                # Plugin acknowledged + completed within timeout.
                self._emit_cancel_phase(job, CancelPhase.COMPLETED)
                return result
            except asyncio.TimeoutError:
                # PHASE: FORCE — cooperative timeout; force-terminating worker
                self._emit_cancel_phase(job, CancelPhase.FORCE)
                self.logger.warning(f"Force terminating plugin for job {job.id[:8]}")
                exec_task.cancel()

                # PHASE: RELOADING — worker reload in progress post-force-kill
                self._emit_cancel_phase(job, CancelPhase.RELOADING)
                self._deps.reload_plugin(job.plugin_instance_id)

                # PHASE: COMPLETED — cancellation fully resolved
                self._emit_cancel_phase(job, CancelPhase.COMPLETED)
                raise asyncio.CancelledError()

        await asyncio.sleep(0.1)

    return exec_task.result()

async def _poll_progress(
    self,
    job: Job,
    plugin: Any
) -> None:
    """Poll progress + sample resources from the plugin during execution.

    Emits PROGRESS_CHANGED events when progress or status_message changes
    from the previous poll (avoids spamming the bus between meaningful
    updates). CR-6 Stage 3: also emits RESOURCE_SNAPSHOT events every
    `resource_snapshot_cadence_polls` iterations; snapshot is also stored
    on `job.last_resource_snapshot` for synchronous inspection.
    """
    last_progress = job.progress
    last_message = job.status_message
    poll_count = 0
    while True:
        try:
            if hasattr(plugin, 'get_progress_async'):
                progress_info = await plugin.get_progress_async()
            elif hasattr(plugin, 'get_progress'):
                progress_info = plugin.get_progress()
            else:
                progress_info = None

            if progress_info is not None:
                new_progress = progress_info.get('progress', 0.0)
                new_message = progress_info.get('message', '')
                job.progress = new_progress
                job.status_message = new_message

                if new_progress != last_progress or new_message != last_message:
                    self._publish_event(JobEvent(
                        type=JobEventType.PROGRESS_CHANGED,
                        job_id=job.id,
                        plugin_instance_id=job.plugin_instance_id,
                        sequence_id=job.sequence_id,
                        sequence_index=job.sequence_index,
                        payload={"progress": new_progress, "status_message": new_message},
                    ))
                    last_progress = new_progress
                    last_message = new_message

            # CR-6 Stage 3: sample resources at cadence + emit RESOURCE_SNAPSHOT.
            poll_count += 1
            if poll_count % self.resource_snapshot_cadence_polls == 0:
                snapshot = self._sample_resource_snapshot(job)
                if snapshot is not None:
                    job.last_resource_snapshot = snapshot
                    self._publish_event(JobEvent(
                        type=JobEventType.RESOURCE_SNAPSHOT,
                        job_id=job.id,
                        plugin_instance_id=job.plugin_instance_id,
                        sequence_id=job.sequence_id,
                        sequence_index=job.sequence_index,
                        payload={"snapshot": asdict(snapshot)},
                    ))

            if progress_info is None and self.resource_snapshot_cadence_polls <= 1:
                # Pathological: no progress support AND every-poll snapshot
                # cadence — we'd spin forever without yielding. Defensive
                # break matches pre-Stage-3 behavior when no progress hook
                # exists.
                if not hasattr(plugin, 'get_stats'):
                    break

        except Exception:
            pass  # Ignore polling errors

        await asyncio.sleep(self.progress_poll_interval)

JobQueue._move_to_history = _move_to_history
JobQueue._signal_job_completed = _signal_job_completed
JobQueue._emit_state_transition = _emit_state_transition
JobQueue._emit_cancel_phase = _emit_cancel_phase
JobQueue._emit_block_reason = _emit_block_reason
JobQueue._process_loop = _process_loop
JobQueue._execute_job = _execute_job
JobQueue._execute_with_cancellation = _execute_with_cancellation
JobQueue._poll_progress = _poll_progress

# %% ../../nbs/core/queue.ipynb #0c35a476
def get_state(self) -> Dict[str, Any]:  # Queue state for UI (legacy shape)
    """Get the current queue state in the pre-CR-6 dict shape.

    REMOVE-AFTER-OVERHAUL: kept so existing UI consumers (notably
    `cjm-fasthtml-job-monitor`) continue to work until they migrate to the
    typed `get_pending` / `get_running` / `get_history` / `get_stats`
    accessors. Reads from the new accessors and reshapes:

    - Legacy keys (`plugin_name`, `created_at`) read from the renamed fields
      via the Job dataclass's backward-compat `@property` aliases.
    - Legacy `error` was a bare string; new is `JobError`. Shim returns
      `error.message` to preserve the string shape.
    - Legacy timestamps were unix floats; new are `datetime`. Shim returns
      `.timestamp()` to preserve float shape.
    """
    running = self.get_running()
    running_dict = None
    if running:
        running_dict = {
            "id": running.id,
            "plugin_name": running.plugin_instance_id,
            "status": running.status.value,
            "started_at": running.started_at.timestamp() if running.started_at else None,
            "progress": running.progress,
            "status_message": running.status_message,
        }

    pending_list = [
        {
            "id": j.id,
            "plugin_name": j.plugin_instance_id,
            "priority": j.priority,
            "position": i,
        }
        for i, j in enumerate(self.get_pending())
    ]

    history_list = [
        {
            "id": j.id,
            "plugin_name": j.plugin_instance_id,
            "status": j.status.value,
            "completed_at": j.completed_at.timestamp() if j.completed_at else None,
            "error": j.error.message if j.error else None,
        }
        for j in self.get_history(limit=20)
    ]

    stats = self.get_stats()
    return {
        "running": running_dict,
        "pending": pending_list,
        "history": history_list,
        "stats": {
            "total_pending": stats.total_pending,
            "total_completed": stats.total_completed,
            "total_failed": stats.total_failed,
            "total_cancelled": stats.total_cancelled,
        },
    }

JobQueue.get_state = get_state

# %% ../../nbs/core/queue.ipynb #e31875a2
# SG-15: curate __all__ to expose only the class + value symbols.
# The patched JobQueue methods (submit, cancel, wait_for_job, events,
# submit_sequence, cancel_sequence, get_resource_snapshot, etc.) remain
# accessible as JobQueue.method() — they're removed from the module's
# `from ... import *` surface because invoking them standalone fails
# (they expect `self`). nbdev's auto-`__all__` lists them as free names;
# this override runs after that assignment and wins by being last.
#
# CR-6 additions: JobEventType + CancelPhase + JobEvent + QueueStats +
# JobQueueDependencies (Stage 1) + SequenceStep + StepResult + JobSequence
# (Stage 2) + ResourceSnapshot (Stage 3) are first-class types that
# consumers import directly.
__all__ = [
    'JobStatus', 'JobEventType', 'CancelPhase',
    'Job', 'JobEvent', 'QueueStats',
    'SequenceStep', 'StepResult', 'JobSequence',
    'ResourceSnapshot',
    'JobQueueDependencies', 'JobQueue',
]
