"""Typed data transfer at the worker boundary — the zero-copy `FileBackedDTO`
protocol and (stage 2 of the post-pass-2 execution sequence) the typed
result envelope that carries task results across the worker HTTP/JSON
boundary, retiring the per-consumer `field_of` dict-or-object tolerance
helpers (pass-2 Thread 3; evidence E5/D10/C7).

Docs: https://cj-mills.github.io/cjm-plugin-systemcore/wire.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/wire.ipynb.

# %% auto #0
__all__ = ['WIRE_KIND_KEY', 'WIRE_DATA_KEY', 'FileBackedDTO', 'flat_from_dict', 'wire_type', 'wire_encode', 'wire_decode']

# %% ../../nbs/core/wire.ipynb #90702fd5
import dataclasses
import logging
from typing import Any, Callable, Dict, Protocol, runtime_checkable

_logger = logging.getLogger(__name__)

# %% ../../nbs/core/wire.ipynb #so9ttuo6zo
@runtime_checkable
class FileBackedDTO(Protocol):
    """Protocol for Data Transfer Objects that serialize to disk for zero-copy transfer."""
    
    def to_temp_file(self) -> str: # Absolute path to the temporary file
        """Save the data to a temporary file and return the absolute path."""
        ...

# %% ../../nbs/core/wire.ipynb #f9aa2f68
# Wire format constants + registries. kind -> class for decode;
# class -> kind (exact type) for encode.
WIRE_KIND_KEY = "__wire__"
WIRE_DATA_KEY = "data"

_WIRE_TYPES: Dict[str, type] = {}
_WIRE_KINDS: Dict[type, str] = {}

# %% ../../nbs/core/wire.ipynb #3e944b85
def flat_from_dict(
    cls,      # The wire DTO dataclass being reconstructed
    d: dict,  # The envelope's "data" payload
):            # An instance of `cls`
    """Default reconstruction for FLAT wire DTOs (no nested-DTO fields).

    Filters the payload to the dataclass's declared fields (unknown extras
    are dropped with a debug log — transport-terminus tolerance, see the
    envelope design note) and lets the constructor enforce required fields
    (a missing required field raises TypeError loudly). DTOs with nested
    DTO fields (e.g. a result carrying a list of typed items) must define
    their own `from_dict` classmethod; `@wire_type` only attaches this
    default when the class has none.
    """
    names = {f.name for f in dataclasses.fields(cls)}
    extras = set(d) - names
    if extras:
        _logger.debug("wire: dropping unknown keys %s for %s",
                      sorted(extras), cls.__name__)
    return cls(**{k: v for k, v in d.items() if k in names})

# %% ../../nbs/core/wire.ipynb #6e0c671e
def wire_type(
    kind: str  # Stable wire discriminator, e.g. "transcription.result"
) -> Callable[[type], type]:  # Class decorator
    """Register a dataclass as a typed wire DTO under `kind`.

    - The class must be a dataclass (encode falls back to
      `dataclasses.asdict` when it defines no `to_dict`).
    - If the class defines no `from_dict`, the flat default
      (`flat_from_dict`) is attached; nested DTOs define their own.
    - Re-registering the SAME class (module + qualname — notebook re-runs,
      module reloads) replaces the entry; a DIFFERENT class claiming an
      already-registered kind raises ValueError.
    """
    def decorator(cls: type) -> type:
        if not dataclasses.is_dataclass(cls):
            raise TypeError(f"@wire_type({kind!r}) requires a dataclass, got {cls!r}")
        existing = _WIRE_TYPES.get(kind)
        if existing is not None:
            same = (existing.__module__ == cls.__module__
                    and existing.__qualname__ == cls.__qualname__)
            if not same:
                raise ValueError(
                    f"wire kind {kind!r} already registered to "
                    f"{existing.__module__}.{existing.__qualname__}")
            _WIRE_KINDS.pop(existing, None)
        if getattr(cls, "from_dict", None) is None:
            cls.from_dict = classmethod(flat_from_dict)
        _WIRE_TYPES[kind] = cls
        _WIRE_KINDS[cls] = kind
        return cls
    return decorator

# %% ../../nbs/core/wire.ipynb #2629c0f3
def wire_encode(
    obj: Any  # A task result (any shape)
) -> Any:     # Tagged envelope dict for registered DTOs; `obj` unchanged otherwise
    """Wrap a registered wire DTO in its tagged envelope (worker side).

    Exact-type lookup: subclasses are NOT encoded under the parent's kind
    (they pass through unregistered, preserving today's behavior).
    Payload preference: the DTO's own `to_dict()` when defined, else
    `dataclasses.asdict` (recursive — nested dataclasses flatten).
    """
    kind = _WIRE_KINDS.get(type(obj))
    if kind is None:
        return obj
    to_dict = getattr(obj, "to_dict", None)
    data = to_dict() if callable(to_dict) else dataclasses.asdict(obj)
    return {WIRE_KIND_KEY: kind, WIRE_DATA_KEY: data}


# %% ../../nbs/core/wire.ipynb #ed8aea49
def wire_decode(
    obj: Any  # A JSON-decoded response body (any shape)
) -> Any:     # The typed DTO for known kinds; `obj` unchanged otherwise
    """Reconstruct a typed result from its tagged envelope (host side).

    Known kind -> the registered class's `from_dict` (strict: a missing
    required field raises). Unknown kind -> the dict passes through
    UNCHANGED with the envelope intact (tolerant degradation for hosts
    without the result's interface library). Untagged values pass through.
    """
    if not (isinstance(obj, dict) and WIRE_KIND_KEY in obj):
        return obj
    cls = _WIRE_TYPES.get(obj.get(WIRE_KIND_KEY))
    if cls is None:
        return obj
    return cls.from_dict(obj.get(WIRE_DATA_KEY) or {})
