"""Typed data transfer at the worker boundary — the zero-copy `FileBackedDTO`
protocol and (stage 2 of the post-pass-2 execution sequence) the typed
result envelope that carries task results across the worker HTTP/JSON
boundary, retiring the per-consumer `field_of` dict-or-object tolerance
helpers (pass-2 Thread 3; evidence E5/D10/C7).

Docs: https://cj-mills.github.io/cjm-plugin-systemcore/wire.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/wire.ipynb.

# %% auto #0
__all__ = ['FileBackedDTO']

# %% ../../nbs/core/wire.ipynb #c1b2db020591
from typing import Protocol, runtime_checkable

# %% ../../nbs/core/wire.ipynb #so9ttuo6zo
@runtime_checkable
class FileBackedDTO(Protocol):
    """Protocol for Data Transfer Objects that serialize to disk for zero-copy transfer."""
    
    def to_temp_file(self) -> str: # Absolute path to the temporary file
        """Save the data to a temporary file and return the absolute path."""
        ...
