"""FastAPI server that runs inside isolated plugin environments"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/worker.ipynb.

# %% auto #0
__all__ = ['EnhancedJSONEncoder', 'parent_monitor', 'create_app', 'run_worker']

# %% ../../nbs/core/worker.ipynb #exports
import argparse
import asyncio
import dataclasses
import importlib
import json
import os
import sys
import threading
import time
from typing import Any, Dict, Generator

import psutil
import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import StreamingResponse

from .platform import terminate_self

import logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    force=True
)

# %% ../../nbs/core/worker.ipynb #encoder
class EnhancedJSONEncoder(json.JSONEncoder):
    """JSON encoder that handles dataclasses and other common types."""
    
    def default(
        self,
        o: Any # Object to encode
    ) -> Any: # JSON-serializable representation
        """Convert non-serializable objects to serializable form."""
        if dataclasses.is_dataclass(o) and not isinstance(o, type):
            return dataclasses.asdict(o)
        return super().default(o)

# %% ../../nbs/core/worker.ipynb #watchdog
def parent_monitor(
    ppid: int # Parent process ID to monitor
) -> None:
    """Monitor parent process and terminate self if parent dies.
    
    This implements the "Suicide Pact" pattern: if the Host process dies,
    the Worker must terminate itself to prevent zombie processes.
    """
    try:
        while True:
            parent = psutil.Process(ppid)
            if parent.status() == psutil.STATUS_ZOMBIE:
                raise psutil.NoSuchProcess(ppid)
            time.sleep(1)
    except (psutil.NoSuchProcess, ProcessLookupError):
        print(f"[Worker {os.getpid()}] Parent {ppid} gone. Shutting down.")
        # Use cross-platform self-termination
        terminate_self()

# %% ../../nbs/core/worker.ipynb #app-factory
def create_app(
    module_name: str, # Python module path (e.g., "my_plugin.plugin")
    class_name: str   # Plugin class name (e.g., "WhisperPlugin")
) -> FastAPI: # Configured FastAPI application
    """Create FastAPI app that hosts the specified plugin."""
    app = FastAPI(title="Plugin Worker")
    plugin_instance = None

    # Dynamic Loading
    try:
        module = importlib.import_module(module_name)
        plugin_cls = getattr(module, class_name)
        plugin_instance = plugin_cls()
    except Exception as e:
        print(f"FATAL: Failed to load {module_name}:{class_name} - {e}")
        sys.exit(1)

    @app.get("/health")
    def health_check() -> Dict[str, Any]:
        """Health check endpoint."""
        return {
            "status": "running",
            "pid": os.getpid(),
            "name": getattr(plugin_instance, "name", "unknown"),
            "version": getattr(plugin_instance, "version", "unknown")
        }

    @app.get("/stats")
    def stats() -> Dict[str, Any]:
        """Return process tree resource usage."""
        proc = psutil.Process()
        
        # 1. Get Memory of Main Process
        total_rss = proc.memory_info().rss
        
        # 2. Get Memory of Children (Safe Loop)
        # recursive=True ensures we catch grandchildren
        for child in proc.children(recursive=True):
            try:
                # We must check if child still exists before asking for memory
                total_rss += child.memory_info().rss
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                # Process died or we don't have permission (rare for child), skip it
                pass

        return {
            "pid": os.getpid(),
            "cpu_percent": proc.cpu_percent(), # Note: aggregating CPU % is complex, main pid is usually enough proxy
            "memory_rss_mb": total_rss / 1024 / 1024
        }

    @app.post("/initialize")
    async def initialize(request: Request) -> Dict[str, str]:
        """Initialize or reconfigure the plugin."""
        try:
            config = await request.json()
            plugin_instance.initialize(config)
            return {"status": "ok"}
        except Exception as e:
            raise HTTPException(status_code=400, detail=str(e))

    @app.get("/config_schema")
    def get_config_schema() -> Dict[str, Any]:
        """Return JSON Schema for plugin configuration."""
        if hasattr(plugin_instance, 'get_config_schema'):
            return plugin_instance.get_config_schema()
        return {}

    @app.get("/config")
    def get_config() -> Dict[str, Any]:
        """Return current plugin configuration."""
        if hasattr(plugin_instance, 'get_current_config'):
            cfg = plugin_instance.get_current_config()
            # Ensure dataclasses are serialized
            return json.loads(json.dumps(cfg, cls=EnhancedJSONEncoder))
        return {}

    @app.post("/execute")
    async def execute(request: Request) -> Any:
        """Execute plugin's main functionality.
        
        Runs in a thread pool so the event loop stays free to serve
        concurrent requests (e.g., /progress polling during long operations).
        """
        data = await request.json()
        args = data.get("args", [])
        kwargs = data.get("kwargs", {})
        
        try:
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(
                None, lambda: plugin_instance.execute(*args, **kwargs)
            )
            # Serialize result (handles dataclasses)
            json_str = json.dumps(result, cls=EnhancedJSONEncoder)
            return json.loads(json_str)
        except Exception as e:
            import traceback
            traceback.print_exc()
            raise HTTPException(status_code=500, detail=str(e))

    @app.post("/execute_stream")
    async def execute_stream(request: Request) -> StreamingResponse:
        """Execute plugin with streaming response (NDJSON)."""
        data = await request.json()
        args = data.get("args", [])
        kwargs = data.get("kwargs", {})

        def iter_response() -> Generator[str, None, None]:
            try:
                if hasattr(plugin_instance, 'execute_stream'):
                    iterator = plugin_instance.execute_stream(*args, **kwargs)
                else:
                    # Fallback: wrap single result
                    iterator = [plugin_instance.execute(*args, **kwargs)]
                
                for chunk in iterator:
                    # Line-delimited JSON (NDJSON)
                    yield json.dumps(chunk, cls=EnhancedJSONEncoder) + "\n"
            except Exception as e:
                yield json.dumps({"error": str(e)}) + "\n"

        return StreamingResponse(iter_response(), media_type="application/x-ndjson")

    @app.post("/cancel")
    def cancel() -> Dict[str, str]:
        """Cancel any running execution."""
        if hasattr(plugin_instance, 'cancel'):
            try:
                plugin_instance.cancel()
                return {"status": "cancelled"}
            except Exception as e:
                return {"status": "error", "detail": str(e)}
        return {"status": "not_supported"}

    @app.get("/progress")
    def get_progress() -> Dict[str, Any]:
        """Get current execution progress."""
        return {
            "progress": getattr(plugin_instance, '_progress', 0.0),
            "message": getattr(plugin_instance, '_status_message', "")
        }

    @app.post("/on_disable")
    def on_disable() -> Dict[str, str]:
        """CR-2: forward the substrate's on_disable signal to the loaded plugin.
        
        Worker stays alive; plugin's on_disable() hook gets a chance to
        release heavy resources (GPU memory, model files, etc.). Default
        PluginInterface.on_disable() is a no-op so plugins that don't
        opt in see no behavior change.
        """
        if hasattr(plugin_instance, 'on_disable'):
            try:
                plugin_instance.on_disable()
                return {"status": "disabled"}
            except Exception as e:
                return {"status": "error", "detail": str(e)}
        return {"status": "not_supported"}

    @app.post("/on_enable")
    def on_enable() -> Dict[str, str]:
        """CR-2: forward the substrate's on_enable signal to the loaded plugin.
        
        Plugin can eagerly re-acquire heavy resources or rely on lazy
        re-acquisition via the next execute() call. Default
        PluginInterface.on_enable() is a no-op.
        """
        if hasattr(plugin_instance, 'on_enable'):
            try:
                plugin_instance.on_enable()
                return {"status": "enabled"}
            except Exception as e:
                return {"status": "error", "detail": str(e)}
        return {"status": "not_supported"}

    @app.post("/get_system_status")
    def get_system_status_endpoint() -> Dict[str, Any]:
        """CR-3: typed MonitorPlugin accessor. Returns SystemStats.to_dict().
        
        Status code taxonomy (intentional, per CR-3 review):
        - 404: plugin is not a MonitorPlugin (configuration error — don't mask).
              Substrate's `system_monitor` was wired to the wrong plugin.
        - 501: plugin is a MonitorPlugin but raised NotImplementedError from its
              get_system_status() default body (legacy monitor predating CR-3 that
              opted out). Proxy falls back to /execute("get_system_status").
        - 500: plugin's get_system_status() raised some other exception. Real
              failure; do not silently fall back.
        - 200: typed call succeeded; body is SystemStats.to_dict().
        """
        if not hasattr(plugin_instance, 'get_system_status'):
            raise HTTPException(
                status_code=404,
                detail=(
                    f"Plugin {getattr(plugin_instance, 'name', class_name)!r} "
                    f"is not a MonitorPlugin (no get_system_status method)."
                ),
            )
        try:
            stats = plugin_instance.get_system_status()
        except NotImplementedError as exc:
            raise HTTPException(status_code=501, detail=str(exc) or "get_system_status not implemented")
        # Serialize via EnhancedJSONEncoder so SystemStats dataclass flattens
        # to its plain dict (and tolerates dict returns from non-typed monitors).
        if hasattr(stats, 'to_dict'):
            return stats.to_dict()
        return json.loads(json.dumps(stats, cls=EnhancedJSONEncoder))

    @app.post("/list_processes")
    def list_processes_endpoint() -> Any:
        """CR-3: typed MonitorPlugin accessor. Returns list of ProcessStats.to_dict().
        
        Same 404/501/500/200 taxonomy as /get_system_status. MonitorPlugin's
        default list_processes() returns `[]`, so non-implementing monitors
        return 200 with an empty list rather than 501.
        """
        if not hasattr(plugin_instance, 'list_processes'):
            raise HTTPException(
                status_code=404,
                detail=(
                    f"Plugin {getattr(plugin_instance, 'name', class_name)!r} "
                    f"is not a MonitorPlugin (no list_processes method)."
                ),
            )
        try:
            procs = plugin_instance.list_processes()
        except NotImplementedError as exc:
            raise HTTPException(status_code=501, detail=str(exc) or "list_processes not implemented")
        # Each ProcessStats has .to_dict(); EnhancedJSONEncoder handles either
        # dataclass instances or pre-converted dicts uniformly.
        return json.loads(json.dumps(procs, cls=EnhancedJSONEncoder))

    @app.post("/cleanup")
    def cleanup() -> Dict[str, str]:
        """Clean up plugin resources."""
        if hasattr(plugin_instance, 'cleanup'):
            plugin_instance.cleanup()
        return {"status": "cleaned"}

    return app

# %% ../../nbs/core/worker.ipynb #main-block
def run_worker() -> None:
    """CLI entry point for running the worker."""
    parser = argparse.ArgumentParser(description="Universal Plugin Worker")
    parser.add_argument("--module", required=True, help="Plugin module path")
    parser.add_argument("--class", dest="class_name", required=True, help="Plugin class name")
    # SG-4: parent-bound listening-socket FD inheritance closes the
    # bind-then-close-then-reopen TOCTOU race. --fd is preferred on Unix;
    # --port stays as the Windows fallback (pass_fds is Unix-only) and as a
    # diagnostic escape hatch when invoking the worker directly.
    parser.add_argument("--fd", type=int, required=False, default=None,
                        help="Inherited listening-socket file descriptor (Unix; preferred)")
    parser.add_argument("--port", type=int, required=False, default=None,
                        help="Port to bind (used when --fd is not provided)")
    parser.add_argument("--ppid", type=int, required=False, help="Parent PID to monitor")
    args = parser.parse_args()

    if args.fd is None and args.port is None:
        parser.error("one of --fd or --port is required")

    # Start watchdog if parent PID provided
    if args.ppid:
        watchdog = threading.Thread(
            target=parent_monitor,
            args=(args.ppid,),
            daemon=True
        )
        watchdog.start()

    app = create_app(args.module, args.class_name)
    if args.fd is not None:
        uvicorn.run(app, fd=args.fd, log_level="warning")
    else:
        uvicorn.run(app, host="127.0.0.1", port=args.port, log_level="warning")

# %% ../../nbs/core/worker.ipynb #module-main
#| eval: false
import sys

if __name__ == "__main__" and "ipykernel" not in sys.modules:
    run_worker()
