"""FastAPI server that runs inside isolated plugin environments

Docs: https://cj-mills.github.io/cjm-plugin-systemcore/worker.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/worker.ipynb.

# %% auto #0
__all__ = ['EnhancedJSONEncoder', 'parent_monitor', 'create_app', 'run_worker']

# %% ../../nbs/core/worker.ipynb #exports
import argparse
import asyncio
import dataclasses
import importlib
import json
import os
import sys
import threading
import time
from datetime import datetime
from typing import Any, Dict, Generator

import psutil
import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import StreamingResponse

from .errors import PluginCancelledError, map_bare_exception_to_job_error
from .platform import terminate_self

import logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    force=True
)

# %% ../../nbs/core/worker.ipynb #encoder
class EnhancedJSONEncoder(json.JSONEncoder):
    """JSON encoder that handles dataclasses and other common types.
    
    SG-52: datetime support added so JobError.occurred_at serializes cleanly
    when emitted via the typed `_job_error` terminal chunk in /execute_stream.
    """
    
    def default(
        self,
        o: Any # Object to encode
    ) -> Any: # JSON-serializable representation
        """Convert non-serializable objects to serializable form."""
        if dataclasses.is_dataclass(o) and not isinstance(o, type):
            return dataclasses.asdict(o)
        if isinstance(o, datetime):
            return o.isoformat()
        return super().default(o)

# %% ../../nbs/core/worker.ipynb #watchdog
def parent_monitor(
    ppid: int # Parent process ID to monitor
) -> None:
    """Monitor parent process and terminate self if parent dies.
    
    This implements the "Suicide Pact" pattern: if the Host process dies,
    the Worker must terminate itself to prevent zombie processes.
    """
    try:
        while True:
            parent = psutil.Process(ppid)
            if parent.status() == psutil.STATUS_ZOMBIE:
                raise psutil.NoSuchProcess(ppid)
            time.sleep(1)
    except (psutil.NoSuchProcess, ProcessLookupError):
        print(f"[Worker {os.getpid()}] Parent {ppid} gone. Shutting down.")
        # Use cross-platform self-termination
        terminate_self()

# %% ../../nbs/core/worker.ipynb #app-factory
def create_app(
    module_name: str, # Python module path (e.g., "my_plugin.plugin")
    class_name: str   # Plugin class name (e.g., "WhisperPlugin")
) -> FastAPI: # Configured FastAPI application
    """Create FastAPI app that hosts the specified plugin."""
    app = FastAPI(title="Plugin Worker")
    plugin_instance = None

    # Dynamic Loading
    try:
        module = importlib.import_module(module_name)
        plugin_cls = getattr(module, class_name)
        plugin_instance = plugin_cls()
    except Exception as e:
        print(f"FATAL: Failed to load {module_name}:{class_name} - {e}")
        sys.exit(1)

    @app.get("/health")
    def health_check() -> Dict[str, Any]:
        """Health check endpoint."""
        return {
            "status": "running",
            "pid": os.getpid(),
            "name": getattr(plugin_instance, "name", "unknown"),
            "version": getattr(plugin_instance, "version", "unknown")
        }

    @app.get("/stats")
    def stats() -> Dict[str, Any]:
        """Return process tree resource usage."""
        proc = psutil.Process()
        
        # 1. Get Memory of Main Process
        total_rss = proc.memory_info().rss
        
        # 2. Get Memory of Children (Safe Loop)
        # recursive=True ensures we catch grandchildren
        for child in proc.children(recursive=True):
            try:
                # We must check if child still exists before asking for memory
                total_rss += child.memory_info().rss
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                # Process died or we don't have permission (rare for child), skip it
                pass

        return {
            "pid": os.getpid(),
            "cpu_percent": proc.cpu_percent(), # Note: aggregating CPU % is complex, main pid is usually enough proxy
            "memory_rss_mb": total_rss / 1024 / 1024
        }

    @app.post("/initialize")
    async def initialize(request: Request) -> Dict[str, str]:
        """Initialize or reconfigure the plugin."""
        try:
            config = await request.json()
            plugin_instance.initialize(config)
            return {"status": "ok"}
        except Exception as e:
            raise HTTPException(status_code=400, detail=str(e))

    @app.post("/prefetch")
    def prefetch() -> Dict[str, str]:
        """CR-4: invoke the plugin's prefetch() hook for eager resource acquisition.
        
        Default PluginInterface.prefetch() is a no-op (SG-19 hook with opt-in
        semantics). Plugins override when downstream callers benefit from
        eager model-download / cache-warming. Errors surface as 500 with the
        exception detail; idempotent calls are the plugin's responsibility.
        """
        if not hasattr(plugin_instance, "prefetch"):
            return {"status": "not_supported"}
        try:
            plugin_instance.prefetch()
            return {"status": "prefetched"}
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))

    @app.post("/reconfigure")
    async def reconfigure(request: Request) -> Dict[str, str]:
        """CR-4: invoke the plugin's reconfigure(old_config, new_config) hook.
        
        Request body: `{"old_config": {...}, "new_config": {...}}`. Default
        PluginInterface.reconfigure() delegates to reconfigure_with_triggers
        which walks RELOAD_TRIGGER metadata on the plugin's config_class.
        Plugins predating CR-4 (no config_class) land in the silent-no-op
        branch — substrate falls back to /initialize when reconfigure is a
        no-op.
        """
        if not hasattr(plugin_instance, "reconfigure"):
            return {"status": "not_supported"}
        try:
            data = await request.json()
            old_config = data.get("old_config")
            new_config = data.get("new_config")
            plugin_instance.reconfigure(old_config, new_config)
            return {"status": "reconfigured"}
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))

    @app.get("/config_schema")
    def get_config_schema() -> Dict[str, Any]:
        """Return JSON Schema for plugin configuration."""
        if hasattr(plugin_instance, 'get_config_schema'):
            return plugin_instance.get_config_schema()
        return {}

    @app.get("/config")
    def get_config() -> Dict[str, Any]:
        """Return current plugin configuration."""
        if hasattr(plugin_instance, 'get_current_config'):
            cfg = plugin_instance.get_current_config()
            # Ensure dataclasses are serialized
            return json.loads(json.dumps(cfg, cls=EnhancedJSONEncoder))
        return {}

    @app.get("/config_options")
    def get_config_options() -> Dict[str, Any]:
        """CR-11: return live config option domains (dynamic schema enrichment)."""
        if hasattr(plugin_instance, 'get_config_options'):
            opts = plugin_instance.get_config_options()
            # FieldOptions/ConfigOption dataclasses -> JSON-serializable dicts
            return json.loads(json.dumps(opts, cls=EnhancedJSONEncoder))
        return {}

    @app.post("/execute")
    async def execute(request: Request) -> Any:
        """Execute plugin's main functionality.
        
        Runs in a thread pool so the event loop stays free to serve
        concurrent requests (e.g., /progress polling during long operations).
        
        CR-4: resets the plugin's `_cancel_requested` flag before invoking
        execute() so cancellation doesn't leak from a previous job. After
        execute() returns or raises, leaves the flag in its post-call state
        (cancel() may have been called during cleanup; substrate decides what
        to do with that on next /cancel signal).
        
        CR-4: PluginCancelledError → HTTP 409 (operator-requested cancellation;
        distinct from 500's "real failure" so the proxy can surface a typed
        "cancelled" state to callers and JobQueue can render the job state
        accordingly per CR-6).
        """
        data = await request.json()
        args = data.get("args", [])
        kwargs = data.get("kwargs", {})
        
        # CR-4: reset cancellation flag before invoking execute() so stale
        # state from a previous job doesn't immediately raise.
        if hasattr(plugin_instance, "_cancel_requested"):
            plugin_instance._cancel_requested = False
        
        try:
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(
                None, lambda: plugin_instance.execute(*args, **kwargs)
            )
            # Serialize result (handles dataclasses)
            json_str = json.dumps(result, cls=EnhancedJSONEncoder)
            return json.loads(json_str)
        except PluginCancelledError as e:
            # CR-4: cooperative cancellation surfaces as 409 Conflict so the
            # proxy can distinguish "operator cancelled" from "real plugin
            # failure" (500). The detail body carries the plugin name for
            # debugging context.
            raise HTTPException(status_code=409, detail=str(e))
        except Exception as e:
            import traceback
            traceback.print_exc()
            raise HTTPException(status_code=500, detail=str(e))

    @app.post("/execute_stream")
    async def execute_stream(request: Request) -> StreamingResponse:
        """Execute plugin with streaming response (NDJSON).
        
        SG-51: resets `_cancel_requested` at the start of iter_response (parity
        with /execute) so a leftover cancel flag from a previous job doesn't
        cause the first check_cancel() to raise on the new stream.
        
        SG-52: typed error chunks via `{"_job_error": <JobError dict>}` terminal
        chunk replace the undocumented `{"error": str(e)}` shape. The wire-format
        contract: ANY exception raised during streaming is converted via
        `map_bare_exception_to_job_error` (CR-5 default classification) and
        emitted as the final NDJSON line with the `_job_error` sentinel key.
        Plugin output chunks never carry that key, so consumers (proxy +
        downstream) can detect terminal errors with a single dict membership
        check. The proxy's execute_stream then raises a typed exception
        client-side, mirroring /execute's HTTP 409 → PluginCancelledError flow.
        """
        data = await request.json()
        args = data.get("args", [])
        kwargs = data.get("kwargs", {})

        def iter_response() -> Generator[str, None, None]:
            # SG-51: reset cancel flag so stale state from a previous job doesn't
            # immediately raise inside the plugin's execute_stream iterator.
            if hasattr(plugin_instance, "_cancel_requested"):
                plugin_instance._cancel_requested = False
            try:
                if hasattr(plugin_instance, 'execute_stream'):
                    iterator = plugin_instance.execute_stream(*args, **kwargs)
                else:
                    # Fallback: wrap single result
                    iterator = [plugin_instance.execute(*args, **kwargs)]
                
                for chunk in iterator:
                    # Line-delimited JSON (NDJSON)
                    yield json.dumps(chunk, cls=EnhancedJSONEncoder) + "\n"
            except Exception as e:
                # SG-52: emit typed JobError as the terminal chunk. Proxy +
                # downstream consumers detect the `_job_error` sentinel key
                # and raise the corresponding typed exception client-side
                # (PluginCancelledError, PluginTransientError, etc.).
                job_error = map_bare_exception_to_job_error(
                    e, plugin_name=getattr(plugin_instance, "name", "unknown"),
                )
                yield json.dumps({"_job_error": job_error}, cls=EnhancedJSONEncoder) + "\n"

        return StreamingResponse(iter_response(), media_type="application/x-ndjson")

    @app.post("/cancel")
    def cancel() -> Dict[str, str]:
        """Cancel any running execution."""
        if hasattr(plugin_instance, 'cancel'):
            try:
                plugin_instance.cancel()
                return {"status": "cancelled"}
            except Exception as e:
                return {"status": "error", "detail": str(e)}
        return {"status": "not_supported"}

    @app.get("/progress")
    def get_progress() -> Dict[str, Any]:
        """Get current execution progress."""
        return {
            "progress": getattr(plugin_instance, '_progress', 0.0),
            "message": getattr(plugin_instance, '_status_message', "")
        }

    @app.post("/on_disable")
    def on_disable() -> Dict[str, str]:
        """CR-2: forward the substrate's on_disable signal to the loaded plugin.
        
        Worker stays alive; plugin's on_disable() hook gets a chance to
        release heavy resources (GPU memory, model files, etc.). Default
        PluginInterface.on_disable() is a no-op so plugins that don't
        opt in see no behavior change.
        """
        if hasattr(plugin_instance, 'on_disable'):
            try:
                plugin_instance.on_disable()
                return {"status": "disabled"}
            except Exception as e:
                return {"status": "error", "detail": str(e)}
        return {"status": "not_supported"}

    @app.post("/on_enable")
    def on_enable() -> Dict[str, str]:
        """CR-2: forward the substrate's on_enable signal to the loaded plugin.
        
        Plugin can eagerly re-acquire heavy resources or rely on lazy
        re-acquisition via the next execute() call. Default
        PluginInterface.on_enable() is a no-op.
        """
        if hasattr(plugin_instance, 'on_enable'):
            try:
                plugin_instance.on_enable()
                return {"status": "enabled"}
            except Exception as e:
                return {"status": "error", "detail": str(e)}
        return {"status": "not_supported"}

    @app.post("/get_system_status")
    def get_system_status_endpoint() -> Dict[str, Any]:
        """CR-3: typed MonitorPlugin accessor. Returns SystemStats.to_dict().
        
        Status code taxonomy (intentional, per CR-3 review):
        - 404: plugin is not a MonitorPlugin (configuration error — don't mask).
              Substrate's `system_monitor` was wired to the wrong plugin.
        - 501: plugin is a MonitorPlugin but raised NotImplementedError from its
              get_system_status() default body (legacy monitor predating CR-3 that
              opted out). Proxy falls back to /execute("get_system_status").
        - 500: plugin's get_system_status() raised some other exception. Real
              failure; do not silently fall back.
        - 200: typed call succeeded; body is SystemStats.to_dict().
        """
        if not hasattr(plugin_instance, 'get_system_status'):
            raise HTTPException(
                status_code=404,
                detail=(
                    f"Plugin {getattr(plugin_instance, 'name', class_name)!r} "
                    f"is not a MonitorPlugin (no get_system_status method)."
                ),
            )
        try:
            stats = plugin_instance.get_system_status()
        except NotImplementedError as exc:
            raise HTTPException(status_code=501, detail=str(exc) or "get_system_status not implemented")
        # Serialize via EnhancedJSONEncoder so SystemStats dataclass flattens
        # to its plain dict (and tolerates dict returns from non-typed monitors).
        if hasattr(stats, 'to_dict'):
            return stats.to_dict()
        return json.loads(json.dumps(stats, cls=EnhancedJSONEncoder))

    @app.post("/list_processes")
    def list_processes_endpoint() -> Any:
        """CR-3: typed MonitorPlugin accessor. Returns list of ProcessStats.to_dict().
        
        Same 404/501/500/200 taxonomy as /get_system_status. MonitorPlugin's
        default list_processes() returns `[]`, so non-implementing monitors
        return 200 with an empty list rather than 501.
        """
        if not hasattr(plugin_instance, 'list_processes'):
            raise HTTPException(
                status_code=404,
                detail=(
                    f"Plugin {getattr(plugin_instance, 'name', class_name)!r} "
                    f"is not a MonitorPlugin (no list_processes method)."
                ),
            )
        try:
            procs = plugin_instance.list_processes()
        except NotImplementedError as exc:
            raise HTTPException(status_code=501, detail=str(exc) or "list_processes not implemented")
        # Each ProcessStats has .to_dict(); EnhancedJSONEncoder handles either
        # dataclass instances or pre-converted dicts uniformly.
        return json.loads(json.dumps(procs, cls=EnhancedJSONEncoder))

    @app.post("/cleanup")
    def cleanup() -> Dict[str, str]:
        """Clean up plugin resources."""
        if hasattr(plugin_instance, 'cleanup'):
            plugin_instance.cleanup()
        return {"status": "cleaned"}

    return app

# %% ../../nbs/core/worker.ipynb #main-block
def run_worker() -> None:
    """CLI entry point for running the worker."""
    parser = argparse.ArgumentParser(description="Universal Plugin Worker")
    parser.add_argument("--module", required=True, help="Plugin module path")
    parser.add_argument("--class", dest="class_name", required=True, help="Plugin class name")
    # SG-4: parent-bound listening-socket FD inheritance closes the
    # bind-then-close-then-reopen TOCTOU race. --fd is preferred on Unix;
    # --port stays as the Windows fallback (pass_fds is Unix-only) and as a
    # diagnostic escape hatch when invoking the worker directly.
    parser.add_argument("--fd", type=int, required=False, default=None,
                        help="Inherited listening-socket file descriptor (Unix; preferred)")
    parser.add_argument("--port", type=int, required=False, default=None,
                        help="Port to bind (used when --fd is not provided)")
    parser.add_argument("--ppid", type=int, required=False, help="Parent PID to monitor")
    args = parser.parse_args()

    if args.fd is None and args.port is None:
        parser.error("one of --fd or --port is required")

    # Start watchdog if parent PID provided
    if args.ppid:
        watchdog = threading.Thread(
            target=parent_monitor,
            args=(args.ppid,),
            daemon=True
        )
        watchdog.start()

    app = create_app(args.module, args.class_name)
    if args.fd is not None:
        uvicorn.run(app, fd=args.fd, log_level="warning")
    else:
        uvicorn.run(app, host="127.0.0.1", port=args.port, log_level="warning")

# %% ../../nbs/core/worker.ipynb #module-main
#| eval: false
import sys

if __name__ == "__main__" and "ipykernel" not in sys.modules:
    run_worker()
