# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-plugin-system',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-plugin-system',
                'lib_path': 'cjm_plugin_system'},
  'syms': {'cjm_plugin_system.core': {'cjm_plugin_system.core.foo': ('core.html#foo', 'cjm_plugin_system/core.py')}}}
