"""CLI tool for declarative plugin management

Docs: https://cj-mills.github.io/cjm-plugin-systemcli.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/cli.ipynb.

# %% auto #0
__all__ = ['app', 'main', 'setup_runtime', 'run_cmd', 'regenerate_manifest', 'install_all', 'setup_host', 'estimate_size',
           'list_plugins', 'remove_plugin', 'validate_file']

# %% ../nbs/cli.ipynb #8385ac8c
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Annotated, Any, Dict, Optional, List

import typer
import yaml

from . import __version__ as _substrate_version
from cjm_plugin_system.core.config import (
    load_config, set_config, get_config, CondaType, RuntimeMode
)
from cjm_plugin_system.core.platform import (
    run_shell_command, conda_env_exists, get_conda_command, build_conda_command,
    ensure_runtime_available, download_micromamba, get_micromamba_binary_path,
    get_current_platform
)
from .core.metadata import PluginTaxonomy, ResourceRequirements
from cjm_plugin_system.core.manifest_format import (
    ManifestV2, InstallSection, CodeSection, DriftTracking,
    CURRENT_FORMAT_VERSION,
    load_manifest, write_manifest, manifest_to_dict, compute_config_schema_hash,
)

app = typer.Typer(help="CJM Plugin System CLI", no_args_is_help=True)

@app.callback()
def main(
    ctx:typer.Context,
    cjm_config:Annotated[Optional[Path], typer.Option(
        "--cjm-config",
        help="Path to cjm.yaml configuration file"
    )]=None,
    data_dir:Annotated[Optional[Path], typer.Option(
        "--data-dir",
        help="Override data directory (manifests, logs)"
    )]=None,
    conda_prefix:Annotated[Optional[Path], typer.Option(
        "--conda-prefix",
        help="Override conda/mamba prefix path"
    )]=None,
    conda_type:Annotated[Optional[str], typer.Option(
        "--conda-type",
        help="Conda implementation: micromamba, miniforge, or conda"
    )]=None,
) -> None:
    """CJM Plugin System CLI for managing isolated plugin environments."""
    cfg = load_config(
        config_path=cjm_config,
        data_dir=data_dir,
        conda_prefix=conda_prefix,
        conda_type=conda_type
    )
    set_config(cfg)

# %% ../nbs/cli.ipynb #6vv2de8081
@app.command("setup-runtime")
def setup_runtime(
    force:bool=typer.Option(False, "--force", "-f", help="Re-download even if binary exists")
) -> None:
    """Download and setup micromamba runtime for project-local mode."""
    cfg = get_config()
    
    # Check if micromamba mode
    if cfg.runtime.conda_type != CondaType.MICROMAMBA:
        typer.echo(f"Runtime setup is only needed for micromamba mode.")
        typer.echo(f"Current conda_type: {cfg.runtime.conda_type.value}")
        typer.echo(f"Set 'conda_type: micromamba' in cjm.yaml to use project-local runtime.")
        raise typer.Exit(code=0)
    
    # Determine binary path
    binary_path = get_micromamba_binary_path(cfg)
    
    if binary_path is None:
        typer.echo("Error: Cannot determine micromamba binary path.", err=True)
        typer.echo("Set 'runtime.prefix' or 'runtime.binaries' in cjm.yaml.", err=True)
        raise typer.Exit(code=1)
    
    # Check if already exists
    if binary_path.exists() and not force:
        typer.echo(f"Micromamba already installed at: {binary_path}")
        typer.echo(f"Use --force to re-download.")
        raise typer.Exit(code=0)
    
    # Show what will be done
    platform_str = get_current_platform()
    typer.echo(f"=== Setup Runtime ===\n")
    typer.echo(f"Platform: {platform_str}")
    typer.echo(f"Destination: {binary_path}")
    typer.echo("")
    
    # Create runtime directory structure
    if cfg.runtime.prefix:
        (cfg.runtime.prefix / "bin").mkdir(parents=True, exist_ok=True)
        (cfg.runtime.prefix / "envs").mkdir(parents=True, exist_ok=True)
        typer.echo(f"Created runtime directories at: {cfg.runtime.prefix}")
    
    # Download micromamba
    success = download_micromamba(binary_path, platform_str, show_progress=True)
    
    if success:
        typer.echo(f"\nRuntime setup complete!")
        typer.echo(f"You can now run: cjm-ctl install-all --plugins <plugins.yaml>")
    else:
        typer.echo(f"\nError: Failed to download micromamba.", err=True)
        raise typer.Exit(code=1)

# %% ../nbs/cli.ipynb #il542i2h7s
def _check_runtime_available() -> None:
    """Check if the configured conda runtime is available, exit with helpful message if not."""
    cfg = get_config()
    
    if not ensure_runtime_available(cfg):
        if cfg.runtime.conda_type == CondaType.MICROMAMBA:
            typer.echo("Error: Micromamba runtime not found.", err=True)
            typer.echo("Run 'cjm-ctl setup-runtime' first to download micromamba.", err=True)
        elif cfg.runtime.conda_type == CondaType.MINIFORGE:
            typer.echo("Error: Mamba not found in PATH.", err=True)
            typer.echo("Install miniforge/mambaforge or set conda_type to 'conda'.", err=True)
        else:
            typer.echo("Error: Conda not found in PATH.", err=True)
            typer.echo("Install conda or set the correct conda_type in cjm.yaml.", err=True)
        raise typer.Exit(code=1)

# %% ../nbs/cli.ipynb #o8jovioahe
def _get_conda_cmd_str() -> str:
    """Get the conda/micromamba command string for shell commands."""
    cfg = get_config()
    cmd_parts = get_conda_command(cfg)
    return " ".join(cmd_parts)

# %% ../nbs/cli.ipynb #qlzvouawd2
import tempfile
import urllib.request
import urllib.error

def _download_url_to_temp(
    url: str,  # URL to download
    suffix: str = ".yml"  # File suffix for temp file
) -> Optional[Path]:  # Path to temp file or None if failed
    """Download a URL to a temporary file. Returns None if download fails."""
    try:
        # Create a named temp file that won't be auto-deleted
        fd, temp_path = tempfile.mkstemp(suffix=suffix)
        os.close(fd)
        
        print(f"Downloading {url}...")
        urllib.request.urlretrieve(url, temp_path)
        return Path(temp_path)
    except (urllib.error.URLError, urllib.error.HTTPError, IOError) as e:
        print(f"Failed to download {url}: {e}")
        return None


def _resolve_env_file(
    env_file: str  # Path or URL to environment file
) -> tuple[str, Optional[Path]]:  # (resolved_path, temp_file_to_cleanup)
    """Resolve env_file to a local path, downloading if it's a URL.
    
    Returns (local_path, temp_file) where temp_file is set if we created
    a temporary file that should be cleaned up later.
    """
    if env_file.startswith("http://") or env_file.startswith("https://"):
        temp_file = _download_url_to_temp(env_file)
        if temp_file:
            return str(temp_file), temp_file
        else:
            raise RuntimeError(f"Failed to download environment file: {env_file}")
    else:
        # Local path, no cleanup needed
        return env_file, None

# %% ../nbs/cli.ipynb #db2ffd25
def run_cmd(
    cmd: str,  # Shell command to execute
    check: bool = True  # Whether to raise on non-zero exit
) -> None:
    """Run a shell command and stream output.
    
    Uses the platform's default shell (no hardcoded /bin/bash).
    """
    run_shell_command(cmd, check=check)

# %% ../nbs/cli.ipynb #f6c48ac5-2eaf-4ed1-90c5-9d91d9912d22
def _generate_manifest(
    env_name: str,  # Name of the Conda environment
    package_name: str,  # Package source string (git URL or package name)
    manifest_dir: Path  # Directory to write manifest JSON files
) -> Optional[Path]:  # Path to the manifest written, or None on failure
    """Run introspection script inside the target env and write a v2.0 manifest.
    
    Builds a `ManifestV2` from the introspection output + install-time markers,
    computes `drift_tracking.config_schema_hash`, and writes via
    `write_manifest` (nested layout, indent=2). Both `installed_at` and
    `regenerated_at` are set to "now"; `regenerate_manifest` preserves the
    original `installed_at` via post-write fix-up.
    """
    print(f"[{env_name}] Generating manifest...")
    cfg = get_config()
    
    # Robust Module Name Extraction
    if package_name.startswith("git+"):
        # Case: git+https://github.com/cj-mills/repo-name.git
        url = package_name[4:]
        repo_part = url.split('/')[-1]
        module_name = repo_part.split('.git')[0].replace('-', '_')
    elif package_name.startswith("-e "):
        path = package_name.split("-e ")[1].strip()
        module_name = Path(path).name.replace('-', '_')
    elif "/" in package_name or "\\" in package_name:
        module_name = Path(package_name).name.replace('-', '_')
    else:
        module_name = package_name.replace('-', '_')

    print(f"[{env_name}] Introspecting module: {module_name}")
    
    # Enhanced introspection script. The script:
    # 1. Gets metadata from get_plugin_metadata()
    # 2. SG-7: imports the interface class declared in meta["interface"]; fails
    #    manifest generation if the FQN doesn't resolve (catches typos +
    #    stale interface library references at install time, not runtime).
    # 3. CR-1: derives the taxonomy block {domain, role, interface_fqcn} from
    #    the verified interface FQN. Domain follows the cjm-<domain>-plugin-system
    #    naming convention; role is the interface class name.
    # 4. Instantiates the plugin class to get config_schema
    # 5. Merges config_schema into metadata (if not already present)
    introspection_script = f'''
import json
import importlib
from {module_name}.meta import get_plugin_metadata

meta = get_plugin_metadata()

# SG-7: verify the declared interface FQN actually resolves. The previous
# substrate shipped a sqlite-graph manifest whose interface field pointed to
# a non-existent module; nothing caught it until runtime discovery.
iface_fqn = meta.get("interface") or ""
if not iface_fqn:
    raise SystemExit("[introspection] interface FQN is missing in get_plugin_metadata()")
if "." not in iface_fqn:
    raise SystemExit(f"[introspection] interface FQN must be a dotted path, got: {{iface_fqn!r}}")
_iface_mod_path, _iface_cls_name = iface_fqn.rsplit(".", 1)
try:
    _iface_mod = importlib.import_module(_iface_mod_path)
except ImportError as e:
    raise SystemExit(f"[introspection] interface module not importable: {{_iface_mod_path}} ({{e}})")
if not hasattr(_iface_mod, _iface_cls_name):
    raise SystemExit(
        f"[introspection] interface class {{_iface_cls_name!r}} not found in module "
        f"{{_iface_mod_path}}"
    )

# CR-1: derive the taxonomy block. Substrate stores strings only.
# domain: extracted from cjm_<domain>_plugin_system package root.
# role: the interface class name (last segment of the FQCN).
_iface_root = _iface_mod_path.split(".")[0]
if _iface_root.startswith("cjm_") and _iface_root.endswith("_plugin_system"):
    _domain = _iface_root[len("cjm_"):-len("_plugin_system")]
else:
    # Non-conventional interface library; substrate falls back to the package
    # root so the manifest still has a usable domain string.
    _domain = _iface_root
meta["taxonomy"] = {{
    "domain": _domain,
    "role": _iface_cls_name,
    "interface_fqcn": iface_fqn,
}}

# Try to get config_schema from plugin instance if not in metadata
if "config_schema" not in meta:
    try:
        # Import plugin module and class
        plugin_module = meta.get("module", "{module_name}.plugin")
        plugin_class = meta.get("class", "")
        
        if plugin_module and plugin_class:
            mod = importlib.import_module(plugin_module)
            cls = getattr(mod, plugin_class)
            
            # Instantiate and get config schema
            instance = cls()
            if hasattr(instance, "get_config_schema"):
                meta["config_schema"] = instance.get_config_schema()
            
            # Clean up
            if hasattr(instance, "cleanup"):
                try:
                    instance.cleanup()
                except:
                    pass
    except Exception as e:
        # Config schema extraction is optional - continue without it
        pass

print(json.dumps(meta, indent=2))
'''
    
    # Build environment with CJM paths for plugin introspection
    env = dict(os.environ)
    env["CJM_DATA_DIR"] = str(cfg.plugin_data_dir)
    if cfg.models_dir:
        env["CJM_MODELS_DIR"] = str(cfg.models_dir)
    
    # SG-2: write the introspection script to a temp .py file rather than
    # passing it inline via `python -c '...'`. cmd.exe does not honor POSIX
    # single quotes, so the inline form silently breaks Windows installs.
    # delete=False because we must close the file before another process
    # (the conda-env python interpreter) reads it on Windows; the finally
    # block unlinks it.
    introspection_fd, introspection_path = tempfile.mkstemp(
        prefix=f"cjm_introspect_{env_name}_",
        suffix=".py",
    )
    try:
        with os.fdopen(introspection_fd, "w") as f:
            f.write(introspection_script)
        
        # The introspection command - use configurable conda command.
        # Double-quote the script path so paths with spaces (common on
        # Windows) work in either shell.
        conda_cmd = _get_conda_cmd_str()
        introspection_cmd = f'{conda_cmd} run -n {env_name} python "{introspection_path}"'
        
        try:
            # Check output, capture stdout
            # Use shell=True without explicit executable for cross-platform support
            # Pass env to propagate CJM paths to the introspection script
            result = subprocess.run(
                introspection_cmd,
                shell=True,
                capture_output=True,
                text=True,
                check=True,
                env=env
            )
            result_str = result.stdout.strip()
            
            # Robust JSON Parsing: 
            # Sometimes 'conda run' leaks warnings into stdout. We try to find the JSON block.
            try:
                start = result_str.find('{')
                end = result_str.rfind('}') + 1
                if start != -1 and end != 0:
                    json_str = result_str[start:end]
                    meta_json = json.loads(json_str)
                else:
                    # Fallback to full string if brackets not found
                    meta_json = json.loads(result_str)
            except json.JSONDecodeError as e:
                print(f"ERROR: Failed to parse JSON from introspection output.")
                print(f"Raw Output:\n{result_str}")
                return None

            # SG-34: drop the dead `type` field from new manifests; CR-1's
            # taxonomy block supersedes it.
            meta_json.pop("type", None)

            plugin_name = meta_json.get('name', 'unknown')
            out_file = manifest_dir / f"{plugin_name}.json"
            now_iso = datetime.now(timezone.utc).isoformat()

            # CR-8: convert flat introspection output into a nested ManifestV2.
            # The introspection script emits a flat dict with both code-section
            # fields (name/version/description/module/class/interface/taxonomy/
            # resources/config_schema) AND install-section fields the plugin
            # owns (python_path/db_path/env_vars). Substrate adds the
            # installer-side install fields (installed_at/installer_version/
            # package_source/conda_env) here.

            # Parse taxonomy + resources sub-dicts into typed objects (or None
            # when the plugin predates those CRs). Substrate stores strings
            # only — no host-side imports of interface libraries needed.
            intro_tax = meta_json.get("taxonomy")
            tax_obj: Optional[PluginTaxonomy] = None
            if isinstance(intro_tax, dict):
                tax_obj = PluginTaxonomy(
                    domain=str(intro_tax.get("domain", "") or ""),
                    role=str(intro_tax.get("role", "") or ""),
                    interface_fqcn=str(intro_tax.get("interface_fqcn", "") or ""),
                )

            intro_res = meta_json.get("resources")
            res_obj: Optional[ResourceRequirements] = None
            if isinstance(intro_res, dict):
                res_obj = ResourceRequirements(
                    requires_gpu=bool(intro_res.get("requires_gpu", False)),
                    platforms=list(intro_res.get("platforms", []) or []),
                    accelerators=list(intro_res.get("accelerators", []) or []),
                )

            config_schema = meta_json.get("config_schema")

            manifest = ManifestV2(
                install=InstallSection(
                    # Plugin-author-supplied install-section fields
                    python_path=str(meta_json.get("python_path", "") or ""),
                    db_path=str(meta_json.get("db_path", "") or ""),
                    env_vars=dict(meta_json.get("env_vars", {}) or {}),
                    # Substrate-supplied install-section fields. conda_env now
                    # written here directly (no more install_all post-write).
                    conda_env=env_name,
                    installed_at=now_iso,
                    installer_version=f"cjm-ctl {_substrate_version}",
                    package_source=package_name,
                ),
                code=CodeSection(
                    name=str(meta_json.get("name", "") or ""),
                    version=str(meta_json.get("version", "") or ""),
                    description=str(meta_json.get("description", "") or ""),
                    module=str(meta_json.get("module", "") or ""),
                    class_name=str(meta_json.get("class", "") or ""),
                    interface=str(meta_json.get("interface", "") or ""),
                    taxonomy=tax_obj,
                    resources=res_obj,
                    config_schema=config_schema,
                    regenerated_at=now_iso,
                ),
                drift_tracking=DriftTracking(
                    config_schema_hash=compute_config_schema_hash(config_schema),
                ),
                overrides={},
            )
            
            # Log detected metadata
            if tax_obj is not None:
                print(f"[{env_name}] Taxonomy: {tax_obj.domain}/{tax_obj.role}")
            if manifest.code.interface:
                print(f"[{env_name}] Interface: {manifest.code.interface}")
            if config_schema is not None:
                print(f"[{env_name}] Config schema: captured")
            
            write_manifest(out_file, manifest)
            print(f"[{env_name}] Wrote manifest to {out_file}")
            # SG-3: return the path so callers can update the manifest by exact
            # file rather than scanning `manifest_dir` with a substring match.
            return out_file
            
        except subprocess.CalledProcessError as e:
            print(f"Error generating manifest for {env_name}:")
            print(e.stderr if e.stderr else str(e))
            return None
        except Exception as e:
            print(f"Unexpected error generating manifest: {e}")
            return None
    finally:
        # Best-effort cleanup of the temp introspection script.
        try:
            os.unlink(introspection_path)
        except OSError:
            pass

# %% ../nbs/cli.ipynb #4eacfb61
@app.command("regenerate-manifest")
def regenerate_manifest(
    plugin_name: str = typer.Argument(..., help="Plugin name as it appears in the manifest"),
    plugins_path: Optional[str] = typer.Option(
        None, "--plugins",
        help="Path to plugins.yaml for package_source recovery (legacy manifests)",
    ),
    package: Optional[str] = typer.Option(
        None, "--package",
        help="Package spec override (e.g., git URL or pip name); wins over manifest/plugins.yaml lookups",
    ),
) -> None:
    """Re-run introspection for an installed plugin and rewrite its manifest.
    
    Reads the existing manifest via `load_manifest` (handles both v2.0 nested
    + legacy v1.0 flat layouts), recovers `env_name` + `package_source` from
    the install section, runs `_generate_manifest` to refresh the code section,
    then post-writes to preserve the original `installed_at` so the regenerate
    only updates `regenerated_at` semantically. Always emits v2.0 layout —
    regenerating a v1.0 manifest transparently upgrades it.
    """
    cfg = get_config()
    manifest_path = cfg.manifests_dir / f"{plugin_name}.json"
    if not manifest_path.exists():
        typer.echo(f"No manifest found at {manifest_path}", err=True)
        raise typer.Exit(code=1)
    
    try:
        existing = load_manifest(manifest_path)
    except (json.JSONDecodeError, ValueError) as e:
        typer.echo(f"Cannot parse existing manifest {manifest_path}: {e}", err=True)
        raise typer.Exit(code=1)
    
    # Recover env_name: explicit field preferred, python_path fallback for legacy.
    env_name = existing.install.conda_env or _extract_env_from_python_path(
        existing.install.python_path
    )
    if not env_name:
        typer.echo(
            f"Cannot determine conda env for {plugin_name!r}: manifest lacks both "
            f"'conda_env' field and a parseable 'python_path'. Reinstall the plugin "
            f"via `cjm-ctl install-all` to refresh.",
            err=True,
        )
        raise typer.Exit(code=1)
    
    # Recover package_source: --package > manifest.install.package_source > plugins.yaml lookup.
    package_source = package
    source_origin = "--package override"
    if package_source is None:
        package_source = existing.install.package_source or None
        if package_source:
            source_origin = "manifest.install.package_source"
    if package_source is None and plugins_path and os.path.exists(plugins_path):
        with open(plugins_path) as f:
            yconfig = yaml.safe_load(f)
        for p in (yconfig or {}).get("plugins", []):
            if p.get("name") == plugin_name:
                package_source = p.get("package")
                source_origin = f"{plugins_path} lookup"
                break
    if package_source is None:
        typer.echo(
            f"Cannot recover package spec for {plugin_name!r}. Manifest predates the "
            f"`package_source` field. Supply --package <spec> or "
            f"--plugins plugins.yaml.",
            err=True,
        )
        raise typer.Exit(code=1)
    
    # Snapshot the original installed_at so we can preserve it after _generate_manifest
    # rewrites the file (which would otherwise set installed_at = regenerated_at = now).
    original_installed_at = existing.install.installed_at
    
    typer.echo(f"Regenerating {plugin_name} from {package_source} ({source_origin})...")
    out_path = _generate_manifest(env_name, package_source, cfg.manifests_dir)
    if out_path is None:
        typer.echo(f"Regeneration failed for {plugin_name}", err=True)
        raise typer.Exit(code=1)
    
    # Post-write fix-up: restore installed_at from the pre-existing manifest.
    # _generate_manifest sets both installed_at + regenerated_at to "now"; for
    # regenerations the install timestamp should be the original install moment.
    # If the original manifest had no installed_at (very old legacy), let
    # _generate_manifest's "now" stand — better than empty.
    if original_installed_at:
        try:
            refreshed = load_manifest(out_path)
            refreshed.install.installed_at = original_installed_at
            write_manifest(out_path, refreshed)
        except (json.JSONDecodeError, ValueError, IOError) as e:
            typer.echo(f"Warning: failed to restore installed_at on {out_path}: {e}")
    
    typer.echo(f"✓ Regenerated manifest at {out_path}")

# %% ../nbs/cli.ipynb #d448fe11
def _conda_env_exists_configured(
    env_name: str  # Name of the conda environment
) -> bool:  # True if environment exists
    """Check if conda environment exists using configured conda command."""
    cfg = get_config()
    cmd_parts = get_conda_command(cfg)
    # Use the first part as the conda command for conda_env_exists
    conda_cmd = cmd_parts[0]
    
    # For micromamba with root prefix, we need to filter envs by the prefix path
    if cfg.runtime.conda_type == CondaType.MICROMAMBA and cfg.runtime.prefix:
        # micromamba -r <prefix> env list --json returns ALL known envs,
        # so we need to filter by the root prefix path
        try:
            result = subprocess.run(
                cmd_parts + ["env", "list", "--json"],
                capture_output=True,
                text=True
            )
            if result.returncode != 0:
                return False
            
            data = json.loads(result.stdout)
            # Get the absolute prefix path for comparison
            prefix_str = str(cfg.runtime.prefix.resolve())
            
            for path in data.get('envs', []):
                # Only consider envs under our root prefix
                if path.startswith(prefix_str):
                    if Path(path).name == env_name:
                        return True
            return False
        except (subprocess.SubprocessError, json.JSONDecodeError, FileNotFoundError):
            return False
    elif cfg.runtime.conda_type == CondaType.MICROMAMBA:
        # System micromamba without root prefix
        return conda_env_exists(env_name, conda_cmd)
    else:
        return conda_env_exists(env_name, conda_cmd)


@app.command()
def install_all(
    plugins_path:str=typer.Option("plugins.yaml", "--plugins", help="Path to plugins.yaml file"),
    force:bool=typer.Option(False, help="Force recreation of environments")
) -> None:
    """Install and register all plugins defined in plugins.yaml."""
    cfg = get_config()
    
    # Check runtime availability
    _check_runtime_available()
    
    if not os.path.exists(plugins_path):
        typer.echo(f"Plugins file not found: {plugins_path}", err=True)
        raise typer.Exit(code=1)

    with open(plugins_path) as f:
        config = yaml.safe_load(f)

    # Setup manifest directory using config
    manifest_dir = cfg.manifests_dir
    manifest_dir.mkdir(parents=True, exist_ok=True)

    plugins = config.get('plugins', [])
    print(f"Found {len(plugins)} plugins to process.")
    
    # Get the conda command string for shell commands
    conda_cmd = _get_conda_cmd_str()
    
    # Determine if using micromamba (different command syntax)
    is_micromamba = cfg.runtime.conda_type == CondaType.MICROMAMBA
    
    # Track temp files to clean up
    temp_files_to_cleanup: List[Path] = []

    try:
        for plugin in plugins:
            name = plugin.get('name')
            env_name = plugin.get('env_name')
            print(f"\n=== Processing {name} ({env_name}) ===")

            # 1. Check if Env Exists (using configured conda command)
            env_exists = _conda_env_exists_configured(env_name)

            # 2. Create Environment
            if not env_exists or force:
                # SAFETY: If forcing, remove old one first to avoid flag issues
                if env_exists and force:
                    print(f"Removing existing environment {env_name}...")
                    run_cmd(f"{conda_cmd} env remove -n {env_name} -y")

                if 'env_file' in plugin:
                    # Resolve env_file (download if URL)
                    local_env_file, temp_file = _resolve_env_file(plugin['env_file'])
                    if temp_file:
                        temp_files_to_cleanup.append(temp_file)
                    
                    # micromamba uses 'create' directly, conda uses 'env create'
                    if is_micromamba:
                        run_cmd(f"{conda_cmd} create -f {local_env_file} -n {env_name} -y")
                    else:
                        run_cmd(f"{conda_cmd} env create -f {local_env_file} -n {env_name}")
                elif 'python_version' in plugin:
                    run_cmd(f"{conda_cmd} create -n {env_name} python={plugin['python_version']} -y")

            # 3. Install Dependencies (Pip)
            base_pip_cmd = f"{conda_cmd} run -n {env_name} pip install"
            
            if 'interface_libs' in plugin:
                libs = " ".join(plugin['interface_libs'])
                run_cmd(f"{base_pip_cmd} {libs}")

            if 'package' in plugin:
                run_cmd(f"{base_pip_cmd} {plugin['package']}")

            # 4. Generate Manifest.
            # CR-8: _generate_manifest now writes install.conda_env directly
            # (it has env_name as a parameter), so the legacy post-write
            # conda_env step is no longer needed.
            pkg_source = plugin['package']
            _generate_manifest(env_name, pkg_source, manifest_dir)

        print("\n All operations complete.")
    
    finally:
        # Clean up any temporary files
        for temp_file in temp_files_to_cleanup:
            try:
                temp_file.unlink()
            except IOError:
                pass

# %% ../nbs/cli.ipynb #ley0ge2bt8j
@app.command("setup-host")
def setup_host(
    plugins_path:str=typer.Option("plugins.yaml", "--plugins", help="Path to plugins.yaml file"),
    yes:bool=typer.Option(False, "--yes", "-y", help="Skip confirmation prompt")
) -> None:
    """Install interface libraries in the current Python environment."""
    if not os.path.exists(plugins_path):
        typer.echo(f"Plugins file not found: {plugins_path}", err=True)
        raise typer.Exit(code=1)

    with open(plugins_path) as f:
        config = yaml.safe_load(f)

    # Collect unique interface libraries from all plugins
    plugins = config.get('plugins', [])
    all_libs: set[str] = set()
    
    for plugin in plugins:
        interface_libs = plugin.get('interface_libs', [])
        all_libs.update(interface_libs)
    
    # Filter out cjm-plugin-system (already installed since we're running this CLI)
    all_libs = {lib for lib in all_libs 
                if 'cjm-plugin-system.git' not in lib and lib != 'cjm-plugin-system'}
    
    if not all_libs:
        typer.echo("No interface libraries found in config.")
        raise typer.Exit(code=0)

    # Display what will be installed
    typer.echo(f"Reading {plugins_path}...")
    typer.echo(f"Found {len(all_libs)} unique interface libraries:")
    for lib in sorted(all_libs):
        typer.echo(f"  - {lib}")
    typer.echo("")

    # Confirm with user unless --yes flag provided
    if not yes:
        confirm = typer.confirm("Install these in the current Python environment?")
        if not confirm:
            typer.echo("Aborted.")
            raise typer.Exit(code=0)

    # Install libraries using the current Python interpreter
    libs_str = " ".join(sorted(all_libs))
    run_cmd(f"{sys.executable} -m pip install {libs_str}")
    
    typer.echo("\nHost environment setup complete.")

# %% ../nbs/cli.ipynb #w8lkxjiwtcl
def _format_size(
    size_bytes: int  # Size in bytes
) -> str:  # Human-readable size string
    """Format bytes as human-readable string."""
    for unit in ['B', 'KB', 'MB', 'GB', 'TB']:
        if size_bytes < 1024:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024
    return f"{size_bytes:.1f} PB"


# SG-37: in-process cache of PyPI 404 responses so a single estimate-size run
# doesn't re-query the same missing name across multiple plugins.
_PYPI_404_CACHE: set[str] = set()


def _get_pypi_size(
    package_spec: str  # Package name or git URL
) -> tuple[int, str]:  # (size_bytes, package_name)
    """Query PyPI for package download size.
    
    SG-37: PyPI normalizes package names to dash-form per PEP 503, so we try
    the dash form first and fall back to the underscore form. Without this,
    cjm-* packages (whose repo names contain dashes) silently 404 because
    the old heuristic only tried the underscored form.
    """
    # Extract a raw repo-name fragment from various spec formats.
    raw_name = package_spec
    if 'github.com' in package_spec and '.git' in package_spec:
        raw_name = package_spec.split('/')[-1].replace('.git', '')
    elif package_spec.startswith('git+'):
        raw_name = package_spec.rstrip('/').split('/')[-1]
    elif '[' in package_spec:
        raw_name = package_spec.split('[')[0]
    elif '>=' in package_spec:
        raw_name = package_spec.split('>=')[0]
    elif '==' in package_spec:
        raw_name = package_spec.split('==')[0]
    
    # Build ordered candidate list: dash-form first (canonical per PEP 503),
    # then underscore-form as fallback. Dedupe while preserving order.
    dash_form = raw_name.replace('_', '-')
    underscore_form = raw_name.replace('-', '_')
    candidates: List[str] = []
    for cand in (dash_form, underscore_form):
        if cand and cand not in candidates:
            candidates.append(cand)
    
    for package_name in candidates:
        if package_name in _PYPI_404_CACHE:
            continue
        try:
            url = f"https://pypi.org/pypi/{package_name}/json"
            with urllib.request.urlopen(url, timeout=10) as resp:
                data = json.loads(resp.read().decode())
            
            # Get the largest file size (usually the wheel)
            urls = data.get('urls', [])
            if urls:
                max_size = max(u.get('size', 0) for u in urls)
                return max_size, package_name
            return 0, package_name
        except urllib.error.HTTPError as e:
            if e.code == 404:
                _PYPI_404_CACHE.add(package_name)
                continue
        except (urllib.error.URLError, json.JSONDecodeError):
            pass
    
    # Nothing matched; surface the canonical form to the caller for display.
    return 0, candidates[0] if candidates else raw_name


def _estimate_conda_size(
    env_file: str,  # Path or URL to environment.yml
    env_name: str  # Target environment name
) -> tuple[int, int]:  # (total_bytes, package_count)
    """Estimate conda package sizes using dry-run."""
    cfg = get_config()
    
    # Resolve env_file (download if URL)
    temp_file = None
    try:
        local_env_file, temp_file = _resolve_env_file(env_file)
    except RuntimeError:
        return 0, 0
    
    try:
        cmd_parts = build_conda_command(cfg, "create", "-f", local_env_file, "-n", env_name, "--dry-run", "--json")
        
        # For micromamba, the command is slightly different
        if cfg.runtime.conda_type != CondaType.MICROMAMBA:
            # conda/mamba use "env create" for environment files
            cmd_parts = build_conda_command(cfg, "env", "create", "-f", local_env_file, "-n", env_name, "--dry-run", "--json")
        
        result = subprocess.run(
            cmd_parts,
            capture_output=True, text=True
        )
        
        if result.returncode != 0:
            return 0, 0
        
        data = json.loads(result.stdout)
        fetch_actions = data.get('actions', {}).get('FETCH', [])
        total_size = sum(pkg.get('size', 0) for pkg in fetch_actions)
        return total_size, len(fetch_actions)
        
    except (subprocess.SubprocessError, json.JSONDecodeError):
        return 0, 0
    finally:
        # Clean up temp file if we created one
        if temp_file:
            try:
                temp_file.unlink()
            except IOError:
                pass


def _estimate_pip_sizes(
    packages: list[str]  # List of pip package specs
) -> tuple[int, int, list[tuple[str, int]]]:  # (total_bytes, found_count, [(name, size), ...])
    """Estimate pip package sizes from PyPI."""
    total_size = 0
    found_count = 0
    details = []
    
    for pkg in packages:
        size, name = _get_pypi_size(pkg)
        details.append((name, size))
        if size > 0:
            total_size += size
            found_count += 1
    
    return total_size, found_count, details

# %% ../nbs/cli.ipynb #kuad748fs2k
from typing import List

@app.command("estimate-size")
def estimate_size(
    plugins_path:str=typer.Option("plugins.yaml", "--plugins", help="Path to plugins.yaml file"),
    plugin_name:Optional[str]=typer.Option(None, "--plugin", "-p", help="Estimate for a single plugin"),
    verbose:bool=typer.Option(False, "--verbose", "-v", help="Show per-package breakdown")
) -> None:
    """Estimate disk space required for plugin environments."""
    if not os.path.exists(plugins_path):
        typer.echo(f"Plugins file not found: {plugins_path}", err=True)
        raise typer.Exit(code=1)

    with open(plugins_path) as f:
        config = yaml.safe_load(f)

    plugins = config.get('plugins', [])
    
    # Filter to single plugin if specified
    if plugin_name:
        plugins = [p for p in plugins if p.get('name') == plugin_name]
        if not plugins:
            typer.echo(f"Plugin not found: {plugin_name}", err=True)
            raise typer.Exit(code=1)

    typer.echo(f"=== Disk Space Estimates ===\n")
    
    total_conda = 0
    total_pip = 0
    
    for plugin in plugins:
        name = plugin.get('name', 'unknown')
        env_name = plugin.get('env_name', '')
        
        typer.echo(f"{name} (env: {env_name})")
        
        # Estimate conda packages
        conda_size = 0
        conda_count = 0
        if 'env_file' in plugin:
            typer.echo(f"  Analyzing conda environment...")
            conda_size, conda_count = _estimate_conda_size(plugin['env_file'], env_name)
            total_conda += conda_size
            
            if conda_size > 0:
                typer.echo(f"  Conda packages: {_format_size(conda_size)} ({conda_count} packages)")
            else:
                typer.echo(f"  Conda packages: Unable to estimate (env may already exist)")
        
        # Estimate pip packages
        pip_packages: List[str] = []
        if 'interface_libs' in plugin:
            pip_packages.extend(plugin['interface_libs'])
        if 'package' in plugin:
            pip_packages.append(plugin['package'])
        
        if pip_packages:
            pip_size, found_count, details = _estimate_pip_sizes(pip_packages)
            total_pip += pip_size
            
            not_found = len(pip_packages) - found_count
            size_str = _format_size(pip_size) if pip_size > 0 else "unknown"
            
            status_parts = []
            if found_count > 0:
                status_parts.append(f"{found_count} found on PyPI")
            if not_found > 0:
                status_parts.append(f"{not_found} not on PyPI")
            
            typer.echo(f"  Pip packages:   {size_str} compressed ({', '.join(status_parts)})")
            
            if verbose and details:
                for pkg_name, pkg_size in details:
                    if pkg_size > 0:
                        typer.echo(f"    - {pkg_name}: {_format_size(pkg_size)}")
                    else:
                        typer.echo(f"    - {pkg_name}: (not found)")
        
        typer.echo("")
    
    # Summary
    typer.echo("─" * 40)
    typer.echo("TOTAL ESTIMATES")
    typer.echo(f"  Conda packages: {_format_size(total_conda)}")
    typer.echo(f"  Pip packages:   {_format_size(total_pip)} (compressed)")
    typer.echo(f"  Combined:       {_format_size(total_conda + total_pip)}")
    typer.echo("")
    typer.echo("Note: Pip sizes are compressed downloads. Installed size is typically 2-5x larger.")
    typer.echo("      Conda estimates require the environment to not already exist.")

# %% ../nbs/cli.ipynb #8bvmucsze7m
def _get_conda_envs() -> set[str]: # Set of existing conda environment names
    """Get list of existing conda environment names using configured conda command."""
    cfg = get_config()
    cmd_parts = build_conda_command(cfg, "env", "list", "--json")
    
    try:
        result = subprocess.run(
            cmd_parts,
            capture_output=True, text=True
        )
        if result.returncode == 0:
            data = json.loads(result.stdout)
            envs = set()
            
            # For micromamba with root prefix, filter by the prefix path
            if cfg.runtime.conda_type == CondaType.MICROMAMBA and cfg.runtime.prefix:
                prefix_str = str(cfg.runtime.prefix.resolve())
                for path in data.get('envs', []):
                    if path.startswith(prefix_str):
                        env_name = Path(path).name
                        envs.add(env_name)
            else:
                # For conda/mamba or system micromamba, use all envs
                for path in data.get('envs', []):
                    env_name = Path(path).name
                    envs.add(env_name)
            
            return envs
    except (subprocess.SubprocessError, json.JSONDecodeError):
        pass
    return set()


def _v2_to_legacy_flat_view(
    raw: Dict[str, Any]  # Manifest JSON dict as read from disk
) -> Dict[str, Any]:  # Flat-shaped dict (install + code merged at top level)
    """REMOVE-AFTER-OVERHAUL: produce a legacy flat-shaped view of a manifest.
    
    Consumer code in `list_plugins` + `remove_plugin` still reads manifests as
    flat dicts (`manifest.get('python_path')`, etc.). When the on-disk manifest
    is v2.0 nested, we flatten install + code sections to the top level so
    those consumers don't need migration in the same PR. The shim retires when
    consumers migrate to `load_manifest` for typed access.
    
    v1.0 manifests pass through unchanged.
    """
    if not isinstance(raw, dict) or raw.get("format_version") != CURRENT_FORMAT_VERSION:
        return raw
    install = raw.get("install", {}) or {}
    code = raw.get("code", {}) or {}
    flat: Dict[str, Any] = {}
    flat.update(install)
    flat.update(code)
    flat["format_version"] = raw.get("format_version", CURRENT_FORMAT_VERSION)
    return flat


def _get_installed_manifests(
    manifest_dir:Optional[Path]=None # Directory to scan (uses config default if None)
) -> list[dict]: # List of manifest dictionaries
    """Load all manifest JSON files from the manifest directory.
    
    Returns flat-shaped dicts regardless of on-disk format (v2.0 manifests are
    flattened via `_v2_to_legacy_flat_view`). Consumers that want typed access
    should use `load_manifest` from `cjm_plugin_system.core.manifest_format`
    instead.
    """
    if manifest_dir is None:
        manifest_dir = get_config().manifests_dir
    
    manifests = []
    
    if not manifest_dir.exists():
        return manifests
    
    for manifest_file in manifest_dir.glob("*.json"):
        try:
            with open(manifest_file) as f:
                raw = json.load(f)
            manifest = _v2_to_legacy_flat_view(raw)
            manifest['_manifest_path'] = str(manifest_file)
            manifests.append(manifest)
        except (json.JSONDecodeError, IOError):
            pass
    
    return manifests


def _extract_env_from_python_path(
    python_path:str # Path like /home/user/miniforge3/envs/my-env/bin/python
) -> str: # Extracted environment name or empty string
    """Extract conda environment name from python_path."""
    if not python_path:
        return ''
    
    # Look for /envs/<env_name>/ pattern
    path_parts = Path(python_path).parts
    for i, part in enumerate(path_parts):
        if part == 'envs' and i + 1 < len(path_parts):
            return path_parts[i + 1]
    
    return ''


@app.command("list")
def list_plugins(
    plugins_path:Optional[str]=typer.Option(None, "--plugins", help="Path to plugins.yaml for cross-reference"),
    show_envs:bool=typer.Option(False, "--envs", "-e", help="Show conda environment status")
) -> None:
    """List installed plugins from manifest directory."""
    cfg = get_config()
    manifests = _get_installed_manifests()
    
    if not manifests:
        typer.echo(f"No plugins found in {cfg.manifests_dir}")
        raise typer.Exit(code=0)
    
    # Load config for cross-reference if provided
    config_plugins = {}
    if plugins_path and os.path.exists(plugins_path):
        with open(plugins_path) as f:
            config = yaml.safe_load(f)
        for p in config.get('plugins', []):
            config_plugins[p.get('name')] = p
    
    # Get conda envs if requested
    conda_envs = _get_conda_envs() if show_envs else set()
    
    typer.echo(f"=== Installed Plugins ({len(manifests)}) ===\n")
    
    for manifest in sorted(manifests, key=lambda m: m.get('name', '')):
        name = manifest.get('name', 'unknown')
        version = manifest.get('version', '?')
        category = manifest.get('category', '')
        
        # Get env name from manifest or extract from python_path
        env_name = manifest.get('conda_env', '')
        if not env_name:
            env_name = _extract_env_from_python_path(manifest.get('python_path', ''))
        
        # Basic info line
        cat_str = f" [{category}]" if category else ""
        typer.echo(f"{name} v{version}{cat_str}")
        
        # Environment status
        if show_envs and env_name:
            env_status = "exists" if env_name in conda_envs else "missing"
            typer.echo(f"  Env: {env_name} ({env_status})")
        elif show_envs:
            typer.echo(f"  Env: (not specified in manifest)")
        
        # Cross-reference with config
        if plugins_path:
            if name in config_plugins:
                cfg_env = config_plugins[name].get('env_name', '')
                if cfg_env and cfg_env != env_name:
                    typer.echo(f"  Config env: {cfg_env} (differs from manifest)")
            else:
                typer.echo(f"  (not in {plugins_path})")
        
        typer.echo("")

# %% ../nbs/cli.ipynb #hl18n81zioc
@app.command("remove")
def remove_plugin(
    plugin_name:str=typer.Argument(..., help="Name of the plugin to remove"),
    plugins_path:Optional[str]=typer.Option(None, "--plugins", help="Path to plugins.yaml for env name lookup"),
    keep_env:bool=typer.Option(False, "--keep-env", help="Keep the conda environment, only remove manifest"),
    yes:bool=typer.Option(False, "--yes", "-y", help="Skip confirmation prompt")
) -> None:
    """Remove a plugin's manifest and conda environment."""
    cfg = get_config()
    manifest_dir = cfg.manifests_dir
    manifest_path = manifest_dir / f"{plugin_name}.json"
    
    # Find the manifest. CR-8: read via the legacy-flat-view shim so v2.0
    # nested manifests work with the existing dict-access code below.
    manifest = None
    if manifest_path.exists():
        try:
            with open(manifest_path) as f:
                raw = json.load(f)
            manifest = _v2_to_legacy_flat_view(raw)
        except (json.JSONDecodeError, IOError):
            pass
    
    if not manifest:
        typer.echo(f"Plugin manifest not found: {plugin_name}", err=True)
        typer.echo(f"  Expected at: {manifest_path}")
        raise typer.Exit(code=1)
    
    # Determine conda environment name (try multiple sources)
    env_name = manifest.get('conda_env', '')
    
    # Fallback 1: Extract from python_path in manifest
    if not env_name:
        env_name = _extract_env_from_python_path(manifest.get('python_path', ''))
    
    # Fallback 2: Check plugins file
    if not env_name and plugins_path and os.path.exists(plugins_path):
        with open(plugins_path) as f:
            config = yaml.safe_load(f)
        for p in config.get('plugins', []):
            if p.get('name') == plugin_name:
                env_name = p.get('env_name', '')
                break
    
    # Check if env exists
    conda_envs = _get_conda_envs()
    env_exists = env_name in conda_envs if env_name else False
    
    # Show what will be removed
    typer.echo(f"=== Remove Plugin: {plugin_name} ===\n")
    typer.echo(f"Manifest: {manifest_path}")
    
    if env_name:
        if env_exists:
            if keep_env:
                typer.echo(f"Conda env: {env_name} (will be kept)")
            else:
                typer.echo(f"Conda env: {env_name} (will be removed)")
        else:
            typer.echo(f"Conda env: {env_name} (does not exist)")
    else:
        typer.echo(f"Conda env: (not specified)")
    
    typer.echo("")
    
    # Confirm
    if not yes:
        confirm = typer.confirm("Proceed with removal?")
        if not confirm:
            typer.echo("Aborted.")
            raise typer.Exit(code=0)
    
    # Remove conda environment using configured command
    if env_name and env_exists and not keep_env:
        typer.echo(f"Removing conda environment: {env_name}...")
        try:
            cmd_parts = build_conda_command(cfg, "env", "remove", "-n", env_name, "-y")
            subprocess.run(cmd_parts, check=True)
            typer.echo(f"  Removed: {env_name}")
        except subprocess.CalledProcessError as e:
            typer.echo(f"  Warning: Failed to remove conda env: {e}", err=True)
    
    # Remove manifest file
    typer.echo(f"Removing manifest: {manifest_path}...")
    try:
        manifest_path.unlink()
        typer.echo(f"  Removed: {manifest_path.name}")
    except IOError as e:
        typer.echo(f"  Error removing manifest: {e}", err=True)
        raise typer.Exit(code=1)
    
    typer.echo(f"\nPlugin '{plugin_name}' removed successfully.")

# %% ../nbs/cli.ipynb #df2c4524
def _validate_taxonomy_block(
    tax: Any,  # taxonomy sub-dict (may be None or non-dict; we type-check here)
    top_level_interface: str,  # `interface` field for cross-check
    path_prefix: str,  # Error message prefix (e.g., "manifest" or "manifest: code")
) -> List[str]:
    """Type-check the taxonomy block + cross-check interface_fqcn vs top-level interface.
    
    Shared between v1.0 (flat) and v2.0 (nested) validators. `path_prefix` is
    used to disambiguate error messages between layouts.
    """
    errors: List[str] = []
    if tax is None:
        return errors
    if not isinstance(tax, dict):
        errors.append(f"{path_prefix}: 'taxonomy' must be an object when present")
        return errors
    for tax_key in ("domain", "role", "interface_fqcn"):
        tax_val = tax.get(tax_key)
        if tax_val is None or tax_val == "":
            errors.append(f"{path_prefix}: 'taxonomy.{tax_key}' is required when taxonomy block present")
        elif not isinstance(tax_val, str):
            errors.append(f"{path_prefix}: 'taxonomy.{tax_key}' must be a string")
    # Cross-check: taxonomy.interface_fqcn must agree with the sibling `interface`
    # field if both are present. Drift here means manifest corruption —
    # regenerate-manifest is the operator fix.
    if (
        isinstance(tax.get("interface_fqcn"), str)
        and isinstance(top_level_interface, str)
        and top_level_interface
        and tax["interface_fqcn"] != top_level_interface
    ):
        errors.append(
            f"{path_prefix}: 'taxonomy.interface_fqcn' ({tax['interface_fqcn']!r}) "
            f"disagrees with sibling 'interface' ({top_level_interface!r})"
        )
    return errors


def _validate_resources_block(
    res: Any,  # resources sub-dict (may be None or non-dict; we type-check here)
    path_prefix: str,  # Error message prefix
) -> List[str]:
    """Phase 5a: type-check the resources block. Shared between v1.0 and v2.0."""
    errors: List[str] = []
    if res is None:
        return errors
    if not isinstance(res, dict):
        errors.append(f"{path_prefix}: 'resources' must be an object when present")
        return errors
    if "requires_gpu" in res and not isinstance(res["requires_gpu"], bool):
        errors.append(f"{path_prefix}: 'resources.requires_gpu' must be a boolean")
    for list_key in ("platforms", "accelerators"):
        if list_key in res:
            lst = res[list_key]
            if not isinstance(lst, list):
                errors.append(f"{path_prefix}: 'resources.{list_key}' must be a list")
            elif not all(isinstance(item, str) for item in lst):
                errors.append(f"{path_prefix}: 'resources.{list_key}' must contain only strings")
    return errors


def _validate_manifest_v2_dict(
    data: Dict[str, Any]  # v2.0 nested manifest dict (caller already verified format_version)
) -> List[str]:  # Empty list = valid
    """CR-8: validate the nested v2.0 manifest layout.
    
    Required sections: `install` + `code`. Optional sections: `drift_tracking`
    (substrate emits it on every fresh write but legacy-via-load_manifest
    upgrades leave it empty until the first regenerate); `overrides` (free-form
    operator overlay).
    
    Required `code.*` fields mirror v1.0's required top-level fields. Required
    `install.python_path` mirrors v1.0's required top-level `python_path`.
    """
    errors: List[str] = []
    
    # Sections must be dicts when present
    install = data.get("install")
    code = data.get("code")
    drift = data.get("drift_tracking")
    overrides = data.get("overrides")
    
    if install is None:
        errors.append("manifest: required section 'install' is missing")
        install = {}
    elif not isinstance(install, dict):
        errors.append(f"manifest: 'install' must be an object, got {type(install).__name__}")
        install = {}
    
    if code is None:
        errors.append("manifest: required section 'code' is missing")
        code = {}
    elif not isinstance(code, dict):
        errors.append(f"manifest: 'code' must be an object, got {type(code).__name__}")
        code = {}
    
    if drift is not None and not isinstance(drift, dict):
        errors.append(f"manifest: 'drift_tracking' must be an object when present, got {type(drift).__name__}")
        drift = {}
    
    if overrides is not None and not isinstance(overrides, dict):
        errors.append(f"manifest: 'overrides' must be an object when present, got {type(overrides).__name__}")
    
    # Required code.* fields (mirroring v1.0 contract)
    for key in ("name", "version", "description", "module", "class", "interface"):
        val = code.get(key) if isinstance(code, dict) else None
        if val is None or val == "":
            errors.append(f"manifest: required field 'code.{key}' is missing or empty")
        elif not isinstance(val, str):
            errors.append(f"manifest: 'code.{key}' must be a string, got {type(val).__name__}")
    
    # Required install.python_path (the proxy needs it to spawn the worker)
    py_path = install.get("python_path") if isinstance(install, dict) else None
    if py_path is None or py_path == "":
        errors.append("manifest: required field 'install.python_path' is missing or empty")
    elif not isinstance(py_path, str):
        errors.append(f"manifest: 'install.python_path' must be a string, got {type(py_path).__name__}")
    
    # Interface FQN must be a dotted path (SG-7 format check)
    iface = code.get("interface", "") if isinstance(code, dict) else ""
    if isinstance(iface, str) and iface and "." not in iface:
        errors.append(
            f"manifest: 'code.interface' {iface!r} is not a dotted FQN "
            f"(expected 'module.subpackage.ClassName')"
        )
    
    # Optional install.* fields — type-check only
    for key in ("conda_env", "db_path", "installed_at", "installer_version", "package_source"):
        if isinstance(install, dict) and key in install and not isinstance(install[key], str):
            errors.append(f"manifest: 'install.{key}' must be a string when present")
    if isinstance(install, dict) and "env_vars" in install and not isinstance(install["env_vars"], dict):
        errors.append("manifest: 'install.env_vars' must be an object when present")
    
    # Optional code.* fields
    if isinstance(code, dict) and "regenerated_at" in code and code["regenerated_at"] is not None:
        if not isinstance(code["regenerated_at"], str):
            errors.append("manifest: 'code.regenerated_at' must be a string when present")
    
    # Optional code.config_schema
    if isinstance(code, dict) and "config_schema" in code and code["config_schema"] is not None:
        cs = code["config_schema"]
        if not isinstance(cs, dict):
            errors.append("manifest: 'code.config_schema' must be an object when present")
        elif "properties" in cs and not isinstance(cs["properties"], dict):
            errors.append("manifest: 'code.config_schema.properties' must be an object when present")
    
    # Optional code.taxonomy block — shared helper for cross-check + type-check
    if isinstance(code, dict):
        errors.extend(_validate_taxonomy_block(
            code.get("taxonomy"),
            top_level_interface=code.get("interface", "") if isinstance(code.get("interface"), str) else "",
            path_prefix="manifest: code",
        ))
        errors.extend(_validate_resources_block(
            code.get("resources"),
            path_prefix="manifest: code",
        ))
    
    # drift_tracking.config_schema_hash type-check (optional even when present)
    if isinstance(drift, dict) and "config_schema_hash" in drift and drift["config_schema_hash"] is not None:
        if not isinstance(drift["config_schema_hash"], str):
            errors.append("manifest: 'drift_tracking.config_schema_hash' must be a string when present")
    
    return errors


def _validate_manifest_v1_dict(
    data: Dict[str, Any]  # Legacy flat manifest dict (no format_version)
) -> List[str]:  # Empty list = valid
    """REMOVE-AFTER-OVERHAUL: validate the legacy v1.0 flat manifest layout.
    
    Retires when `cascade_manifests.py` rewrites every production manifest to
    v2.0. Keeps the SG-6 validator working against pre-CR-8 manifests during
    the transition window.
    """
    errors: List[str] = []
    
    # Required string fields. `description` is required per OQ-3 — it's the
    # one human-readable label the substrate genuinely owns + has consumers
    # for; making it dead-letter optional is what SG-6 explicitly fixes.
    for key in ("name", "version", "description", "module", "class", "interface", "python_path"):
        val = data.get(key)
        if val is None or val == "":
            errors.append(f"manifest: required field {key!r} is missing or empty")
        elif not isinstance(val, str):
            errors.append(f"manifest: field {key!r} must be a string, got {type(val).__name__}")
    
    # Interface FQN must be a dotted path (SG-7 format check)
    iface = data.get("interface", "")
    if isinstance(iface, str) and iface and "." not in iface:
        errors.append(
            f"manifest: field 'interface' {iface!r} is not a dotted FQN "
            f"(expected 'module.subpackage.ClassName')"
        )
    
    # Optional fields — type-check only
    for key in (
        "category", "category_override", "conda_env", "db_path",
        "package_source", "installer_version", "installed_at",
    ):
        if key in data and not isinstance(data[key], str):
            errors.append(f"manifest: field {key!r} must be a string when present")
    
    if "env_vars" in data and not isinstance(data["env_vars"], dict):
        errors.append("manifest: field 'env_vars' must be an object when present")
    
    if "config_schema" in data and data["config_schema"] is not None:
        cs = data["config_schema"]
        if not isinstance(cs, dict):
            errors.append("manifest: field 'config_schema' must be an object when present")
        elif "properties" in cs and not isinstance(cs["properties"], dict):
            errors.append("manifest: 'config_schema.properties' must be an object when present")
    
    # Shared helpers for taxonomy + resources (flat-layout path prefix)
    errors.extend(_validate_taxonomy_block(
        data.get("taxonomy"),
        top_level_interface=data.get("interface", "") if isinstance(data.get("interface"), str) else "",
        path_prefix="manifest",
    ))
    errors.extend(_validate_resources_block(data.get("resources"), path_prefix="manifest"))
    
    return errors


def _validate_manifest_dict(
    data: Any  # Loaded manifest JSON
) -> List[str]:  # List of human-readable error messages (empty == valid)
    """SG-6 + CR-8: structural validation, dispatching on `format_version`.
    
    `format_version == "2.0"` validates the nested v2.0 layout.
    Absent `format_version` validates the legacy flat v1.0 layout
    (REMOVE-AFTER-OVERHAUL — retires after cascade_manifests.py).
    Any other value rejects with a single error so unknown future formats
    fail loud rather than silently degrading.
    """
    if not isinstance(data, dict):
        return [f"manifest must be a JSON object, got {type(data).__name__}"]
    
    fmt = data.get("format_version")
    if fmt == "2.0":
        return _validate_manifest_v2_dict(data)
    if fmt is None:
        return _validate_manifest_v1_dict(data)
    return [
        f"manifest: unrecognized format_version {fmt!r}; "
        f"expected '2.0' or legacy (no format_version field)"
    ]


def _validate_plugins_yaml_dict(
    data: Any  # Loaded plugins.yaml content
) -> List[str]:  # List of human-readable error messages (empty == valid)
    """Structural validation of a plugins.yaml file.
    
    Each plugin entry must have name + env_name + package, plus either env_file
    or python_version (one defines how the conda env is created).
    """
    errors: List[str] = []
    if not isinstance(data, dict):
        return [f"plugins.yaml must be a YAML mapping at the top level, got {type(data).__name__}"]
    
    plugins = data.get("plugins")
    if plugins is None:
        return ["plugins.yaml: top-level key 'plugins' is missing"]
    if not isinstance(plugins, list):
        return [f"plugins.yaml: 'plugins' must be a list, got {type(plugins).__name__}"]
    
    seen_names: set[str] = set()
    for i, plugin in enumerate(plugins):
        prefix = f"plugins.yaml: plugins[{i}]"
        if not isinstance(plugin, dict):
            errors.append(f"{prefix}: must be a mapping, got {type(plugin).__name__}")
            continue
        
        # Required string fields
        for key in ("name", "env_name", "package"):
            val = plugin.get(key)
            if val is None or val == "":
                errors.append(f"{prefix}: required field {key!r} is missing or empty")
            elif not isinstance(val, str):
                errors.append(f"{prefix}: field {key!r} must be a string")
        
        # Name uniqueness
        name = plugin.get("name")
        if isinstance(name, str) and name:
            if name in seen_names:
                errors.append(f"{prefix}: duplicate plugin name {name!r}")
            seen_names.add(name)
        
        # Env creation: env_file OR python_version (at least one)
        if "env_file" not in plugin and "python_version" not in plugin:
            errors.append(
                f"{prefix}: must declare either 'env_file' or 'python_version' "
                f"to specify how the conda env is created"
            )
        
        if "interface_libs" in plugin and not isinstance(plugin["interface_libs"], list):
            errors.append(f"{prefix}: 'interface_libs' must be a list when present")
    
    return errors


def _detect_manifest_format(
    path: Path  # File to inspect
) -> Optional[str]:  # 'manifest' | 'plugins_yaml' | None
    """Auto-detect file format from extension."""
    suffix = path.suffix.lower()
    if suffix == ".json":
        return "manifest"
    if suffix in (".yaml", ".yml"):
        return "plugins_yaml"
    return None

# %% ../nbs/cli.ipynb #babd0a83
@app.command("validate")
def validate_file(
    path:Path=typer.Argument(..., help="Manifest JSON or plugins.yaml to validate"),
    format:Optional[str]=typer.Option(
        None, "--format", "-f",
        help="Override format detection: 'manifest' or 'plugins_yaml'",
    ),
) -> None:
    """SG-6: validate a manifest JSON or plugins.yaml file's structure.
    
    Auto-detects format from the file extension (`.json` → manifest,
    `.yaml`/`.yml` → plugins.yaml). Exits non-zero with a list of validation
    errors if any check fails.
    """
    if not path.exists():
        typer.echo(f"File not found: {path}", err=True)
        raise typer.Exit(code=1)
    
    fmt = format or _detect_manifest_format(path)
    if fmt is None:
        typer.echo(
            f"Cannot detect format from extension {path.suffix!r}. "
            f"Pass --format manifest or --format plugins_yaml.",
            err=True,
        )
        raise typer.Exit(code=1)
    
    try:
        if fmt == "manifest":
            with open(path) as f:
                data = json.load(f)
            errors = _validate_manifest_dict(data)
            kind = "manifest"
        elif fmt == "plugins_yaml":
            with open(path) as f:
                data = yaml.safe_load(f)
            errors = _validate_plugins_yaml_dict(data)
            kind = "plugins.yaml"
        else:
            typer.echo(f"Unknown format: {fmt!r}", err=True)
            raise typer.Exit(code=1)
    except (json.JSONDecodeError, yaml.YAMLError) as e:
        typer.echo(f"Parse error in {path}: {e}", err=True)
        raise typer.Exit(code=1)
    
    if errors:
        typer.echo(f"✗ {path} ({kind}): {len(errors)} error(s)", err=True)
        for err in errors:
            typer.echo(f"  - {err}", err=True)
        raise typer.Exit(code=1)
    
    typer.echo(f"✓ {path} ({kind}): valid")
