"""Shared cryptographic hashing primitives for content integrity verification"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils/hashing.ipynb.

# %% auto #0
__all__ = ['hash_bytes', 'hash_file', 'verify_hash']

# %% ../../nbs/utils/hashing.ipynb #cell-imports
import hashlib
from pathlib import Path
from typing import Union

# %% ../../nbs/utils/hashing.ipynb #cell-hash-bytes
def hash_bytes(
    content: bytes,  # Byte content to hash
    algo: str = "sha256"  # Hash algorithm name (e.g., "sha256", "sha3_256")
) -> str:  # Hash string in "algo:hexdigest" format
    """Compute a hash of byte content."""
    return f"{algo}:{hashlib.new(algo, content).hexdigest()}"

# %% ../../nbs/utils/hashing.ipynb #cell-hash-file
def hash_file(
    path: Union[str, Path],  # Path to file to hash
    algo: str = "sha256",  # Hash algorithm name
    chunk_size: int = 8192  # Read chunk size in bytes
) -> str:  # Hash string in "algo:hexdigest" format
    """Stream-hash a file without loading it entirely into memory."""
    h = hashlib.new(algo)
    with open(path, 'rb') as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return f"{algo}:{h.hexdigest()}"

# %% ../../nbs/utils/hashing.ipynb #cell-verify-hash
def verify_hash(
    content: bytes,  # Content to verify
    expected: str  # Expected hash in "algo:hexdigest" format
) -> bool:  # True if content matches expected hash
    """Verify content against an expected hash string."""
    algo, _ = expected.split(":", 1)
    return hash_bytes(content, algo) == expected
